### ISSUE TITLE
Task Error gives no clue to issue

### ISSUE THREAD

**Issue by kgeographer** [frictionlessdata/frictionless-py#1000]
Using v3.31.0, which has been working for a couple years in my app, I try to trap or report errors with this:
```
from frictionless import validate
...
def validate_tsv(file, ext):
  try:
    report = validate(file, schema=myschema, sync_schema=True)
  except:
    err = sys.exc_info()
    print('error on fvalidate',err)    
    print('error args',err[1].args)    
  print(report)
```

Now validating a .tsv file with 23,000 lines. the validation fails with only the `report`:

```
{	'version': '3.31.0', 
	'time': 0.038, 
	'valid': False, 
	'stats': {'errors': 1, 'tables': 0}, 
	'errors': [
		{	'code': 'task-error', 
			'name': 'Task Error', 
			'tags': ['#general'], 
			'note': '', 
			'message': 'The validation task has an error: ', 
			'description': 'General task-level error.'}
		], 
	'tables': []
}
```
By splitting the file I see that it fails somewhere between row 5000 and row 8000, but I have no way of telling what the issue is. The text by the way includes many Polish language characters, but the file is utf-8 and many other similar files have validated without issue over the years.

I know there is a much more current version, but when I upgrade to it, I get an error that `sync_schema` is not a recognized parameter. I've spent several hours at this now, tweaking the input file in various ways, to no avail.

**Comment by lwinfree** [comment]
hi @kgeographer have you tried using `schema_sync` in the current version of Frictionless-py? https://framework.frictionlessdata.io/docs/guides/framework/detector-guide/#schema-sync I think that is the current, correct syntax (instead of `sync_schema`). Let me know if that fixes your problem after updating!

**Comment by kgeographer** [comment]
Thanks for noting that. I saw that upgrading requires a refactoring, and wanted to avoid that right away -- but I'll add that to my TODOs -- good practice before I fall another point release behind. Maybe it will result in more informative Task Error reports. Anyway, the immediate problem, failing "silently" was solved in a random fix: I changed the order of columns in the .tsv file. Go figure.

**Comment by lwinfree** [comment]
Great! :-)
