### ISSUE TITLE
Sort field descriptors semantically instead of alphabetically in YAML files

### ISSUE THREAD

**Issue by mcnoat** [frictionlessdata/frictionless-py#1002]
# Overview
Currently the [field descriptors](https://specs.frictionlessdata.io/table-schema/#field-descriptors) in a YAML file for table schemas are sorted alphabetically. This results in the following order:
* `description`
* `name`
* `title`
* `type`

(As far as I can tell, example isn't implemented yet, although it's [documented](https://specs.frictionlessdata.io/table-schema/#field-descriptors).)

A typical use case for researchers looking at someone else's CSV files that have been documented with Frictionless Data, is that they consult the YAML file if they don't understand the meaning of a heading in the CSV file. Hence, I would argue that the `name` attribute should be at the top. I think there are different solutions for the ordering after that. One could be:
* `name`
* `type`
* `title`
* `description`

Whatever, the final ordering is, I think that putting `name` first is the most helpful change. The rest could follow the schema succinct (`name`) towards less succinct (`description`).

# Implementation
I'm not a very experienced programmer, but thinking about the implementation a bit made me realize that this is not a trivial issue. The best idea I have is to refactor the different groups of descriptors (data resource descriptors, table schema descriptors, etc.) into [Enum](https://docs.python.org/3/library/enum.html)-esque classes that have a sorting logic build into them.

# JSON files
Interestingly, files created with `to_json` seem to be sorted by the order the fields are initialized in the Python script. Perhaps an easier solution than the "semantic sorting" proposed here would be to implement the same behavior for `to_yaml`. In the "initialization order" `name` and `type` come first (if `.infer()` has been called) and the rest of the order is up to the user.

**Comment by roll** [comment]
Hi @mcnoat,

I think it's a really good idea and for myself, I also was thinking of something like this while getting `frictionless` output in CLI not perfectly readable

**Comment by roll** [comment]
@aivuk 
WDYT? It might be an interesting issue to take a look.

Let's discuss implementation details in the issue first and I think we can build it.

**Comment by roll** [comment]
@mcnoat 
I'm releasing a new version with improved order:

```yaml
# --------
# metadata: data/table.csv
# --------

path: data/table.csv
name: table
profile: tabular-data-resource
scheme: file
format: csv
hashing: md5
encoding: utf-8
schema:
  fields:
    - type: integer
      name: id
    - type: string
      name: name
```
