### ISSUE TITLE
Upgrade Typer version because of the Click problem

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#1011]
# Overview

- https://github.com/tiangolo/typer/pull/375

**Comment by areleu** [comment]
This brought me problems today, any recommendation on what to do in the meantime?

Update: For now I added a version constraint for click (>=8.0, <8.1) into my dependency chain and it worked without issues.

**Comment by roll** [comment]
@areleu 
Yes I wanted to propose the same (downgrading to `click==8.0.4`)

**Comment by tiangolo** [comment]
Hello! I just released Typer `0.4.1`, you can now upgrade the version and it should handle it. :rocket: :nerd_face:

**Comment by roll** [comment]
Thanks @tiangolo!

TBH I'm not sure why `click` dropped this deprecated API on a minor release. I would expect it happening on a major release
