### ISSUE TITLE
Error reading a simple JSON file

### ISSUE THREAD

**Issue by mcarans** [frictionlessdata/frictionless-py#1017]
# Overview

I'm not sure if I have missed something but the following code to read a simple JSON file gives an error with a message that doesn't help with diagnosing the problem: `frictionless.exception.FrictionlessException: [resource-error] The data resource has an error: cannot extract metadata "https://raw.githubusercontent.com/OCHA-DAP/hdx-python-scraper/main/tests/fixtures/additional_json.json" because ""`

This used to work fine with Tabulator and is hopefully the last hurdle to overcome to complete the switch to Frictionless. I've made a cut down example:

```python
from pprint import pprint
import frictionless
url = "https://raw.githubusercontent.com/OCHA-DAP/hdx-python-scraper/main/tests/fixtures/additional_json.json"
resource = frictionless.Resource(url)
resource.open()
pprint(resource.read_rows())
resource.close()
```

The JSON looks like this:
```json
[
  {
    "Country Code": "#country+code",
    "Country Name": "#country+name",
    "Population": "#population"
  },
  {
    "Country Code": "AFG",
    "Country Name": "Afghanistan",
    "Population": 38041754
  }
]
```

**Comment by roll** [comment]
Hi @mcarans,

By defaultr `Resource` expects a metadata if the extension is JSON/YAML so in this case we explicitly use the `path` keyword argument. It's not needed for other formats like `csv`.

```
url = "https://raw.githubusercontent.com/OCHA-DAP/hdx-python-scraper/main/tests/fixtures/additional_json.json"
resource = frictionless.Resource(path=url)
# To understand better why it works it's the same as
resource = frictionless.Resource({"path": url})
```

The initial version is guessed to be:

```python
resource = frictionless.Resource(url)
resource = frictionless.Resource(descriptor=url) # as it's JSON - probably metadata
```

As an integrator you probably are interested in always using explicit keyword arguments and more specific functions e.g. `validate_resource` vs `validate` to reduce guessing.

**Comment by roll** [comment]
Please let me know if I can help with something else. And congrats on your migration! Frictionless should be much faster and in-general is much better designed as a consistent data tool (over the set of prev libs)

**Comment by roll** [comment]
Probably one thing I need to mention:
- Frictionless casts and validate data by default (including schema inferring) if you use `resource.read_rows`
- Frictionless can be more similar to `tabulator` if you use `resource.read_lists` (raw data)
