### ISSUE TITLE
Incorrect reading of 3 line header that includes merged cells

### ISSUE THREAD

**Issue by mcarans** [frictionlessdata/frictionless-py#1024]
# Overview

I'm having trouble getting Frictionless to read a spreadsheet that has a 3 line header that includes merged cells. It used to be read correctly by Tabulator. Correct reading would give headers like "Current Phase P3+ #"

```python
from pprint import pprint
import frictionless
from frictionless.plugins.excel import ExcelDialect
url = "http://map.ipcinfo.org/api/public/population-tracking-tool/data/2017,2022/?page=1&limit=1&condition=A&export=true&country=AF"
dialect = ExcelDialect(sheet="IPC", fill_merged_cells=True)
layout = frictionless.Layout(header_rows=[10, 12])
resource = frictionless.Resource(url, format="xlsx", dialect=dialect, layout=layout)
resource.open()
pprint(resource.read_rows()[:4])
resource.close()
```

Adding file here for future reference:
[Afghanistan - IPC Analysis 2017-2022.xlsx](https://github.com/frictionlessdata/frictionless-py/files/8484644/Afghanistan.-.IPC.Analysis.2017-2022.xlsx)

**Comment by mcarans** [comment]
@roll I found the issue where you fixed this in Tabulator: https://github.com/frictionlessdata/tabulator-py/issues/320. You made this fix: "I hope I have found the problem. It seems self.__sheet.merged_cells.ranges was changed in-place during merging so some ranges were skipped" - maybe the solution is the same for Frictionless?

https://github.com/frictionlessdata/tabulator-py/commit/0d09eeef6eea5ea525ed4d130bf055e4746a9b47

**Comment by roll** [comment]
Thanks @mcarans! 

I'll fix it

**Comment by roll** [comment]
Hi @mcarans,

Sorry it wasn't explicetely stated in the documentation but in Frictionless we try to be more compliant with Frictionless Standards regarding `header_rows` so it now supports only full list of row numbers NOT a range limits as it was in `tabulator`:

https://github.com/frictionlessdata/frictionless-py/pull/1028/files#diff-aa3789bb8ac1441b16a3b5a9675097ed2f68edde1a835bd946cb0a1d9d983069R368-R373

It also can be written as like:

```python
layout = Layout(header_rows=list(range(10,13))
```
