### ISSUE TITLE
Code error in frictionless-cars notebook

### ISSUE THREAD

**Issue by shashigharti** [frictionlessdata/frictionless-py#1034]
In this notebook "frictionless-cars", the wikipedia header has changed so it has broken some parts of the code.

![screenshot-nimbusweb me-2022 04 15-16_57_56](https://user-images.githubusercontent.com/5582809/163564564-f99cf15e-b5ee-469b-b880-7743d40632cf.png)
![screenshot-colab research google com-2022 04 15-16_58_49](https://user-images.githubusercontent.com/5582809/163564570-27adeb48-fc10-4b60-bdcb-29ec5e06eff7.png)

**Comment by shashigharti** [comment]
@lwinfree this is not in github repo. We can use "open in google collab" link in this notebook to open it in the google collab. As we discussed shall we add it in the website repo?

**Comment by lwinfree** [comment]
Hi @shashigharti! Yes, please go ahead and try to add this notebook to the github repo so it can be edited more easily. Here are the steps you'll need to do (there might be more steps as well, I'm not totally sure if this will work!):

- The notebooks are currently linked through the header in this file: https://github.com/frictionlessdata/frictionless-py/blob/main/site/docusaurus.config.js starting on line 84. You'll need to change that whole notebooks section to something like this: 
```
    {
          to: "docs/tutorials/notebooks",
          label: "Notebooks",
          position: "left",
    },
```

- then, you will need to create the notebooks folder here https://github.com/frictionlessdata/frictionless-py/tree/main/docs (similar to the guides folder). 

- Save each colab notebook as a copy in Github. I'm assuming this saves them as .ipynb files (though I have not confirmed this). Save them in the new notebooks folder you created in the previous step. I'm assuming that the docs site will be able to render the notebooks, but it might not work. My hope is that it will render correctly!

Let me know if you have any issues with this or want some help! Also, you can run the docs site locally to check your work as you go (I think you know how to do this, but again, let me know if you need help!) Thanks!

**Comment by shashigharti** [comment]
Thank you @lwinfree
