### ISSUE TITLE
A wrong CSV that passes validation

### ISSUE THREAD

**Issue by aborruso** [frictionlessdata/frictionless-py#1048]
# Overview

Hi, if I run validate on [this bad "CSV"](https://gist.githubusercontent.com/aborruso/b868ee7fe11137927f3af7bf4845a2e8/raw/95cff4b1d97b4085342a4847dca9bc0e0c9b4d62/tmp.csv), I have no error.

But it has an error on line 35, a `"` to remove.

This CSV has 21.692 rows and one header row, but if you validate it, you have back `"rows": 21624`.

If you remove the `"` you have on line 35, and validate it, you have the right result: `"rows": 21692`.

Moreover in line 36 I have 10 field separator and not 9.

I'm using frictionless-4.29.0

Thank you

**Comment by roll** [comment]
Thanks @aborruso, we will investigate

**Comment by shashigharti** [comment]
@roll Total rows 21692; A  double quote starts in line 35 and the mapping ending quote is found in line 103.   (103-35 = 68) rows data are taken as a single string. So the total of 68 rows becomes 1 and row count becomes 21624.

**Comment by aborruso** [comment]
> @roll Total rows 21692; A double quote starts in line 35 and the mapping ending quote is found in line 103.

Yes, this is one of the error: a quote without ending quote at row 35.

And there is another one at row 36: you have an incorrect number of field separators. 

You can view all in this diff, between wrong input rows and corrected rows https://gist.github.com/aborruso/cdfbd59a30504c544bf21259ce782a09/revisions?diff=split#diff-0e5523056ab6dbb2a3bfa672b305d76b003954fa5a1bcc8de29528c2ad79b2ed=

Thank you

**Comment by shashigharti** [comment]
Thank you @aborruso

**Comment by lwinfree** [comment]
@roll please take a look - maybe disable dialect? (notes from chatting earlier)

**Comment by roll** [comment]
Hi @aborruso and @shashigharti,

Unfortunatelly I don't see how the machine can detect human intention in this file. As Sashi mentioned, this CSV looks pretty valid if we consider that there is a long quoted cell from line 35 to line 103. So the Python parser reads it this way and only then Frictionless does its job.

If we disable quoting:

```bash
$ frictionless validate tmp/issue1048.csv --dialect '{"quoteChar": ""}'
# -------
# invalid: tmp/issue1048.csv
# -------

===  =====  ==========  =================================================================
row  field  code        message
===  =====  ==========  =================================================================
 36     11  extra-cell  Row at position "36" has an extra value in field at position "11"
===  =====  ==========  =================================================================
```

I think we can add a builtin custom check that detects ouliners in cell size. For example, in this file all the column's cells have similar size with one obvious outliner.

cc @aivuk

**Comment by roll** [comment]
Hi @shashigharti,

I think we can close this issue by creating a feature request for detecting cell outliners (a custom check or maybe an extension for `checks.devitated_value`) and providing this CSV as an example

**Comment by shashigharti** [comment]
Closing this issue and created new issue #1066 to add the check to detect cell outliners.

cc @roll @aborruso

**Comment by shashigharti** [comment]
Hi @aborruso,

First I would like to thank you for reporting this and your valuable input.  We have added 'deviated-cell' check in newly released version 'v4.38.0' which identifies  any discrepancies in data like in this csv that you have shared. Running the check in this file gives the following message:

```
report = validate(
        "../data/issue-1066.csv",
        checks=[checks.deviated_cell()]
    )
report.flatten(['code', 'description', 'message'])
```
```
[['deviated-cell',
  'The cell is deviated.',
  'There is a possible error because the cell is deviated: cell at row "35" and field "Gestore" has deviated size']]
```

Please let us know your thoughts on it!. Thanks again!

**Comment by aborruso** [comment]
> Please let us know your thoughts on it!. Thanks again!

I think that this is a great project :)

I have installed v4.38.0, and when I run validate I have no error. Is it normal?

![image](https://user-images.githubusercontent.com/30607/168771981-8c4a8bca-38fc-4a74-b09e-e40adbf93372.png)

**Comment by shashigharti** [comment]
Thanks! Sorry I forgot to inform that we are still working on exposing this check through CLI. We will inform you once it is added.
