### ISSUE TITLE
Type detection is incorrect for sparse dataset

### ISSUE THREAD

**Issue by rad-pat** [frictionlessdata/frictionless-py#1050]
With a sparse dataset, the type is not detected correctly. It is easiest to show by an example which I expect should be detected as integer, but in fact resolves to 'any'. 

```
import frictionless

with frictionless.Resource(
        data=[["Heading1"], ['0'], ['1'], [''], [''], ['']],
        trusted=True,
        detector=frictionless.Detector(
            sample_size=6,
            field_confidence=0.5
        )
) as resource:
    print(resource.schema)

>>> {'fields': [{'name': 'Heading1', 'type': 'any'}]}
```
100% of the populated values are integer, the problem is that the scoring is not re-evaluated when a missing value is encountered. I have a code change which fixes the issue. I will put it in a PR.

**Comment by roll** [comment]
Thanks @rad-pat!

**Comment by roll** [comment]
@aivuk 
Please take a look, it's related to #891

**Comment by aivuk** [comment]
I did it @roll, checked the PR it works well, but I left a comment regarding some additional tests that I think it would be a good idea to add.
