### ISSUE TITLE
Add tutorial for new features added

### ISSUE THREAD

**Issue by shashigharti** [frictionlessdata/frictionless-py#1058]
# Add tutorial for new features

* pretty print feature for metadata.
* Excel stats 
* to_markdown feature for metadata.
* to_excel_template feature to export table schema as excel.

**Comment by lwinfree** [comment]
I'm going to re-open this so @shashigharti can add some more text to describe the code. For example, you could add more description on line 5 (transform to package). What do these transform steps do? Why are you doing them? If you were going to explain the code out loud to me, what would you say? Write those thoughts :-) 


 I'll edit the text before merging. Thanks!
