### ISSUE TITLE
`header` property from remote dialect not recognized

### ISSUE THREAD

**Issue by peterdesmet** [frictionlessdata/frictionless-py#1076]
When validating a resource against a remote CSV schema, the `header` property is not recognized. It does work when the exact same dialect properties are verbosely included.

- [test.csv](https://github.com/frictionlessdata/frictionless-py/files/8668920/test.csv)
- [test_remote_dialect.txt](https://github.com/frictionlessdata/frictionless-py/files/8668931/test_remote_dialect.txt) (change extension to json)
- [test_verbose_dialect.txt](https://github.com/frictionlessdata/frictionless-py/files/8668933/test_verbose_dialect.txt) (change extension to json)
 
## Remote dialect

```
frictionless validate test_remote_dialect.json
# -------
# invalid: test.csv
# -------

===  =====  =============  ==================================================================================================================================================
row  field  code           message                                                                                                                                           
===  =====  =============  ==================================================================================================================================================
            dialect-error  Dialect is not valid: "Additional properties are not allowed ('header' was unexpected)" at "" in metadata and at "additionalProperties" in profile
===  =====  =============  ==================================================================================================================================================
```

## Verbose dialect

```
frictionless validate test_verbose_dialect.json
# -----
# valid: test.csv
# -----
```

**Comment by roll** [comment]
Thanks! I'll investigate

**Comment by roll** [comment]
@peterdesmet 
Hi, as I figure it out, remote `dialect.header` is not supported in `frictionless@4`. To make it work you need to provide a layout - https://framework.frictionlessdata.io/docs/guides/framework/layout-guide#header

I'm going to fix this problem soon in `frictionless@5` - https://github.com/frictionlessdata/frictionless-py/issues/947 - where dialect/layout/etc will be merged to be compliant to the standards.
