### ISSUE TITLE
Ability to run builtin validation checks via CLI

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#1078]
# Overview

We have builtin checks in the framework which is not enabled by default - https://framework.frictionlessdata.io/docs/guides/validation-checks#table-dimensions. We want a way to enable them via CLI.

I think in general we need to provide a JSON interface to do so. It will be a universal way that supports all the builtin checks and all the enabled via plugins custom checks.

```bash
$ frictionless validate table.csv --checks '[{"code": "table-dimensions", "numRows": 10}]'
```
On the other hand, we might need to provide some shortcuts for most common conditions (again similar for the dialect API). For example:

```bash
$ frictionless validate table.csv --forbidden-values 'columnName:value1,value2,value3' --formula 'columnX > columnY`
```

@shashigharti @aivuk 
Let's discuss what options we'd like to expose

**Comment by aivuk** [comment]
I think a json interface will be a bit cumbersome to use. How about instead of:

`$ frictionless validate table.csv --checks '[{"code": "table-dimensions", "numRows": 10}]'`

We have something like:

`$ frictionless validate table.csv --checks table-dimensions --numRows 10`

Basically we could have a standard interface for all the checks that would be parsed as:
`
$ frictionless validate table.csv --checks CHECK_CODE1 --PARAM_NAME1 PARAM_VALUE1 --PARAM_NAME 2 --PARAM_VALUE2 CHECK_CODE2 ...`

Or something like that (the proposal above would be a bit tricky to separate the checks arguments from the standard command line arguments).

**Comment by roll** [comment]
@aivuk 
The default JSON interface is still good to have as:
- it's a universal way for FD
- we use the same for `dialect/etc`
- it will work for any checks added in the future
- it can be used for non-human CLI usage (JSON stringified)

Another question is that the second way of providing checks might be exactly as you suggest. Of course, it will require some smart CLI coding:

> providing two checks might be a problem for this syntax

```bash
$ frictionless validate table.csv --check CHECK_CODE1 --PARAM_NAME1 PARAM_VALUE1 --PARAM_NAME 2 --PARAM_VALUE2 CHECK_CODE2 
```

OR

... [alternatives]

**Comment by roll** [comment]
@aivuk 
@shashigharti
@aborruso 

Human readable syntax brainstorming:

```bash
$ frictionless validate table.csv --checks duplicate-row deviated-cell forbidden-value:values=a,b,c 
```

**Comment by shashigharti** [comment]
> Human readable syntax brainstorming:
> 
> ```shell
> $ frictionless validate table.csv --checks duplicate-row deviated-cell forbidden-value:values=a,b,c 
> ```
JSON (no comments)
For CLI, I prefer this one

**Comment by aborruso** [comment]
> Human readable syntax brainstorming:

For some commands (dialect) it's possible to use the JSON way, that is the standard FD way.

For the CLI I prefer the last @roll way `frictionless validate table.csv --checks duplicate-row deviated-cell forbidden-value:values=a,b,c `, but I think it should be enabled also for dialect and to other CLI commands that use JSON.

For me it is also okay to use the JSON

**Comment by roll** [comment]
DONE in v5 (#1119) (will be released this month)
