### ISSUE TITLE
Investigate Datasette integration

### ISSUE THREAD

**Issue by aivuk** [frictionlessdata/frictionless-py#1090]
After the experiment https://github.com/aivuk/frictionless-notebooks/blob/main/csv-to-datapackage-to-datasette/Convert%20CSV%20to%20Datapackage%2C%20import%20to%20a%20Sqlite%20and%20use%20it%20with%20Datasette.ipynb to import a csv to datasette:
 
 1. Creating a Datapackage from the CSV using Frictionless framework
 2. Convert the datapackage to a sqlite using https://github.com/kindly/datapackage_convert
 3. Open the sqlite with Datasette
 
We thought about the creation of a Frictionless or a Datasette plugin to automatize the process. The issue here is to investigate how this could be implemented. The possible options are:

 1. Create a Frictionless plugin for Datasette. This would add Datasette and datapackage_convert as a dependency and we would have a new CLI command to convert a csv to datapackage and open it on Datasette.
 2. Create a Datasette plugin where you could provide to datasette or using the UI, or in the CLI a datapackage, and it would open the datapackage on datasette.

I think both options 1 and 2 are worthwhile to implement, the first one to the Frictionless framework users and the second one for the users of Datasette to discover the FD framework.

@roll

**Comment by roll** [comment]
From @amercader 

> This is great, and if we think about it as our "recommended" way of easily publishing a data package we can think of ways of streamline it even more with a package that wraps all steps (or maybe as part of the main frictionless cli? frictionless serve for local datasette instance and even frictionless publish for [fly.io](http://fly.io/), gh pages (?)...

**Comment by roll** [comment]
I've made the issue name broader so we can brainstorm the integration here and then create specific issues bases on this work

**Comment by aivuk** [comment]
I did investigate a bit more on the subject and also considered @amercader ideas. I think the best approach would be in terms of how easy it would be to implement:

 1. Create on frictionless CLI a command to publish a datapackage/csv on fly.io or vercel. This would be easy to do, we would just need to add Datasette as a dependency to FD,  do the steps to convert a datapackage as described [here](https://github.com/aivuk/frictionless-notebooks/blob/main/csv-to-datapackage-to-datasette/Convert%20CSV%20to%20Datapackage%2C%20import%20to%20a%20Sqlite%20and%20use%20it%20with%20Datasette.ipynb) and use Datasette [publish](https://docs.datasette.io/en/stable/publish.html) feature, that can publish to Google Cloud, Heroku, Fly.io and Vercel.
 
 2. Create a Datasette plugin to import directly in Datasette a datapackage. We could do the work based on https://github.com/simonw/datasette-upload-csvs

 3. Looks like the publish to a static site with Datasette using Pyodide is still in development, but  I [read](https://architecturenotes.co/datasette-simon-willison/) (I recommend the article and I think it would be a good idea to @roll  do something similar but about Frictionless) from the Datasette's author that it's one of his priorities now. We could think in adding this to 1, or developing a [Livemark](livemark.frictionlessdata.io/) plugin to add a Datasette/Pyodide to a livemark static website.

**Comment by aivuk** [comment]
@roll just pinging you to discuss the next steps

**Comment by roll** [comment]
To follow in https://github.com/frictionlessdata/frictionless-py/issues/1116
