### ISSUE TITLE
Add default `frictionless` CLI command

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#1095]
# Overview

Currently, we have these commands:
- `frictionless describe`
- `frictionless extract`
- `frictionless validate`
- [coming] `frictionless analyze`
- etc

We'd like to have (note there is no action):

```
$ frictionless table.csv

# Describe

[resource/schema as a table]

# Extract

[first X lines of the data as a table]

# Validate

## Summary

[validation summary table]

## Errors 

[validation errors table]
```

**Comment by shashigharti** [comment]
@roll if user doesn't mention the action, it will run all three possible actions and show the results?

**Comment by roll** [comment]
@shashigharti 
It needs to be a new CLI command e.g. `program.default`:

```
resource = Resource('tabe.csv')
resource.infer()

# show schema as a table using resource.schema (let's prototype and discuss)

# show first X rows as a table using resource.extract

# show validation report using resource.validate
```

We don't need a new `frictionless.actions` for it -- just a new module in `program`

**Comment by shashigharti** [comment]
@roll resource.schema.fields will not be nested in this usecase? 

And to flatten json object what do you think of this library https://pypi.org/project/flatten-json/?

**Comment by roll** [comment]
@shashigharti 
Our goal is provide the most vital information regarding the schema, for example:

```
# Describe

field type required
-------------------
name1 string 
name2 number true
...
```

**Comment by roll** [comment]
Currently, it doesn't seem to be possible to provide a default command the way we want with Typer - https://github.com/tiangolo/typer/issues/18

We will implement a normal command "summary" - `frictionless summary table.csv` - and then @roll will think how we can call it also as the default

**Comment by roll** [comment]
@shashigharti 
As a current quick-fix:

> you can use this in `program.main' for program creation

```python
# Program


# TODO: remove this hack when Typer supports not-found commands catching
# <link to the typer issue>
class Program(typer.Typer):
    def __call__(self, *args, **kwargs):
        if sys.argv[1].count("."):
            sys.argv = [sys.argv[0], "summary", sys.argv[1]]
        return super().__call__(*args, **kwargs)


program = Program()
```

Can you please also create a feature request for Typer? I would say that we'd like to have an ability to catch not found commands or something like this
