### ISSUE TITLE
Resource function to_pandas fails creating index if last field is of type 'datetime'

### ISSUE THREAD

**Issue by henhuy** [frictionlessdata/frictionless-py#1100]
When reading a resource using `to_pandas()`, index is build from primary key.
But while creating index, code looks into last looked-up field instead of index field to get index data type.
If last field type is of type `datetime` or `date`, index column is tried to be converted to DatetimeIndex, but this fails if primary key column is of type `integer`.

I will provide example package.json and propose a fix in PR.

**Comment by shashigharti** [comment]
Thank you @henhuy  for reporting the issue!. We will investigate.

**Comment by henhuy** [comment]
> Thank you @henhuy for reporting the issue!. We will investigate.

Nice! see my PR for a possible solution and initial test which shows the bug. Not sure if I put everything in the right place...

**Comment by shashigharti** [comment]
Thank you! Sure we will review your PR!
