### ISSUE TITLE
Exception on pandas parser when using a datetime column containing timezone information as index 

### ISSUE THREAD

**Issue by aivuk** [frictionlessdata/frictionless-py#1105]
If an user try to load a resource and use a datetime column as index, if this column has timezone information the transform to pandas (.to_pandas()) will give an exception:

`ValueError: Tz-aware datetime.datetime cannot be converted to datetime64 unless utc=True`

An example to reproduce this problem:

datapackage.json

```

{
    "name": "to_pandas_bug",
    "resources": [
        {
            "profile": "tabular-data-resource",
            "name": "timezone-issue",
            "path": "timezone-issue.csv",
            "scheme": "file",
            "format": "csv",
            "encoding": "utf-8",
            "schema": {
                "fields": [
                    {"name": "id", "type": "integer"},
                    {
                        "name": "timestamp",
                        "type": "datetime"
                    }
                ],
                "primaryKey": ["timestamp"]
            },
            "dialect": {"delimiter": ";"}
        }
    ]
}
```
And the data timezone-issue.csv:

```
id;timestamp
0;2020-01-01T15:00:00+03:00
1;2020-01-01T15:00:00+04:00
```
@roll

**Comment by aivuk** [comment]
A possible solution to solve the problem is just to change on __write_convert_type of the pandas plugin:

`"datetime": np.dtype("datetime64[ns]")`

to

`"datetime": pandas.DatetimeTZDtype(tz='UTC')`

This solves the exception issue, but you lost the timezone information when the datetime is converted to UTC. Maybe there is a way to continue with the timezone information without transforming to UTC.

**Comment by roll** [comment]
Thanks!
