### ISSUE TITLE
Implement Datasette integration

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#1116]
# Overview

We'd like to have a nice integration with Datasette. We did initial investigation here - https://github.com/frictionlessdata/frictionless-py/issues/1090

# Implementation

- [ ] We need a new command `frictionless research` (name is pending) that works exactly the same as `frictionless query` but instead of sqlite starts Datasette

**Comment by aivuk** [comment]
Hi @roll  the command would be basically identical to https://github.com/frictionlessdata/framework/blob/2d961d2b83632d12eab1131faa52c13adbc591c5/frictionless/program/query.py except for the last line, from `os.system(f"sqlite3 {database}")` to `os.system(f"datasette {database}")` (or with `-o` to open the browser automatically after the command). Don't you think that it would be better to add a option to query, something like:

`frictionless query --datasette file.csv`

and if the user provide no arguments it opens sqlite as default?

**Comment by roll** [comment]
@aivuk 
I think we will eventually get to what you propose having like:
- frictionless explore source --with visidata/other/etc
- frictionless query source -- with sqlite/datasettte/etc

But for now I thought that using another command for a first version will give us more space for experimenting and thinking on the flags needed (if we need to pass many datasettes flags we will probably not be able to merge commands)

**Comment by aivuk** [comment]
Created a [PR](https://github.com/frictionlessdata/framework/pull/1471) but I just copied the query.py command and added datasette as a dependency to be installed as `pip install frictionless[datasette]`.
