### ISSUE TITLE
CLI: frictionless describe fails on --dialect (for --type package)

### ISSUE THREAD

**Issue by vlcinsky** [frictionlessdata/frictionless-py#1126]
```
$ frictionless describe --dialect '{"delimiter": ";"}' --type package country-2.csv 
Package.__init__() got an unexpected keyword argument 'dialect'
```
## missing CLI option to describe a package for a directory of CSV files with non-default delimiter
CLI allows to infer schema and resource for a CSV using non-default delimiter such as ";"

However, for package, CLI shows `--dialect` option in help, but using it ends with error message which looks like internal error.

My use case is: having a directory full of CSV files with ";" as a delimiter I would like to describe the whole package using CLI.

**Comment by shashigharti** [comment]
Thank you @vlcinsky for reporting it. Looks like it fails when we use it with package. We will investigate it further.

**Comment by roll** [comment]
@shashigharti 
I think we can have dialect argument in the Package constructor forwarding it to underlying resources in the `package.metadata_process` -- let's discuss next Monday

**Comment by shashigharti** [comment]
@roll in metadata_process did you mean setting dialect property as follows?
```
                resource.onerror = self.__onerror
                resource.trusted = self.__trusted
                resource.dialect = self.get("dialect")
```

**Comment by roll** [comment]
@shashigharti 
Probably in the constructor:

```python
                    resource = Resource(
                        resource,
                        dialect=self.dialect,
                        basepath=self.__basepath,
                        detector=self.__detector,
                        hashing=self.__hashing,
                    )
```

In general, I'm reworking this part of the framework (metadata_ methods) so let's make it work for now and then I'll reduce the complexity
