### ISSUE TITLE
Storing custom checks inside resource descriptors in `datapackage.json`

### ISSUE THREAD

**Issue by fjuniorr** [frictionlessdata/frictionless-py#1131]
If I have an inquiry in a file `inquiry.json` with a given `row-constraint` check, say: 

```json
{
  "tasks": [
    {
      "path": "data.csv",
      "schema": "tableschema.json",
      "checks": [
        {
          "code": "row-constraint", 
          "formula": "remuner > rem_pos"
        }
      ]
    }
  ]
}
```

I can execute it in the CLI with `frictionless validate inquiry.json`. 

Is there any standard way to store this information inside a resource descriptor so that it would be run during a call to `frictionless validate datapackage.json`?

**Comment by roll** [comment]
Thanks @fjuniorr, I'll check if we can support it in v5 (I'm working on now)

**Comment by roll** [comment]
It's now supported in v5 and we will provide an introductory blog for all new features including this one when v5 is released (in around a month) :+1:

**Comment by roll** [comment]
DONE in #1119
