### ISSUE TITLE
Review the documentation for v5

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#1133]
# Overview

We need to review and update (when needed) the documentation for v5

---

Please PR v5 branch

**Comment by roll** [comment]
DONE in https://github.com/frictionlessdata/frictionless-py/pull/1119

**Comment by aborruso** [comment]
Hi @roll is there a public url to preview the 5.0 documentation?

Thank you

**Comment by roll** [comment]
Hi @aborruso the docs now are:
- v5: https://framework.frictionlessdata.io/
- v4: https://v4.framework.frictionlessdata.io/

**Comment by aborruso** [comment]
WOW!!!

Thank you
