### ISSUE TITLE
to_pandas should create datetime64 for date columns

### ISSUE THREAD

**Issue by jze** [frictionlessdata/frictionless-py#1138]
# Overview

When converting resources to panda dataframes the `to_pandas` method uses `object` data type for columns that have been defined as `date` in the *Table Schema*. It would be more convenient (and more intuitive) if columns with type `date` would have the correct data type. 

Here is a small example:

```python
from frictionless import Resource
import pandas as pd
r = Resource('https://opendata.zitsh.de/frictionless/pegel_wasserstand.json')
df = r.to_pandas()

df['Zeit [MEZ]'] = pd.to_datetime(df['Zeit [MEZ]']) # this line should not be necessary
df = df.set_index('Zeit [MEZ]')

df.loc['2022'].plot()
```

**Comment by roll** [comment]
Thanks @jze! We will investigate
