### ISSUE TITLE
`frictionless validate` no longer accepts list of resources

### ISSUE THREAD

**Issue by peterdesmet** [frictionlessdata/frictionless-py#1140]
According to the specs,  resource path should accept a list of files:

> To support this use case the path property MAY be an array of strings rather
than a single string:

Since frictionless v4.40.0, this causes an error:

```
TypeError: stat: path should be string, bytes, os.PathLike or integer, not list
```

I make extensive use of list of paths, so I hope this can be fixed. 😄 

## Test files

datapackage.json:
```
{
  "profile": "tabular-data-package",
  "resources": [
    {
      "name": "measurements",
      "path": [
        "https://github.com/frictionlessdata/frictionless-py/files/8941635/file_1.csv",
        "https://github.com/frictionlessdata/frictionless-py/files/8941634/file_2.csv"
      ],
      "profile": "tabular-data-resource",
      "schema": {
        "fields": [
          {
            "name": "location",
            "type": "string"
          },
          {
            "name": "measurement",
            "type": "number"
          }
        ]
      }
    }
  ]
}
```
[file_1.csv](https://github.com/frictionlessdata/frictionless-py/files/8941635/file_1.csv)
[file_2.csv](https://github.com/frictionlessdata/frictionless-py/files/8941634/file_2.csv)

**Comment by shashigharti** [comment]
Thank you for reporting!. We will investigate it further and fix it.

**Comment by peterdesmet** [comment]
👋 @roll is there a unit test to prevent this?

**Comment by roll** [comment]
@shashigharti 
Can you please add one? We should have packages like this in data. THe problem was only related to the CLI (report.to_summary)

**Comment by shashigharti** [comment]
Sure I will add the test.

**Comment by roll** [comment]
@peterdesmet 
The fix is on its way. There are still a few improvements we need to add to the summary though
