### ISSUE TITLE
Using Row retrieved by extract(stream=True) in dict-unpacking function invocation ("double star" f(**row)) can fail

### ISSUE THREAD

**Issue by hjoukl** [frictionlessdata/frictionless-py#1152]
Hi,

many thanks for this cool new library - I've successfully used the fine tableschema- and datapackage-py libs in the past. This looks like a
very nice successor.

Environment: Python 3.6 - frictionless frictionless 4.40.3

I've run into "disturbing behaviour" ;-) when trying to add `description` and `example` attributes to a Resource object's table schema fields. Problem: I want to add to the info gathered by `frictionless.describe(<csv file>)`, namely additional field `description` and `example` attributes. For the examples I'd like to simple read the 1st data row and use these values as example values.

Here's a minimal example that provokes the bug(?) for me:

Data: `$ cat colors.csv`

```
id,color,description
1,red,The color of blood
2,green,The color of hope
3,blue,The color of oceans
4,yellow,Bright as the sun
5,black,Dark as the night
```

Program: `$ cat test_read_resource_examples.py`
```python
import frictionless


def add_attr(resource, attr_name, **field_attrs):
    """Add attr: value to data resource table schema fields for each field in
    {field_name: value} field dict.
    """
    for field in resource['schema']['fields']:
        field[attr_name] = field_attrs[field['name']]
    return resource


datafile = 'colors.csv'
resource = frictionless.describe(datafile)

# add additional attributes to resource table schema fields
add_attr(resource, 'description', id='The color ID', color='The color name',
         description='The exhaustive color description')
print(resource)

# read 1st resource table row for use as examples
example_row = next(resource.extract(stream=True))
#print(example_row)  # Uncommenting this print() line makes the program work!
add_attr(resource, 'example', **example_row)
print(example_row['color'])
```

Running this fails:
```
$ .venv/dev-venv2/bin/python test_read_resource_examples.py 
{'encoding': 'utf-8',
 'format': 'csv',
 'hashing': 'md5',
 'name': 'colors',
 'path': 'colors.csv',
 'profile': 'tabular-data-resource',
 'schema': {'fields': [{'description': 'The color ID',
                        'name': 'id',
                        'type': 'integer'},
                       {'description': 'The color name',
                        'name': 'color',
                        'type': 'string'},
                       {'description': 'The exhaustive color description',
                        'name': 'description',
                        'type': 'string'}]},
 'scheme': 'file'}
Traceback (most recent call last):
  File "test_read_resource_examples.py", line 24, in <module>
    add_attr(resource, 'example', **example_row)
  File "test_read_resource_examples.py", line 9, in add_attr
    field[attr_name] = field_attrs[field['name']]
KeyError: 'id'
```

However, if I just uncomment the `print(example_row)` line...

```
$ .venv/dev-venv2/bin/python test_read_resource_examples.py 
{'encoding': 'utf-8',
 'format': 'csv',
 'hashing': 'md5',
 'name': 'colors',
 'path': 'colors.csv',
 'profile': 'tabular-data-resource',
 'schema': {'fields': [{'description': 'The color ID',
                        'name': 'id',
                        'type': 'integer'},
                       {'description': 'The color name',
                        'name': 'color',
                        'type': 'string'},
                       {'description': 'The exhaustive color description',
                        'name': 'description',
                        'type': 'string'}]},
 'scheme': 'file'}
{'id': 1, 'color': 'red', 'description': 'The color of blood'}
red
```

... it suddenly works?!

I'm unsure if that actually _should_ work or if I'm doing s.th. unsupported, e.g. by adding to the Resource schema fields through its dict interface (I've noticed there's also `example` and `description` properties).
That said I found the behaviour rather surprising  :-) - what kind of "sync" does the row stdout output provoke to make it function? Do I somehow accidentally corrupt the Resource (meta)data?

Again, thanks for the cool library.

Best, 
Holger

**Comment by shashigharti** [comment]
Thank you for reporting! We will investigate it.

**Comment by hjoukl** [comment]
Thanks for investigating!

Switching to using properties instead of dict item access does not help. I.e. changing my `add_attr` function to
```python
def add_attr(resource, attr_name, **field_attrs):
    """Add attr: value to data resource table schema fields for each field in
    {field_name: value} field dict.   
    """                               
    for field in resource.schema.fields:    
        attr_value = field_attrs[field.name]
        setattr(field, attr_name, attr_value)
    return resource
```
makes no difference (albeit looking cleaner ;-)).

However, I think I've found the culprit: When trying to add `example` Field properties I'm reading the 1st row like this: 
```
example_row = next(resource.extract(stream=True))
````
(not quite sure if that's how one _should_ do this but I haven't found a way to only read the 1st data line)

Now, I go on to hand the `Row` object into the `add_attr` function using dict unpacking:
```
add_attr(resource, 'example', **example_row)
```
The reason this doesn't work without a call to `__str__` (or `__repr__`, for that matter) is that these methods invoke `self.__process()`:

https://github.com/frictionlessdata/frictionless-py/blob/72e1391b41094678e97c1a3e386703f6e193c96d/frictionless/row.py#L58-L60

Debugging 
```python
# read 1st resource table row for use as examples
example_row = next(resource.extract(stream=True))
import pdb; pdb.set_trace()
print(example_row)  # Uncommenting this print() line makes the program work!   
```
shows that the dict-unpacked function args are empty _unless_ the Row arg has `self._process()`ed:
```
$ .venv/dev-venv2/bin/python test_read_resource_examples.py 
> test_read_resource_examples.py(25)<module>()
-> print(example_row)  # Uncommenting this print() line makes the program work!
(Pdb) s
--Call--
> .venv/dev-venv2/lib/python3.6/site-packages/frictionless/row.py(58)__str__()
-> def __str__(self):
(Pdb) 
> .venv/dev-venv2/lib/python3.6/site-packages/frictionless/row.py(59)__str__()
-> self.__process()
(Pdb) 
--Call--
> .venv/dev-venv2/lib/python3.6/site-packages/frictionless/row.py(267)__process()
-> def __process(self, key=None):
(Pdb) 
> .venv/dev-venv2/lib/python3.6/site-packages/frictionless/row.py(274)__process()
-> if self.__processed:
(Pdb) p self._Row__processed
False
(Pdb) 
```

Without the `__str__(...)` invocation no `self.__process()` is done and the dict-unpacking code leads to an empty function kwargs dict:
```
$ .venv/dev-venv2/bin/python test_read_resource_examples.py 
.venv/dev-venv2/lib/python3.6/site-packages/requests/__init__.py:104: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  RequestsDependencyWarning)
> test_read_resource_examples.py(27)<module>()
-> add_attr(resource, 'example', **example_row)
(Pdb) s
--Call--
> test_read_resource_examples.py(4)add_attr()
-> def add_attr(resource, attr_name, **field_attrs):
(Pdb) s
> test_read_resource_examples.py(8)add_attr()
-> for field in resource.schema.fields:
(Pdb) p field_attrs
{}
(Pdb) 
```

So, naive `**row` usage of a row retrieved through `resource.extract(stream=True)` doesn't work.
Not sure if that's expected or intentional, I find it surprising. So imho it should at least be documented...

**Workaround**: 
Do the dict-unpacking function invocation using `to_dict`:
```
add_attr(resource, 'example', **example_row.to_dict())
```
Which runs `self.__process()` (sidenote: Possible micro-optimization in https://github.com/frictionlessdata/frictionless-py/blob/72e1391b41094678e97c1a3e386703f6e193c96d/frictionless/row.py#L248-L251: Only `import_module("frictionless.plugins.json")` conditionally i.e. in the code path where plugin is actually used)

**Proper fix**:
Override dict-unpacking in `Row`. Surprisingly, this can **not** be easily achieved: Since Row is a `dict` subclass, (C)Python circumvents the usual dunder method machinery (see e.g. https://stackoverflow.com/a/19526400/7379507 or https://treyhunner.com/2019/04/why-you-shouldnt-inherit-from-list-and-dict-in-python/) i.e. overriding `keys()` and `__getitem__` and putting `self.__process()` in there doesn't gain you anything. Because these are simply not called for a `f(**row)` call.

So to do it `Row` would need to 

- inherit from `collections.UserDict` instead (https://docs.python.org/3.10/library/collections.html#collections.UserDict) or
- inherit from `collections.abc.MutableMapping` (https://docs.python.org/3/library/collections.abc.html#collections.abc.MutableMapping)

No idea about performance implications.

Best,
Holger

**Comment by hjoukl** [comment]
Just noticed that the title "Dynamically adding information to Resource's schema fields through dict interface provokes incomplete extract(stream=True) result row" was misleading imho, so changed it.

**Comment by roll** [comment]
Hi @hjoukl!

The problem is that the row is lazy evulated (that's why print fixes it). We can make the code work by using `row.to_dict()`:

```python
example_row = resource.read_rows(size=1)[0]  # also we can simplify the reading
add_attr(resource, "example", **example_row.to_dict())
```

Currently, we're in v5 reworking the way Frictionless works with Metadata; making it simpler and easier. The next step for us will be revising the `Row` class; maybe also making it simpler to prevent this kind of edge case confusing sutuations

**Comment by hjoukl** [comment]
I see. So exactly what I noticed in my previous comment:

> **Workaround**: Do the dict-unpacking function invocation using `to_dict`:
> 
> ```
> add_attr(resource, 'example', **example_row.to_dict())
> ```
> Which runs `self.__process()` (sidenote: Possible micro-optimization in
> 
> https://github.com/frictionlessdata/frictionless-py/blob/72e1391b41094678e97c1a3e386703f6e193c96d/frictionless/row.py#L248-L251
> : Only `import_module("frictionless.plugins.json")` conditionally i.e. in the code path where plugin is actually used)

Thanks for the update,
Holger

**Comment by roll** [comment]
Ohh I missed the last bit 👍
