### ISSUE TITLE
field_filter modifies order of labels, but not of values

### ISSUE THREAD

**Issue by vlcinsky** [frictionlessdata/frictionless-py#1155]
transformation pipeline provides function `field_filter` which is not documented much.

My initial expectation was it would take the table and provide new one, having only the columns with specified names and the order of fields would not change.

This is definitely not the case. Current behavior is:
- order of field names in records is changed according to order of names in `names` argument
- however, the order of field values in records remains the same as before
- and target.schema remains unchanged in regards to order of field names

## test_field_filter.py
```python
from frictionless import Resource, transform, steps


def test_field_filter():
    rec1 = {"first": "v111", "second": "v222"}

    header = list(rec1.keys())
    assert header == ["first", "second"]
    row1_vals = list(rec1.values())
    assert row1_vals == ["v111", "v222"]

    data = [header, row1_vals]

    resource = Resource(data)
    resource.infer()
    assert resource.labels == header

    assert dict(resource.read_rows()[0]) == rec1
    assert resource.validate()["valid"]
    new_header = ["second", "first"]
    target = transform(
        resource,
        steps=[
            steps.field_filter(names=new_header),
            # steps.table_normalize(),
        ],
    )
    target_row1 = target.read_rows()[0]
    # execting order of headers not modified
    assert target.labels == header
    # expecting records keeping it's values under original name
    assert dict(target_row1) == rec1
```
The test fails:
```
    def test_field_filter():
        rec1 = {"first": "v111", "second": "v222"}

        header = list(rec1.keys())
        assert header == ["first", "second"]
        row1_vals = list(rec1.values())
        assert row1_vals == ["v111", "v222"]

        data = [header, row1_vals]

        resource = Resource(data)
        resource.infer()
        assert resource.labels == header

        assert dict(resource.read_rows()[0]) == rec1
        assert resource.validate()["valid"]
        new_header = ["second", "first"]
        target = transform(
            resource,
            steps=[
                steps.field_filter(names=new_header),
                # steps.table_normalize(),
            ],
        )
        target_row1 = target.read_rows()[0]
        # expecting order of headers not modified
>       assert target.labels == header
E       AssertionError: assert ['second', 'first'] == ['first', 'second']
E         At index 0 diff: 'second' != 'first'
E         Use -v to get more diff
```
## Clarifying expected behavior

I came to two possible behaviors which make sense to me

### var1: pure field filter without changing their order
The `field_filter` shall:
- keep order of field names unchanged
- result shall contain only the names, which are passed by `names` argument
- `target.schema` shall change accordingly
- of course, all field values in all records shall remain bound to original field name

### var2: filter and reorder columns
There are situations where reordering columns (field names + their values) could come handy. Typical situation is when someone provides a table with all required columns but their order is mixed.

I guess this is not the behavior, everyone expects, so I would propose adding a new parameter `reorder` with default value `False`

The new signature would be `target.field_select(name list[str], reorder: bool = False)`

**Comment by vlcinsky** [comment]
Note1: Current **workaround** is to specify `name` with field names in the order as they appear in the data.

Note2: `steps.table_normalize()` does other unexpected things (changing order of headers again leaving values in wrong positions), but until expected behavior of `field_filter` is clarified, it is not worth to deal with that.

**Comment by shashigharti** [comment]
Thank you for reporting!. Looks like the fields value are also being swapped. 
{'first': 'v222', 'second': 'v111'}
We will look into this issue.

**Comment by vlcinsky** [comment]
The cause seems to be [in these  lines with for loop](https://github.com/frictionlessdata/frictionless-py/blob/3f4a71d45ae36292fe15e6364a3bd1700ec3cbd3/frictionless/steps/field/field_filter.py#L23-L25) where it removes the fileds from the schema but keeps original ones in original order:

```python
    def transform_resource(self, resource):
        table = resource.to_petl()
        names = self.get("names")
        for name in resource.schema.field_names:
            if name not in names:
                resource.schema.remove_field(name)
        resource.data = table.cut(*names)
```
