### ISSUE TITLE
Add a CLI ability to describe data in markdown 

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#1158]
# Overview

We want to export metadata like this:

```
$ frictionless describe table.csv --markdown
$ frictionless describe schema.json --markdown # also allow providing metadata to describe
```

From https://github.com/frictionlessdata/frictionless-py/issues/837#issuecomment-1173178536

**Comment by roll** [comment]
Implemented in v5 (will be released this month):

```
$ frictionless describe data/table.csv --markdown
```

And for already existent metadata I've created a feature request - https://github.com/frictionlessdata/frictionless-py/issues/1170

**Comment by dennisangemi** [comment]
Nice! Thank u so much
