### ISSUE TITLE
Have sensible defaults for `innerpath` in `Package` class

### ISSUE THREAD

**Issue by augusto-herrmann** [frictionlessdata/frictionless-py#1174]
# Overview

Current behaviour when instantiating the `Package` class with a zip file or url is to look for a file named `datapackage.json` inside. If none is found, it throws an exception.

## Example

```python
package = Package('http://repositorio.dados.gov.br/seges/consumo-energia/consumo-energia.zip')
```

this throws an exception because the zip file does not contain a `datapackage.json`, but a `datapackage.yaml`. Specifying an `innerpath` argument makes it work:

```python
package = Package('http://repositorio.dados.gov.br/seges/consumo-energia/consumo-energia.zip', innerpath='datapackage.yaml')
```

## Proposal

In order to make the Frictionless Framework more usable and simplify user's code it should have sensible defaults. It could look first for a `datapackage.json`, then look for a `datapackage.yaml` (maybe also `.yml`), and only if none is found raise an exception.

**Comment by kagawa0710** [comment]
@roll Hi! Can I try to extend this feature?

**Comment by roll** [comment]
@kagawa0710 
Hi, sure!

**Comment by kagawa0710** [comment]
@roll 
I sent a pull request!
