### ISSUE TITLE
Describe resource to provide bytes and hash

### ISSUE THREAD

**Issue by rgaiacs** [frictionlessdata/frictionless-py#1202]
Consider the following minimal CSV file:

```
foo,bar
1,1
2,2
```

In Python, I run

```
import frictionless
frictionless.describe('mwe.csv')
```

and the output is

```
{'encoding': 'utf-8',
 'format': 'csv',
 'hashing': 'md5',
 'name': 'mwe',
 'path': 'mwe.csv',
 'profile': 'tabular-data-resource',
 'schema': {'fields': [{'name': 'foo', 'type': 'integer'},
                       {'name': 'bar', 'type': 'integer'}]},
 'scheme': 'file'}
```

Will be create that `frictionless.describe` also include properties `bytes` and `hash`.

**Comment by roll** [comment]
Hi @rgaiacs,

You need to provide the stats argument:

```
# $ frictionless describe mwe.csv --stats
frictionless.describe('mwe.csv', stats=True)
```

Currently, it will add the stats dictionary to the metadata but from v5 (which is about to be released) you can do:

```
$ frictionless describe mwe.csv --stats --standards v1
```
To make it `bytes/hash` on the root
