### ISSUE TITLE
Add default values to CLI options help when applicable

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#1223]
# Overview

https://github.com/frictionlessdata/frictionless-py/issues/930#issuecomment-1207254960

**Comment by aivuk** [comment]
@roll for what I saw the `limit-rows` has no default at https://github.com/frictionlessdata/framework/blob/main/frictionless/program/common.py#L265 or https://github.com/frictionlessdata/framework/blob/main/frictionless/settings.py

But in general all CLI options with default values have them being displayed with the parameter on common.py, or am I mistaken?

**Comment by roll** [comment]
@aivuk 
It seems it's been already fixed in v5

![def](https://user-images.githubusercontent.com/557395/200254746-b8f833a3-5572-405b-b1b6-cf150dbe1cfd.png)

Let's close until we get another user request

**Comment by aborruso** [comment]
> It seems it's been already fixed in v5

wow, thank you very much!
