### ISSUE TITLE
Add iterrows method to Resource to avoid replacing the default __iter__ method

### ISSUE THREAD

**Issue by areleu** [frictionlessdata/frictionless-py#1227]
# Overview

I think this is critical, I was trying to use the package with my own json schema profile and I was always getting this weird error "unhashable type: Row". This is because the jsonschema library tries to iterate over the elements of the Resource. 

# Solution
I think the best solution is to add an iterrows method that goes through the rows in the resource. And replace every place where one would iterate over the Resource with this method. 

I also considered converting the resource into a dictionary at "frictionless/metadata.py" line 274 but I think replacing the __iter__ method is not a good idea at all, please prove me wrong if you had a good reason to do this.

**Comment by roll** [comment]
Thanks @areleu!

The `resource.__iter__` is removed in v5 which is about to be released for public beta testing. We can't do the same in v4 as it's a breaking change.

So currently in v4, one can use:

```
with Resource() as resource:
  resource.row_stream
```

and as you mentioned:

```
resource.to_dict()
```

for exporting a descriptor

**Comment by areleu** [comment]
Thanks a lot! I will be very happy to start testing v5 right away. I let you know if I find some issue.

**Comment by roll** [comment]
Great! We're going to put a first public version of v5 on PyPi this week
