### ISSUE TITLE
CSV validation: is it RFC 4180 compliant?

### ISSUE THREAD

**Issue by aborruso** [frictionlessdata/frictionless-py#1230]
Hi,
if I run

```
frictionless validate "https://gist.githubusercontent.com/aborruso/3b675b529da264be83c7e75e26d2ee26/raw/e18c3cbbb5217acc430c950c3f5ae622eb52e661/tmp.csv"
```

I have "valid" result.

But in RFC 4180 I have "Fields containing line breaks (CRLF), double quotes, and commas should be enclosed in double-quotes."

In the input I have the cell `LISTA CIVICA | "SAINT-OYEN - TRAVAILLI EUNSEMBLO"` and this is not a valid RFC 4180 cell.
It should be `"LISTA CIVICA | ""SAINT-OYEN - TRAVAILLI EUNSEMBLO"""`.

Then the question is: should frictionless validation be RFC 4180 compliant? If yes, this seems to me a bug.

Thank you

**Comment by roll** [comment]
Thanks @aborruso, we will investigate

**Comment by roll** [comment]
I think it's similar to the issue we discussed a few month ago, I guess in this case the software also can't figure out a data publisher intention regarding quotes and for software it's RFC4180 compliant but with a content non intended by an author. What I can't understand in this case is why validation doesn't fail with some dimension error like extra/missing-cell if the parser reads cells incorrectly. @shashigharti is analysing it atm

**Comment by shashigharti** [comment]
We use csv.reader underhood and the default value for CSV.reader dialect is:
quoting = QUOTE_MINIMAL
quote_char = "

So it parses the cell correctly even if there is "double quote" in the cell  which is not enclosed in "".

Here we use sniffer to predict the default dialect params.
https://github.com/frictionlessdata/framework/blob/main/frictionless/formats/csv/parser.py#L33

So I think it is parsing correctly even if the csv doesn't have the double quotes around the field text that has quote char in it.

**Comment by aborruso** [comment]
@shashigharti @roll then currently frictionless can mark as valid a CSV file that is not RFC 4180 compliant. Am I right?

It would be very useful to add a validate option - `--rfc4180` - to make frictionless able to run a full RFC 4180 check.

**Comment by shashigharti** [comment]
yes. And I tried using default config as well(python csv reader) but it doesn't complain even if RFC 4180 doesn't apply.
I think this thread is relevant where they discuss about RFC-strict dialect:
https://github.com/python/cpython/issues/70044 

Yes it would be useful, but not sure how we can add it if csv reader itself doesn't  raise error about it. Looking for the feedback.

WDYT @roll @aivuk?

**Comment by roll** [comment]
I don't think it's possible ATM -- we just "don't see" these quotes (missing or provided) as we operate with a byte stream before csv.parser and a cell stream after csv.parser

**Comment by roll** [comment]
BTW, RFC 4180 - https://www.ietf.org/rfc/rfc4180.txt

```
   5.  Each field may or may not be enclosed in double quotes (however
       some programs, such as Microsoft Excel, do not use double quotes
       at all).  If fields are not enclosed with double quotes, then
       double quotes may not appear inside the fields.  For example:

       "aaa","bbb","ccc" CRLF
       zzz,yyy,xxx

   6.  Fields containing line breaks (CRLF), double quotes, and commas
       should be enclosed in double-quotes.  For example:

       "aaa","b CRLF
       bb","ccc" CRLF
       zzz,yyy,xxx
```

> If fields are not enclosed with double quotes, then double quotes may not appear inside the fields
> Fields containing line breaks (CRLF), double quotes, and commas should be enclosed in double-quotes

TBH I don't see any MUST requirements here. Usually SHOULD (and of course MAY) are not considered as obligatory 

Also, Frictionless' comment on this RFC - https://specs.frictionlessdata.io/tabular-data-resource/#csv-file-requirements (for example, the file we're discussing is not RFC 4180 valid anyway as it's not comma separated)

**Comment by aborruso** [comment]
Hi @roll and as usual, thank you for your time.

> TBH I don't see any MUST requirements here. Usually SHOULD (and of course MAY) are not considered as obligatory

In the CSV RFC you have a lot of "should", because is a RFC and not a final definition of the standard.

Just to give an example of another "should" for a very important element: "*Each line should contain the same number of fields throughout the file.*"

> Also, Frictionless' comment on this RFC - https://specs.frictionlessdata.io/tabular-data-resource/#csv-file-requirements (for example, the file we're discussing is not RFC 4180 valid anyway as it's not comma separated)

In this comment I read "CSV files `MUST` follow RFC 4180 with the following important exceptions allowed". What about to add the exception about double quotes inside cells? 

Once again, thank you

**Comment by shashigharti** [comment]
Hi @aborruso, thanks again.

I agree with you that it would be nice to have a feature that could check quotes inside cell, but it may not be possible atm and we need to wait until it's resolved in python parser. Because built in python parser library which we use, does not raise any error but tries to adhere to RFC 4180 standard by adding quotes silently while parsing.

For example:
``` 
# CSV File
# Name;Address;Country
# Liam;Quebec;Canada
# Charlotte;Denver "International";USA
# Amelia;Platz des;Berlin
# Elijah;"Platz ""des""";Germany
```
## usecase 1 - with inferred dialect
```python
with open('test-csv-1.csv', newline='') as csvfile:
    dialect = csv.Sniffer().sniff(csvfile.read(1024))
print("Dialect", dialect.__dict__, "\n")

print("+++ Data +++")
# delimiter = ';' quotechar='"'
with open('/home/shashi/Desktop/data-encoding/test-csv-1.csv') as csvfile:
    reader = csv.reader(csvfile, dialect = dialect)
    for index,row in enumerate(reader):
        print(' -- '.join(row))
```
```
Dialect {'__module__': 'csv', '_name': 'sniffed', 'lineterminator': '\r\n', 'quoting': 0, '__doc__': None, 'doublequote': True, 'delimiter': ';', 'quotechar': '"', 'skipinitialspace': False} 

+++ Data +++
Name -- Address -- Country
Liam -- Quebec -- Canada
Charlotte -- Denver "International" -- USA
Amelia -- Platz des -- Berlin
Elijah -- Platz "des" -- Germany
```
Row 2 is not enclosed in quotes and row 4 is, but both row 2 and row 4 are read correctly.

## usecase 2 - default
```python
print("+++ Data +++")
# delimiter = ',' quotechar='"'
with open('/home/shashi/Desktop/data-encoding/test-csv-1.csv') as csvfile:
    reader = csv.reader(csvfile)
    for index,row in enumerate(reader):
        print(' -- '.join(row))
```
```
+++ Data +++
Name;Address;Country
Liam;Quebec;Canada
Charlotte;Denver "International";USA
Amelia;Platz des;Berlin
Elijah;"Platz ""des""";Germany
```

In usecase 2, where we use default values with delimiter = "," it reads without any error. But it reads row 2 and row 4 differently but no error.

**Comment by aivuk** [comment]
I agree with what @shashigharti  said above, better to wait to see if a strict mode is implemented in the standard csv library or look for another library.

There is the library https://github.com/alan-turing-institute/CleverCSV that is a drop in substitute to the standard csv library and it can convert a csv to a RFC 4180 compliant one, but it also don't raise an exception when a row is not compliant to the RFC. The library says that it can detect the dialect better with messy csv files:

> With our method we achieve 97% accuracy for dialect detection, with a 21% improvement on non-standard (messy) CSV files compared to the Python standard library.

The only way that I can see to detect that the csv is no compliant to the RFC 4180 would be to change the standard csv library or the clevercsv (in that case it would need to be done in the C parser https://github.com/alan-turing-institute/CleverCSV/blob/master/src/cparser.c). Other idea would be to just convert the csv to a standard compliant one using clevercsv and comparing the different csv files, but this would not be recommended for big csv files.

**Comment by aborruso** [comment]
Ok, I close it. Consider for yourself whether to include this validation exception in the documentation.

And thank you very much
