### ISSUE TITLE
Adding a field inferencing "subrule", otherwise very often I would have wrong extracted values

### ISSUE THREAD

**Issue by aborruso** [frictionlessdata/frictionless-py#1232]
Hi,
daily I work with data where some columns have only numerical values in the cells, but which are actually string fields.

A typical case is that of administrative codes, of regions, provinces and cities (in the table below `codice_regione`, `codice_provincia` and `codice_comune` fields). In Italy, the city of Losine has the code `0870`, and obviously it's a string, and it must remain a string, otherwise I would lose the chance to JOIN this data with other data.

| comune | codice_regione | codice_provincia | codice_comune | denominazione_comune | sigla_provincia | data_entrata_in_carica |
| --- | --- | --- | --- | --- | --- | --- |
| 030151360 | 03 | 015 | 1360 | POLPENAZZE DEL GARDA | BS | 13/10/2021 |
| 030120530 | 03 | 012 | 0530 | CAROBBIO DEGLI ANGELI | BG | 04/10/2021 |
| 020040580 | 02 | 004 | 0580 | SAINT-DENIS | AO | 23/09/2020 |
| 030150870 | 03 | 015 | 0870 | LOSINE | BS | 04/10/2021 |
| 190480090 | 19 | 048 | 0090 | CAPO D'ORLANDO | ME | 27/10/2021 |

But if I run `extract` on it

```
frictionless extract "https://gist.githubusercontent.com/aborruso/076e5fad847b658a535b16cbcf3abdfd/raw/887edc88ab75b01d15ea1ac4bb052ffaf8d5ef9c/tmp.csv" --csv
```

the `codice_regione`, `codice_provincia` and `codice_comune` fields are no longer strings, they are all numbers and the cell values have changed (in example the code of Losine becomes `870`).

| comune | codice_regione | codice_provincia | codice_comune | denominazione_comune | sigla_provincia | data_entrata_in_carica |
| --- | --- | --- | --- | --- | --- | --- |
| 30151360 | 3 | 15 | 1360 | POLPENAZZE DEL GARDA | BS | 13/10/2021 |
| 30120530 | 3 | 12 | 530 | CAROBBIO DEGLI ANGELI | BG | 04/10/2021 |
| 20040580 | 2 | 4 | 580 | SAINT-DENIS | AO | 23/09/2020 |
| 30150870 | 3 | 15 | 870 | LOSINE | BS | 04/10/2021 |
| 190480090 | 19 | 48 | 90 | CAPO D'ORLANDO | ME | 27/10/2021 |

I know, octal numbers exist, but in 99% of cases (I'm talking about my experience), if I have fields with cells starting with zero they are not octal numbers, but string codes.

If it were possible I would add a subrule for all fields mapped as numbers: if there are cells that start with a zero,  not followed by a `,` or `.`, set that inferenced field as `string` and not as `number`.

Thank you.

**Comment by roll** [comment]
Thanks @aborruso, we will discuss it but I think it makes sense

**Comment by roll** [comment]
@shashigharti 
I think we need to return None if it starts from '0' here:
- https://github.com/frictionlessdata/frictionless-py/blob/main/frictionless/fields/integer.py#L36
- https://github.com/frictionlessdata/frictionless-py/blob/main/frictionless/fields/number.py#L66

I guess it's the right solution as leading zeros might be really confusing e.g. Python doesn't allow them:
```
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
```

**Comment by roll** [comment]
Another question if `integer/number.bareNumber` is set to False we might need to allow leading zeros to make possible to have a numeric column like this

**Comment by aborruso** [comment]
Wow @roll thank you.

I am very happy to have contributed in terms of ideas.

How to install the current 5 dev version?

**Comment by roll** [comment]
Hi @aborruso,

It requires `--pre` modifier - https://framework.frictionlessdata.io/docs/getting-started.html#installation

**Comment by aborruso** [comment]
Hi @roll ,
it seems that we have this problem still in 5 release.

If I run

```
frictionless validate --buffer-size 25000000 "https://gist.githubusercontent.com/aborruso/c99d74e88d0f8037219c958a40fe744c/raw/6d8b602f5692306bbc16ee6b05210363be911c63/tmp.csv"
```

I have wrong type error. The second columns contains a lot of `01` values (and so on), it's a string column, but it's mapped as integer.

I'm using 5.0.0b10.

Thank you

**Comment by roll** [comment]
Unfortunately, we had to revert this change in `frictionless@5.2.3` as it contradicts the Table Schema standard (see #1364):

> lexical representation consisting of a finite-length sequence of decimal digits (#x30-#x39) separated by a period as a decimal indicator. An optional leading sign is allowed. If the sign is omitted, "+" is assumed. **Leading and trailing zeroes are optional**. If the fractional part is zero, the period and following zero(es) can be omitted. For example: -1.23, 12678967.543233, +100000.00, 210.

And it seems to be impossible to keep this particular case aligned with the standard.

**Comment by aborruso** [comment]
Hi @roll there is something I do not understand.

In #1364 the 15 field in the schema is mapped as integer, but in the values we have `02000000317`, then it's not an integer.

Why was it mapped as integer?

**Comment by aborruso** [comment]
> **Leading and trailing zeroes are optional**.

@roll  isn't ours a different case?
In the standard I think that the leading is for `0.326565`, not for `0326565`, there must be a comma.

**Comment by aborruso** [comment]
@roll moreover, if you open the [web page](https://opendata.schleswig-holstein.de/dataset/65f105e1-f7c0-48a1-9697-d77cef43d25c?resource_id=8cd69e13-eeec-45cd-9b5e-0e3d69532679) of that data, you have that the `BST_Nr` field is an identification field, a code.
So for me the scheme is badly defined and frictionless was helpful in finding out.

What do you think about it?

![image](https://user-images.githubusercontent.com/30607/212049812-eb51f836-ca32-4b0d-a52b-06aeaf2c2ed1.png)

**Comment by roll** [comment]
Hi @aborruso,

Yea it might be an error in the metadata but the more general problem is that by the standard we can't forbid leading zeroes as it's explicitly allowed - https://www.w3.org/TR/xmlschema-2/#decimal (this is referenced in Table Schema standard)

I'm NOT against of detecting CODES but I think we just need to find another way to doing so e.g. having a special logic in `detector.detect_schema` (cc @shashigharti maybe creating a new feature request?)

**Comment by aborruso** [comment]
> Yea it might be an error in the metadata but the more general problem is that by the standard we can't forbid leading zeroes as it's explicitly allowed - https://www.w3.org/TR/xmlschema-2/#decimal (this is referenced in Table Schema standard)

@roll I'm trying to investigate but there is something strange. In my opinion it refers to the fact that you can have "0.3265" or ".3265", but not that you can represent "0.3265" as "03265", or "3265" as "03265".

So, for me the standard would be respected

**Comment by aborruso** [comment]
> Yea it might be an error in the metadata but the more general problem is that by the standard we can't forbid leading zeroes as it's explicitly allowed - https://www.w3.org/TR/xmlschema-2/#decimal (this is referenced in Table Schema standard)

@roll I'm trying to investigate but there is something strange. In my opinion it refers to the fact that you can have "0.3265" or ".3265", but not that you can represent "0.3265" as "03265", or "3265" as "03265".

So, for me the rule would be respected

**Comment by roll** [comment]
Yea it's quite weird although it seems still to be allowed for integer type: 
- https://stackoverflow.com/questions/26642421/why-does-the-w3c-xml-schema-specification-allow-integers-to-have-leading-zeros
- https://stackoverflow.com/questions/8134505/xml-integer-element-with-leading-zeros

**Comment by aborruso** [comment]
@roll in that document [1] you have

> Leading and trailing zeroes are prohibited subject to the following: there must be at least one digit to the right and to the left of the decimal point which may be a zero


Than you must have a point.


[1] https://www.w3.org/TR/xmlschema-2/#decimal

**Comment by roll** [comment]
@aborruso 
Thanks I think they have two levels based on this section:
- lexical representation (allowing leading zeroes)
- canonical representation aka normalized (forbidding leading zeroes)

So it still seems to be allowed. In general, I think it's anyway two different questions:
- [VALIDATION] if a data publisher declared a value like this `0123145` as an integer, shall we mark it invalid? I think NO based on the text of Table Schema (and XML reference)
- [INFERRING] if a value like `01234523` is a part of the data sample shall we mark the field `string` or `integer`? We can decide here without touching the validation part as the inferring is fully software-relative and not standartazed

**Comment by aborruso** [comment]
> * [INFERRING] if a value like `01234523` is a part of the data sample shall we mark the field `string` or `integer`? We can decide here without touching the validation part as the inferring is fully software-relative and not standardized

@roll I think we should have no doubts about this: `string`. 

Thank you

**Comment by roll** [comment]
Thansk @aborruso, I've created an issue - https://github.com/frictionlessdata/framework/issues/1380
