### ISSUE TITLE
Plugins Reference Missing

### ISSUE THREAD

**Issue by davidlday** [frictionlessdata/frictionless-py#1256]
# Overview

In the documentation, the "Getting Started" page refers to the [list of Frictionless Framework plugins and their status](https://framework.frictionlessdata.io/docs/references/plugins-reference). However, that page doesn't appear to exist any more. Where can I find a current list of plugins and their status?

Thank you!

**Comment by shashigharti** [comment]
Hi @davidlday 

You can find it here for now: https://v4.framework.frictionlessdata.io/docs/references/plugins-reference . We will fix the broken link.
