### ISSUE TITLE
`frictionless validate` points to deprecated function `validate_resource` in 4.40.0

### ISSUE THREAD

**Issue by peterdesmet** [frictionlessdata/frictionless-py#1262]
Frictionless version 4.40.0, when using CLI `frictionless validate datapackage.json` I get:

```
....../python3.7/site-packages/frictionless/actions/validate.py:215: UserWarning: Function "validate_resource" is deprecated (use "resource.validate").
  warnings.warn(message, UserWarning)

# -----
# valid: data.csv 
# -----
```

Why does the CLI `validate` function point to a deprecated function? How to circumvent this?

Example package I used: [test-dp.zip](https://github.com/frictionlessdata/framework/files/9682552/test-dp.zip)

**Comment by roll** [comment]
Hi @peterdesmet, can you please update to `v4.40.8` - it was a bug fixed in `v4.40.1`
