### ISSUE TITLE
using frictionless.describe with datetime containing NaT gives "ValueError: NaTType does not support time"

### ISSUE THREAD

**Issue by enningb** [frictionlessdata/frictionless-py#1263]
We're using frictionless v5 (b9) on a Mac with Python 3.

We use a parquet file containing a date-column with missings (they show as `NaT`). When we do:

`describe('data.parq')`

we get an error, stating:

    "ValueError: NaTType does not support time"

Is this something because frictionless does not recognize `NaT` as a missing-value?

**Comment by shashigharti** [comment]
Thanks @enningb for reporting!. Can you please share the data file that you are using? 

I used parquet file with date column which has 'NaT' values but couldn't replicate the error. 

`describe('https://github.com/fdtester/temp-files/blob/main/myfile.parquet?raw=true')`

**Comment by enningb** [comment]
Thanks @shashigharti  for your reply! I can describe your example file as well, without any errors. While preparing my example-file I discovered that by changing my extension from '.parq' to '.parquet' I could describe my dataset as well. So the problem is in the use of the extension. I confirmed this by using your file with a changed extension. 

I guess this will be solved with https://github.com/frictionlessdata/framework/pull/1266

**Comment by shashigharti** [comment]
> Thanks @shashigharti for your reply! I can describe your example file as well, without any errors. While preparing my example-file I discovered that by changing my extension from '.parq' to '.parquet' I could describe my dataset as well. So the problem is in the use of the extension. I confirmed this by using your file with a changed extension.

Nice! thanks. 

> I guess this will be solved with #1266

Yes the extension issue is solved here.
