### ISSUE TITLE
Validating against a schema

### ISSUE THREAD

**Issue by kgeographer** [frictionlessdata/frictionless-py#1268]
#### question/clarification
I have been using frictionless 3.31.0 for some time to validate uploaded delimited data files and it works fine. Exploring the v4 and v5 docs, I am confused. Previously I defined a json schema with various constraints on fields (including regex), then ran a command that essentially says "validate this file against this schema." Then I parse the resulting report. Very straightforward. I have reread the new docs over and over, but the examples don't indicate how I would achieve the same effect. Am I to make a package? I understand there are built-in checks (useful), but I will have several custom ones.

Can you give me any tips on how to proceed?

The relevant 3.x code looks like this:
```
from frictionless import validate
file = 'path/to/myfile.csv'
my_schema = json.loads(codecs.open('path/to/schema.json','r','utf8').read())'
try:
  report = validate(file, schema=my_schema, sync_schema=True)
except:
  err = sys.exc_info()
  print('error on validate',err)    
  print('error args', err[1].args)  
```

**Comment by roll** [comment]
Hi @kgeographer!

With `frictionless@5` this snippet will look as:

```python
from frictionless import Resource, Detector

resource = Resource('path/to/file.csv', schema='path/to/schema.json', detector=Detector(sync_schema=True))
report = resource.validate()
print(report.valid)
```

Please let me know if you need more help (I'll re-open the issue)

**Comment by roll** [comment]
We have a validation guide here - https://framework.frictionlessdata.io/docs/guides/validating-data.html - it includes both CLI and Python examples

**Comment by kgeographer** [comment]
Thanks! That looks like what I'm after, will test it out soon. FWIW, in the guide I could find no similar pattern, e.g. schema and detector as arguments in Resource creation. I'd have never put this together, so big thanks! Maybe a full-blown example alongside the minimal one near the top?

**Comment by roll** [comment]
@kgeographer 
More in-depth resource docs (including full API reference) you can find here (also a link to a detector docs): 
- https://framework.frictionlessdata.io/docs/framework/resource.html (it seems it misses the detector argument in the high-level docs)
- https://framework.frictionlessdata.io/docs/framework/detector.html
