### ISSUE TITLE
validation: use of path and basepath

### ISSUE THREAD

**Issue by aborruso** [frictionlessdata/frictionless-py#1273]
Hi,
I would like to validate a CSV using the way suggested from @roll [here](https://github.com/frictionlessdata/framework/issues/834#issuecomment-831754967) , simply running:

```
frictionless validate ../myrelativepath/myfile.yml --path ./mydatarelativepath/myfile.csv
```

I'm using 4.40.8 version and I have the below not found error.

If I use `--basepath`

```
frictionless validate ./risorse/province.yml --basepath ./rawdata --path provincia_di_padova.csv
```

I have no error.

Can't I just use `--path`? Do I always have to use the pair `--path` and `--basepath`?

Than you

## Not found error

![image](https://user-images.githubusercontent.com/30607/197327729-0a7df403-a55e-4764-a526-7f8b3e0a492f.png)

**Comment by shashigharti** [comment]
Hi @aborruso thanks for reporting!

Can you please try using `--trusted` param:

`frictionless extract 1274/resource.yaml  --path ../1229/countries.csv --trusted`

**Comment by aborruso** [comment]
hi @shashigharti 
I'm using `validate` not `etract`, and in validate help I do no have `--trusted`.

I'll do your test anyway

Thank you

**Comment by aborruso** [comment]
hi @shashigharti ,
applying your example to my real case I have

```
[scheme-error] The data source could not be successfully loaded: [Errno 2] No such file or directory: '../../dati/amministazioni-italiane/risorse/../../dati/amministazioni-italiane/rawdata/provincia_di_palermo.csv'
```

But if I run

```
frictionless validate ../../dati/amministazioni-italiane/risorse/province.yml --basepath ../../dati/amministazioni-italiane/rawdata/ --path provincia_di_palermo.csv
```

I have

```
# -----
# valid: provincia_di_palermo.csv
# -----

## Summary

+------------------------+--------------------------+
| Description            | Size/Name/Count          |
+========================+==========================+
| File name              | provincia_di_palermo.csv |
+------------------------+--------------------------+
| File size (KB)         | 297652                   |
+------------------------+--------------------------+
| Total Time Taken (sec) | 0.23                     |
+------------------------+--------------------------+
```

**Comment by shashigharti** [comment]
hi @aborruso  

sorry yes the validate does not support --trusted in version  4.40.8 

But it has been fixed in v5. And this should work in v5
`frictionless validate ../../dati/amministazioni-italiane/risorse/province.yml --path ../../dati/amministazioni-italiane/rawdata/provincia_di_palermo.csv --trusted`

Thanks

**Comment by aborruso** [comment]
Ok, it works in 5.

Thank you
