### ISSUE TITLE
header and extract: "--valid" and "--invalid" flags

### ISSUE THREAD

**Issue by aborruso** [frictionlessdata/frictionless-py#1274]
Hi,
I'm using 4.40.8 version.

If I run 

```
frictionless extract --csv --valid ./file.yml --basepath ./rawdata --path file.csv
```

I have the CSV header in the output, but If use `--invalid` flags I have no header. I think there should be either way.

Could you add it, or add the option to have it also for invalid output?

Thank you

**Comment by shashigharti** [comment]
Hi @aborruso 

Thank you for reporting!. It is fixed in v5.



![Image](https://user-images.githubusercontent.com/5582809/198516639-0c6ae2ff-6000-4380-b365-cbd191247948.png)

**Comment by aborruso** [comment]
Thank you. I will wait for the next release ;)

**Comment by shashigharti** [comment]
Closing the issue as it is fixed in v5
