### ISSUE TITLE
Zenodo metadata transfer

### ISSUE THREAD

**Issue by peterdesmet** [frictionlessdata/frictionless-py#1277]
With the new Zenodo integration, it is now possible to write a Frictionless Data Package to Zenodo 🎉 . It would be great however, if all relevant (and DataCite compatible) metadata in a `datapackage.json` where pushed (by default) as metadata to that deposit, so the user doesn't have to repeat this information (e.g. `contributors`, `title`, `description`, `license` etc.)

Such functionality would probably best rely on a generic function that can convert Data Package properties to DataCite properties.

For inspiration, in Camtrap DP (an extended Data Package) I have listed the metadata terms as they are typically entered in Zenodo. I've also adopted `relatedIdentifiers` directly from DataCite: https://tdwg.github.io/camtrap-dp/metadata/

**Comment by shashigharti** [comment]
Thanks for the request!
