### ISSUE TITLE
String code inferred as an integer

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#1285]
Hi @roll ,
it seems that we have this problem still in 5 release.

If I run

```
frictionless validate --buffer-size 25000000 "https://gist.githubusercontent.com/aborruso/c99d74e88d0f8037219c958a40fe744c/raw/6d8b602f5692306bbc16ee6b05210363be911c63/tmp.csv"
```

I have wrong type error. The second columns contains a lot of `01` values (and so on), it's a string column, but it's mapped as integer.

I'm using 5.0.0b10.

Thank you

_Originally posted by @aborruso in https://github.com/frictionlessdata/framework/issues/1232#issuecomment-1298175924_

**Comment by shashigharti** [comment]
Hi @aborruso,

You can try increasing sample_size to 200 and the type will be inferred correctly. The default sample size is 100 and the first 100 are similar to integer value, so it is inferred as "integer". This works:

```
frictionless validate --buffer-size 25000000 "https://gist.githubusercontent.com/aborruso/c99d74e88d0f8037219c958a40fe744c/raw/6d8b602f5692306bbc16ee6b05210363be911c63/tmp.csv" --sample-size 200

# -----
# valid: https://gist.githubusercontent.com/aborruso/c99d74e88d0f8037219c958a40fe744c/raw/6d8b602f5692306bbc16ee6b05210363be911c63/tmp.csv 
# -----

## Summary 

+--------------+-----------------------------------------------------------------------------------------------------------------------------------+
| Name         | Value                                                                                                                             |
+==============+===================================================================================================================================+
| File Place   | https://gist.githubusercontent.com/aborruso/c99d74e88d0f8037219c958a40fe744c/raw/6d8b602f5692306bbc16ee6b05210363be911c63/tmp.csv |
+--------------+-----------------------------------------------------------------------------------------------------------------------------------+
| File Size    | 424.9 kB                                                                                                                          |
+--------------+-----------------------------------------------------------------------------------------------------------------------------------+
| Total Time   | 1.34 Seconds                                                                                                                      |
+--------------+-----------------------------------------------------------------------------------------------------------------------------------+
| Rows Checked | 32682                                                                                                                             |
+--------------+-----------------------------------------------------------------------------------------------------------------------------------+
```

**Comment by aborruso** [comment]
> You can try increasing sample_size to 200 and the type will be inferred correctly. The default sample size is 100 and the first 100 are similar to integer value, so it is inferred as "integer". This works:

It works, ant it was my error, because I used `--buffer-size` and not `--sample-size`. I used `--buffer-size` because in [this](https://github.com/frictionlessdata/framework/issues/824#issuecomment-828393635) @roll message, he used it for right encoding inferencing.

So, if I understand correctly, both contribute to a good inferencing, but on different aspects. Is there a part of documentation talking about these aspects?

Thank you

**Comment by shashigharti** [comment]
yes, both contribute to good inferencing but in different context!. In [this](https://github.com/frictionlessdata/framework/issues/824#issuecomment-828393635) case that you have shared, it was related to inferring file encoding so we had to increase `--buffer-size` as chardet uses "bigger byte sample" as mentioned by @roll 

But in this case, we are trying to infer field type, so only increasing `--sample-size` will do:

`frictionless validate "https://gist.githubusercontent.com/aborruso/c99d74e88d0f8037219c958a40fe744c/raw/6d8b602f5692306bbc16ee6b05210363be911c63/tmp.csv" --sample-size 200`

It is only briefly specified in the [documentation](https://framework.frictionlessdata.io/docs/framework/detector.html#sample-size) . We will update it.

Thank you!

**Comment by roll** [comment]
So these values have literal meaning:
- buffer size: how many bytes to read for encoding infering
- sample size: how many rows to read for dialect/schema infering
