### ISSUE TITLE
Validate() does not check required anyOf properties of profile-defined fields

### ISSUE THREAD

**Issue by MaxLiebetreu** [frictionlessdata/frictionless-py#1290]
**Disclaimer:** I am just starting out with Frictionless, so maybe I'm misunderstanding something.

When a Package is defined, we may specify a profile, like "tabular-data-package" ([tabular-data-package.json](https://specs.frictionlessdata.io/schemas/tabular-data-package.json)). Frictionless should then make sure that the restrictions for tabular-data-package are adhered to. 

**This does not seem to be the case for anyOf required properties** - we can specify a key "licenses" and assign to it an array of objects. According to tabular-data-package, entries in "licenses" need to provide either a "name" or a "path". However, validate seems to only check whether the entries to "licenses" are objects, and does not perform any further checks. I suspect this to be a bug or an oversight related to the nesting of "anyOf" and "required"?
For types which specify required properties directly and not as part of the anyOf logic, this seems to work fine - as checked with "contributors".

**Code to reproduce:**
```
import frictionless
import os

def CheckReport(report: dict):
    if (report["errors"]):
        print(f"\nERRORS found in metadata:\n", report["errors"])
    else:
        print(f"\n NO errors found in metadata.\n")

package = frictionless.Package(
    profile="tabular-data-package",
    resources=[frictionless.describe(path=os.path.join("resources", "simple_sample_data.csv"), profile="tabular-data-resource")],
    licenses=[{"sf": 3}],
)
CheckReport(package.validate())

package["licenses"] = "some license"
CheckReport(package.validate())

package["licenses"] = [3, {}]
CheckReport(package.validate())

package["licenses"] = [{}]
package["contributors"]=[{"name": "some name"}]
CheckReport(package.validate())

package["contributors"]=[{"title": "some title", "name": "some name"}]
CheckReport(package.validate())
```

> NO errors found in metadata.
> 
> 
> ERRORS found in metadata:
>  [{'code': 'package-error',
>  'description': 'A validation cannot be processed.',
>  'message': 'The data package has an error: "\'some license\' is not of type '
>             '\'array\'" at "licenses" in metadata and at '
>             '"properties/licenses/type" in profile',
>  'name': 'Package Error',
>  'note': '"\'some license\' is not of type \'array\'" at "licenses" in '
>          'metadata and at "properties/licenses/type" in profile',
>  'tags': []}]
> 
> ERRORS found in metadata:
>  [{'code': 'package-error',
>  'description': 'A validation cannot be processed.',
>  'message': 'The data package has an error: "3 is not of type \'object\'" at '
>             '"licenses/0" in metadata and at "properties/licenses/items/type" '
>             'in profile',
>  'name': 'Package Error',
>  'note': '"3 is not of type \'object\'" at "licenses/0" in metadata and at '
>          '"properties/licenses/items/type" in profile',
>  'tags': []}]
> 
> ERRORS found in metadata:
>  [{'code': 'package-error',
>  'description': 'A validation cannot be processed.',
>  'message': 'The data package has an error: "\'title\' is a required property" '
>             'at "contributors/0" in metadata and at '
>             '"properties/contributors/items/required" in profile',
>  'name': 'Package Error',
>  'note': '"\'title\' is a required property" at "contributors/0" in metadata '
>          'and at "properties/contributors/items/required" in profile',
>  'tags': []}]
> 
> NO errors found in metadata.

**Comment by shashigharti** [comment]
Thanks @MaxLiebetreu  we will investigate!.
