### ISSUE TITLE
Add --sheet parameter to describe command for XLSX

### ISSUE THREAD

**Issue by vviers** [frictionlessdata/frictionless-py#1291]
# Overview

Hey there 👋🏼 thanks for the great package !

One small improvement to my quality of life as a developper would be to have the option to easily point to a specific sheet within xls/ods files when using the `frictionless describe` command.

I know `frictionless describe --dialect '{"excel": {"sheet": "my sheet"}}' Tables.xlsx` works, but since the _extract_ and _validate_ commands have the handy `--sheet` parameter, I figured the same could be added to the _describe_ command as well ?

Happy to implement this and make a PR if you think that's useful !

**Comment by shashigharti** [comment]
Thanks! @vviers, we will add.
