### ISSUE TITLE
Update standalone resource metadata with `steps.resource_update()`

### ISSUE THREAD

**Issue by fjuniorr** [frictionlessdata/frictionless-py#1351]
# Overview

I'm not sure if this is a bug or a feature request. Should I be able to update a standalone resource metadata in the [same way](https://github.com/frictionlessdata/framework/blob/a377e71862097c55b04d4776a00550eb2445b570/tests/steps/resource/test_resource_update.py) that is possible to update package metadata? 

Here is a [reproducible example](https://github.com/fjuniorr/datapackage-reprex/tree/transform-txt):

```python
from frictionless import Resource, Pipeline, steps

url = 'https://raw.githubusercontent.com/fjuniorr/datapackage-reprex/transform-txt/resource.json'
resource = Resource(url)

pipeline = Pipeline(
    steps=[
        steps.resource_update(name="indicadores_planejamento", descriptor={"title": "New title"}),
    ],
)

target = resource.transform(pipeline)
target.title # no title
```

**Comment by shashigharti** [comment]
Thanks @fjuniorr for reporting!.

**Comment by roll** [comment]
Hi @fjuniorr,

I'm releasing `frictionless@5.3` supporing this
