### ISSUE TITLE
Update existing dataset on CKAN using `frictionless.portals.CkanControl`

### ISSUE THREAD

**Issue by fjuniorr** [frictionlessdata/frictionless-py#1352]
I wan't to update an existing package published to CKAN but I'm getting an error that the URL is already in use. 

It looks like `CkanControl` is not recognizing the `allow_update` flag:

```python
from frictionless.portals import CkanControl
from frictionless import Package

url = 'https://raw.githubusercontent.com/transparencia-mg/datapackage-reprex/root-datapackage/datapackage.json'
package = Package(url)
config = CkanControl(baseurl='https://homologa.cge.mg.gov.br', 
                                      apikey='ec5c0860-9e48-41f3-8850-4a7128b18df8', # not a real key
                                      allow_update = True) 

package.publish(control=config)
# frictionless.exception.FrictionlessException: [error] CKAN API 
# error:FrictionlessException('[error] 
# {"help": "https://homologa.cge.mg.gov.br/api/3/action/help_show?name=package_create", 
# "error": {"name": ["Essa URL j\\u00e1 est\\u00e1 em uso."], "__type": "Validation Error"}, "success": false} ') 

config
# Traceback (most recent call last):
#   jsonschema/validators.py", line 318, in is_type
#     return self.TYPE_CHECKER.is_type(instance, type)
#   File "jsonschema/_types.py", line 119, in is_type
#     raise UndefinedTypeCheck(type) from None
# jsonschema.exceptions.UndefinedTypeCheck: Type 'bool' is unknown to this type checker
```

**Comment by shashigharti** [comment]
Thanks @fjuniorr for reporting. We will look into it.

**Comment by aivuk** [comment]
@fjuniorr the problem happens because to update an already existing dataset in CKAN, the datapackage must have an 'id' property. The CKAN portal uses this id to ask CKAN to update the specified dataset by the id. If there is no id in the datapackage, it tries to create a new dataset using the 'name' property, but this clashes with the already existing dataset with the same name. I don't see a quick way to update without specifying the id. Maybe a parameter to control as dataset_id?

**Comment by fjuniorr** [comment]
@aivuk it's common in the Open Data Portal of Minas Gerais that the same [data package](https://github.com/transparencia-mg/doacoes-comodatos-amigo-estado-mg) is published in different CKAN sites (eg. [staging](https://homologa.cge.mg.gov.br/dataset/doacoes-comodatos-amigo-estado-mg) and [production](https://dados.mg.gov.br/dataset/doacoes-comodatos-amigo-estado-mg) environments). With that use case in mind, it would be nice to not have to store (or retrieve during the update) the dataset id for different sites.

Any chance the `name` property of the data package be used instead of the id? I'm asking because the endpoint [package_update](https://docs.ckan.org/en/2.9/api/#ckan.logic.action.update.package_update) receives either "the name or id of the dataset to update".

**Comment by aivuk** [comment]
I think it would be a new feature and it would be necessary to pass a parameter to the control to explicitly request to update a dataset with a given ` name`, because o CKAN dataset can change its name, but the ID will remain the same. I will create an issue to track this feature.

**Comment by fjuniorr** [comment]
If the user already need to explicitly allow updates with `allow_update = True` don't you think that using `name` to update a dataset could at least be used as a fallback behaviour if the `id` property is not present?

I understand that the [spec has an id field](https://specs.frictionlessdata.io/data-package/#id) that match this use case, but from my side I'm still more surprised that `frictionless-py` would assume that a given `id` present in a data package is  valid in the context of a given CKAN site then that the data package `name` would be used for updates.

**Comment by roll** [comment]
I think it should be like this if the update is supported by the CKAN integration:

```python
from frictionless.portals import CkanControl
from frictionless import Package

url = 'https://raw.githubusercontent.com/transparencia-mg/datapackage-reprex/root-datapackage/datapackage.json'
package = Package(url)
config = CkanControl(baseurl='https://homologa.cge.mg.gov.br', 
                                      dataset='name' or package.name # user's responsibility
                                      apikey='ec5c0860-9e48-41f3-8850-4a7128b18df8', # not a real key
                                      allow_update = True) 

package.publish(control=config)
```

**Comment by roll** [comment]
BTW this error is not related to actual logic. It was just a typo in the JSON Schema definition for `portals.CkanControl` - https://github.com/frictionlessdata/framework/commit/0b6ef89aff9633fe23ecc1db902f906e2fe41440. I'm releasing `frictionless@5.5.1` with a fix

```python
config
# Traceback (most recent call last):
#   jsonschema/validators.py", line 318, in is_type
#     return self.TYPE_CHECKER.is_type(instance, type)
#   File "jsonschema/_types.py", line 119, in is_type
#     raise UndefinedTypeCheck(type) from None
# jsonschema.exceptions.UndefinedTypeCheck: Type 'bool' is unknown to this type checker
```
