### ISSUE TITLE
frictionless extract format-error

### ISSUE THREAD

**Issue by jze** [frictionlessdata/frictionless-py#1362]
The command
```
frictionless extract 'https://umweltanwendungen.schleswig-holstein.de/pegel/jsp/frictionless.jsp?mstnr=114069&thema=w'
```

produces the error
```
[format-error] The data source could not be successfully parsed: format "jsp" is not supported 
```

The data returned at the specified URL is a valid Tabular Data Resource. You can try it by downloading it first before calling `frictionless extract`:
```
curl -o table.json  'https://umweltanwendungen.schleswig-holstein.de/pegel/jsp/frictionless.jsp?mstnr=114069&thema=w'
frictionless extract table.json
```

**Version**
5.0.0b23

**Comment by roll** [comment]
Hi @jze, I'm releasing `frictionless@5.1` that supports the `descriptor` option:

```
frictionless extract --descriptor 'https://umweltanwendungen.schleswig-holstein.de/pegel/jsp/frictionless.jsp?mstnr=114069&thema=w'
```

Without providing the descriptor directly the framework basically can't figure out that the path is a resource json
