### ISSUE TITLE
Best way to pass custom http header to authenticate

### ISSUE THREAD

**Issue by vviers** [frictionlessdata/frictionless-py#1369]
Hey there 👋🏼 

I would like frictionless to be able to authenticate to a server via a `{"Authorization": f"Apikey {key}"}` header in order to read a remote resource.

I tried to play with the `RemoteControl` object but I does not have the `http_session` attribute anymore.

Before hacking away frictionless, I was wondering if you could point me to the easiest way to do this ?

Many thanks 🙏🏼

**Comment by roll** [comment]
Hi @vviers,

Since v5, it's been moved to a system context - https://framework.frictionlessdata.io/docs/advanced/system.html - as more appropriate way to handle auth/z (now it also handles metadata loading etc)

Please let me know if it helps
