### ISSUE TITLE
Migrating from v4 to v5 - how to skip blank rows

### ISSUE THREAD

**Issue by mcarans** [frictionlessdata/frictionless-py#1375]
I am attempting to migrate from v4 to v5.

From what I can tell, the following has changed:
frictionless.plugins.csv.CsvDialect -> frictionless.formats.CsvControl
frictionless.plugins.excel.ExcelDialect -> frictionless.formats.ExcelControl
frictionless.Layout -> frictionless.Dialect

Please confirm I have that right.

I have run into a problem with ignoring blank rows. In v4, it worked like this:
```
    if ignore_blank_rows:
        if layout.skip_rows is None:
            layout.skip_rows = ["<blank>"]
        elif "<blank>" not in layout.skip_rows:
            layout.skip_rows.append("<blank>")
```

There doesn't seem to be a `skip_rows` in the v5 Dialect class and the nearest equivalent I could find, `comment_rows`, does not take strings. How do I implement the above in v5?

**Comment by shashigharti** [comment]
Thanks @mcarans for reporting!

**Comment by roll** [comment]
Hi @mcarans,

It's correct the changes are aligning the framework with the coming Table Dialect Standard - https://github.com/frictionlessdata/specs/issues/697

**Comment by roll** [comment]
I'm releasing `frictionless@5.4` that supports `dialect.skip_blank_rows` - https://framework.frictionlessdata.io/docs/framework/dialect.html#skip-blank-rows
