### ISSUE TITLE
v5 reference docs: wrong documentation for class attributes

### ISSUE THREAD

**Issue by hjoukl** [frictionlessdata/frictionless-py#1378]
# Overview

v5 reference docs are buggy wrt to class attributes:

Reference docs for e.g. Resource https://framework.frictionlessdata.io/docs/framework/resource.html#reference-resource.name:

" Resource name according to the specs. It should be a slugified name of the resource.

Reference docs for e.g. Resource type https://framework.frictionlessdata.io/docs/framework/resource.html#reference-resource.type:

"Resource name according to the specs. It should be a slugified name of the resource. "

i.e. the same as name docs.

However: https://github.com/frictionlessdata/framework/blob/f3fea0a2277da6032988595523bd2a0b7438ccef/frictionless/resource/resource.py#L185-L188

The docs look ok for the class, its methods and (real) properties. The class attributes are documented using "non-standard" doc strings, immediately after the class attr definition (which won't be stored in `cls.__doc__` IIRC).

I suspect s.th. is amiss in your ref doc generation for those, somehow picking the first "class attr docstring" for all subsequent ones.

**Comment by roll** [comment]
Hi @hjoukl,

Thanks for reporting it's been fixed in Livemark in https://github.com/frictionlessdata/livemark/commit/5cee52ee6a04124c7a74672afe16097b6f604b12
