### ISSUE TITLE
Document and/or examples showing dialect.add_control

### ISSUE THREAD

**Issue by mcarans** [frictionlessdata/frictionless-py#1393]
@roll When running the code below, I would expect the header to be from the sheet "Trend", but it is 
from the first sheet "Cover". The sheet parameter of ExcelControl seems to be ignored. Unless I''m missing something, I think this is a bug.

```
from frictionless import Control, Detector, Dialect, Resource
from frictionless.formats import CsvControl, ExcelControl, JsonControl

url = "https://raw.githubusercontent.com/OCHA-DAP/hdx-python-utilities/main/tests/fixtures/downloader/test_xlsx_processing.xlsx"

control = ExcelControl()
control.sheet = "Trend"
control.fill_merged_cells = True

detector = Detector()
detector.field_type = "any"
detector.field_float_numbers = True
detector.field_missing_values = [""]

dialect = Dialect()
dialect.skip_blank_rows = True
dialect.header_rows = [7, 8]
dialect.header = True

resource = Resource(path=url, control=control, detector=detector, dialect=dialect)
resource.open()
print(resource.header)
```

**Comment by mcarans** [comment]
I see what I did wrong. The Control object must be added to the Dialect object not passed to the Resource ie.

```
    if control:
        dialect.add_control(control)
```
I think this should be documented eg. here: https://framework.frictionlessdata.io/docs/formats/excel.html. I had to look at the source code of frictionless to find out about this call.

**Comment by shashigharti** [comment]
Hi @mcarans , thanks for reporting!
If I understand you correctly, you can pass control in both Dialect and Resource. The only difference is in dialect you have option to pass multiple controls as a [list](https://github.com/frictionlessdata/framework/blob/main/frictionless/dialect/dialect.py#L75).

**Comment by mcarans** [comment]
@shashigharti As far as I can tell, it is not possible to pass control to Resource. I tried `control=control` with the Resource constructor and it didn't work. That is fine, but it should be made clear in the examples and docs that control must be passed to Dialect not Resource. 

Alternatively, the Resource constructor could be changed to accept a Control object (which was how I imagined it would work).

**Comment by shashigharti** [comment]
Thank you @mcarans!. 

I think If we pass both (dialect and control) then 'dialect' will be read and control param gets ignored [here](https://github.com/frictionlessdata/framework/blob/main/frictionless/resource/resource.py#L146). So due to that the param passed as  control doesn't have effect. 
I am going to tag @roll for his feedback. Thanks!

**Comment by roll** [comment]
@mcarans 
@shashigharti 
I'm releasing the fix that allow `Resource` to accept both `dialect/control`:

```python
    dialect = Dialect()
    control = formats.CsvControl()
    resource = Resource("data/table.csv", dialect=dialect, control=control)
    assert resource.dialect is dialect
    assert resource.dialect.controls[0] is control
```

**Comment by mcarans** [comment]
@roll i have tested after upgrading to 5.5.9 and my unit test fails. My original code that worked looks like this:
```
    kwargs["dialect"] = dialect
    if control:
        dialect.add_control(control)
    http_session = kwargs.pop("http_session", session)
    with system.use_context(http_session=http_session):
        if url:
            resource = Resource(path=url, **kwargs)
        else:
            resource = Resource(data=data, **kwargs)
        resource.open()
        return resource
```

I changed `dialect.add_control(control)` to `kwargs["control"] = control` and it failed. The test reads an Excel file `https://raw.githubusercontent.com/OCHA-DAP/hdx-python-utilities/main/tests/fixtures/downloader/test_xlsx_processing.xlsx?a=1` and looks at sheet "Trend" using headers on `[7, 8]`.

**Comment by roll** [comment]
@mcarans 
Sorry, the release process stuck yesterday and the target version `frictionless@5.5.10` has just been released

**Comment by mcarans** [comment]
Thanks, the test passes now
