### ISSUE TITLE
Merged PR #1255 changes lost in framework v5

### ISSUE THREAD

**Issue by hjoukl** [frictionlessdata/frictionless-py#1399]
Creating this issue to raise some  attention on this. 

Not sure if only this PR is affected or if maybe other merged changes also got lost for v5:

Sadly, somehow the (merged) PR #1255 _never_ made it to framework v5, see #1196.

So running with "long and wide" sqlite tables is still broken (I'd rather consider that issue a bug than an enhancement) on frictionless 5.x. You quickly run into it on RHEL7 systems due to its default SQLite config but it's easily reproducible on other systems, too.

Since my PR was merged in Oct. 2022 after the last v4 release, it looks like there's now no released version that contains the fix.

Let me know if I can help...

Best, Holger

_Originally posted by @hjoukl in https://github.com/frictionlessdata/framework/issues/1196#issuecomment-1396769909_

**Comment by shashigharti** [comment]
Thanks @hjoukl for reporting!

**Comment by roll** [comment]
Thanks @hjoukl ! I'll handle it ASAP

**Comment by hjoukl** [comment]
Hi @shashigharti, I could provide a new PR for this, unless you're on it, anyway.
Nothing fancy (since I've no clue how I could properly rebase the original PR to the v5 line), I'd just simply package the #1255 changes as a brand new PR.

Please let me know if this would help,
H.

**Comment by shashigharti** [comment]
Hi @hjoukl, Thanks I have started working on it, I will use cherry pick and keep the original author and date as before. what do you think?

**Comment by roll** [comment]
@shashigharti Thanks! Please take into account that currently there is duplicated code in expwrimental `resource.index`

**Comment by hjoukl** [comment]
> Hi @hjoukl, Thanks I have started working on it, I will use cherry pick and keep the original author and date as before. what do you think?

Great! Whatever works best for you guys. If there's something I could help with from my side, just let me know.

**Comment by shashigharti** [comment]
@roll I tried changing and found that changing from

```python
self.connection.execute(table.insert().values(buffer))
to
self.connection.execute(table.insert(), buffer)
```

requires dict to be passed as param(Based on the sqlalchemy [documentation](https://github.com/sqlalchemy/sqlalchemy/blob/rel_1_4/lib/sqlalchemy/engine/base.py#L1281) ). So we have to make changes to mapper.write_row(row) to return dict. If not changed, many tests fail with following error:
`TypeError: '<' not supported between instances of 'bool' and 'str'`


**To double check, I tested following code:**
It works
 ```python
result = connection.execute(
                t.insert(),
                [
                        {"x": 7, "y": "jack"},
                        {"x": 8, "y": "ed"},
                ]
            )
```
It doesn't
```python
result = connection.execute(
                t.insert(),
                [
                        [8, "jack"],
                        [8, "ed"],
                ]
            )
```

What do you suggest?

**Comment by roll** [comment]
Thanks a lot @shashigharti -- I will investigate

**Comment by roll** [comment]
Hi @hjoukl,

Thanks a lot for your input. I'm releasing `frictionless@5.6.0` with all the changes incorporated. Also in general, it's better to use `conn.execute(insert, params)` for performance so your contribution was really valuable :+1:

**Comment by hjoukl** [comment]
> Hi @hjoukl,
> 
> Thanks a lot for your input. I'm releasing `frictionless@5.6.0` with all the changes incorporated. 

Great! Looking forward to it.

> Also in general, it's better to use `conn.execute(insert, params)` for performance so your contribution was really valuable 

Well, yes - that's what I already investigated before my PR: https://github.com/hjoukl/bench-sqlalchemy-executemany :-)
(see also here: https://github.com/frictionlessdata/framework/issues/1196#issuecomment-1248638184)

To quote myself:
"The gist of it is that executemany is superior to the previous approach performance-wise, sometimes vastly (especially with SQLite). I've run the sample benchmark for the DB engines tested in your CI (SQlite, PostgreSQL, MySQL)."

Best, Holger

**Comment by roll** [comment]
Thanks!
