### ISSUE TITLE
AttributeError: 'Package' object has no attribute 'to_sql'

### ISSUE THREAD

**Issue by joahim** [frictionlessdata/frictionless-py#1406]
When trying to save the data package to `sqlite` I get the following error:

```AttributeError: 'Package' object has no attribute 'to_sql'```

I'm following the [SQL Format documentation page](https://framework.frictionlessdata.io/docs/formats/sql.html):

```
from frictionless import Package

package = Package('path/to/datapackage.json')
package.to_sql(f'sqlite:///database.db')
```
I installed the `frictionless` python package with `pip install frictionless[sql]`.

Looking at the frictionless source code [v5.5.1] I could indeed not find the `to_sql` method. Is the documentation out of date or am I missing something?

**Comment by roll** [comment]
Thanks @joahim,

It's definitely a bug in the docs or in the code. I'll investigate. In meantime, please try using `package.publish` instead of `package.to_sql`
