### ISSUE TITLE
Unexpected change (bug?) in --basepath behavior (CLI)

### ISSUE THREAD

**Issue by ezwelty** [frictionlessdata/frictionless-py#1416]
# Overview

In v4.40, `--basepath` was prepended to the paths of the resources in the package. In v5.5.5, it is also prepended to the provided path of the descriptor, breaking certain functionality (e.g. validating local file against remote descriptor). Is this intentional or a bug?

`data/test.csv`
```csv
id
```

`datapackage.yaml`
```yaml
name: test
resources:
  - name: test
    path: test.csv
```

```sh
frictionless validate --basepath data datapackage.yaml
```

### 5.5.5
```
# -------
# invalid: ['datapackage.yaml']
# -------
type           message
-------------  ------------------------------------------------------------------------------------------------------------------------------------------------------
package-error  The data package has an error: cannot retrieve metadata "data/datapackage.yaml" because "[Errno 2] No such file or directory: 'data/datapackage.yaml'"
```

### 4.40

```
# -----
# valid: test.csv 
# -----
## Summary 
+------------------------+-------------------+
| Description            | Size/Name/Count   |
+========================+===================+
| File name              | test.csv          |
+------------------------+-------------------+
| File size (bytes)      | 5                 |
+------------------------+-------------------+
| Total Time Taken (sec) | 0.009             |
+------------------------+-------------------+
```

**Comment by ezwelty** [comment]
The same happens with a descriptor loaded from a URL, say `https://example.com/datapackage.yaml`. Doesn't this defeat the purpose of `basepath`, since resource paths are relative to the datapackage descriptor by default?

```
+-------+---------+--------------+----------------------------------------------------------------------------------------+
| Row   | Field   | Type         | Message                                                                                |
+=======+=========+==============+========================================================================================+
|       |         | scheme-error | The data source could not be successfully loaded: 404 Client Error: Not Found for url: |
|       |         |              | https://example.com/test.csv                                                           |
+-------+---------+--------------+----------------------------------------------------------------------------------------+
```

**Comment by roll** [comment]
Thanks @ezwelty! I will fix it

**Comment by roll** [comment]
Hi @ezwelty,

I'm trying to reproduce the problem, but I can't. Say I have this with v5:

> data/issue-1416/test.csv
```
id
1
```

> data/issue-1416/datapackage.yaml
```
name: test
resources:
  - name: test
    path: test.csv
```

```
frictionless validate --basepath data/issue-1416 datapackage.yaml

# -----
# valid: test.csv
# -----

## Summary

+--------------+---------------+
| Name         | Value         |
+==============+===============+
| File Place   | test.csv      |
+--------------+---------------+
| File Size    | 5 Bytes       |
+--------------+---------------+
| Total Time   | 0.036 Seconds |
+--------------+---------------+
| Rows Checked | 1             |
+--------------+---------------+
```

**Comment by roll** [comment]
> The same happens with a descriptor loaded from a URL, say https://example.com/datapackage.yaml. Doesn't this defeat the purpose of basepath, since resource paths are relative to the datapackage descriptor by default?

Thanks. That's the regression I'm just going to handle in #1388

**Comment by ezwelty** [comment]
@roll Here is the core issue:

> In v4.40, --basepath was prepended to the paths of the resources in the package. In v5.5.5, it is also prepended to the provided path of the descriptor

So in your example, you would need to do this to see the problem:

```
frictionless validate --basepath data/issue-1416 data/issue-1416/datapackage.yaml
```

Or move `datapackage.yaml` to the current directory and then do this:

```
frictionless validate --basepath data/issue-1416 datapackage.yaml
```

**Comment by roll** [comment]
@ezwelty 
I see... Yea, it was an intentional change that unified the basepath concept so e.g. now the `Catalog` will work as well using the code like this:

```
catalog = Catalog('catalog.json', basepath='data')
catalog.get_package('name') # will have `data` basepath
```

BTW the problem you mentioned:
> breaking certain functionality (e.g. validating local file against remote descriptor)

Can you please check if it's still actual for `frictionless@5.5.7`?

**Comment by ezwelty** [comment]
@roll Hmm, I must admit I find the new behavior confusing. If `basepath` just prefixes the paths of a catalog's packages (and not also the path to the catalog), then shouldn't `basepath` just prefix the paths of a package's resources? It feels surprising (and the purpose of `basepath` becomes trivial) when `basepath` prefixes the package path when that path is what was given as argument to the function. The result is that the package descriptor and the files can never be separated, hence removing the ability to validate data against a descriptor stored elsewhere.

I tested `frictionless@5.5.7`. The behavior seems the same as before:

```
frictionless validate --schema-sync --basepath local/path/to/csvs \
https://raw.githubusercontent.com/mjacqu/glenglat/main/contribute/datapackage.yaml
```

gives:

```
...
## Errors 

+-------+---------+--------------+----------------------------------------------------------------------------------------+
| Row   | Field   | Type         | Message                                                                                |
+=======+=========+==============+========================================================================================+
|       |         | scheme-error | The data source could not be successfully loaded: 404 Client Error: Not Found for url: |
|       |         |              | https://raw.githubusercontent.com/mjacqu/glenglat/main/contribute/borehole.csv         |
+-------+---------+--------------+----------------------------------------------------------------------------------------+
```

**Comment by roll** [comment]
> @roll Hmm, I must admit I find the new behavior confusing. If basepath just prefixes the paths of a catalog's packages (and not also the path to the catalog), then shouldn't basepath just prefix the paths of a package's resources?

Sorry I wasn't clear. Yes, it prefixes the path to the catalog or any other metadata so the idea is that it works exactly the same to all the metadata types:

> tmp/catalog.json
```
{"name": "catalog", "packages": ["package.json"]}
```
> tmp/package.json
```
{"name": "package", "resources": [{"name": "resource", "path": "table.csv"}]}
```
```python
from frictionless import Catalog

catalog = Catalog("catalog.json", basepath="tmp")
print(catalog.basepath)
# tmp
print(catalog.get_package("package").basepath)
# tmp
print(catalog.get_package("package").get_resource("resource").basepath)
# tmp
```

In v4, the `basepath` semantics was basically different for data and metadata making it impossible to implement nested structures like this.

> The result is that the package descriptor and the files can never be separated

I think that's what actually the specs require :smiley: I mean the idea of data containerization.

> hence removing the ability to validate data against a descriptor stored elsewhere.

I think we might just need to think of an additional feature to make this use case possible

**Comment by roll** [comment]
I've created a feature request - https://github.com/frictionlessdata/framework/issues/1435
