### ISSUE TITLE
Typo Basic Example Python code

### ISSUE THREAD

**Issue by DunklesArchipel** [frictionlessdata/frictionless-py#1420]
A typo in the Python code in the section "Basic Examples - Data transformation" yields an erroneous output.

Specifically lines 207 to 209
```python
source = Resource('data/countries.csv')
target = resource.transform(pipeline)
pprint(target.read_rows())
```

where `resource` should be `source`

**Comment by shashigharti** [comment]
Thanks @DunklesArchipel for reporting!
