### ISSUE TITLE
Upgrading from previous software generation (pre v4)

### ISSUE THREAD

**Issue by cschloer** [frictionlessdata/frictionless-py#1429]
# Overview

Hi @roll , it's been a while! I hope you've been well. As you might remember, we have an application that runs using the old [datapackage-pipelines](https://github.com/frictionlessdata/datapackage-pipelines) package (with pipeline-spec.yaml), as well as the tabulator, tableschema, etc libraries.

I've been browsing the new framework and it seems like it brings together and simplifies a lot of concepts (ie goodtables -> `frictionless validate`, datapackage-pipelines -> `frictionless transform`). However, migrating seems like a very big lift. as I would need to:
    - rebuild the custom processors we made using dataflows
    - migrate all of the old pipeline-spec.yamls to json, ensuring that the steps and the parameters are the same (or find equivalent steps/parameters) and that these pipelines work exactly the same in the new framework.
    - change the runner to use frictionless instead of dataflows.
    - among many other things that I'm probably not thinking of right now

My question to you is: **What other benefits do I gain from upgrading to the new framework besides the simplification & unification of all of these concepts into one?** Specifically:

1.    Are there performance improvements in how the data is streamed/handled? Specifically with large resources or with many (100+) resources in one pipeline. (perhaps from using PETL?)

2.   Is there functionality that wasn't previously possible, or are there simply more standard processors? 
             - One request I often get is the ability to switch the order of resources so that a `Join` step can process resources that were not loaded in in the "correct" order. Is that possible - or has `Join` changed such that this would work?
3.  Is there (planned?) functionality that would allow statistics to be run on the resource? Such as, for each numeric field getting the max, min, and mean values. Currently I am loading each resource into a pandas df for this information, which is obviously not ideal.

Feel free to point me to some resources describing the changes between pre-v4 and current frictionless if that is easier for you!

**Comment by roll** [comment]
Hi @cschloer,

Currently, I'm planning another big step for performance and other aspects you mentioned to be implemented in `frictionless@6` as well as there is ongoing work on https://github.com/frictionlessdata/application to provide visual components for pipelines/etc, so I think the best option will be to wait till it's done, and then we can think of the best ways of the migration (and proper justification like 10x faster etc)

**Comment by cschloer** [comment]
Thanks @roll . I see from [the roadmap](https://frictionlessdata.io/development/roadmap/) that v6 is scheduled to be released in June. That timeline works on my end - I'll check back in then!

**Comment by cschloer** [comment]
Hey @roll - taking a look at the roadmap again, it seems like V6 has been removed. Has it been lowered in priority?

**Comment by roll** [comment]
Hi @cschloer, yea, currently, we're exploring different options

**Comment by cschloer** [comment]
Hi @roll - if V6 is not planned, do you think it's still worth it to update to v5, purely from a performance perspective?

I also assume that if V6 ever does indeed come out, the changes won't be quite as breaking as they were to v4?

**Comment by cschloer** [comment]
Another question related to all of this -

Would it be feasible to fork the [open data editor](https://github.com/okfn/opendataeditor) to run as a web application? I assume so because you've written it in react, but I wonder if you have any thoughts. I'd also want to make changes to add custom processors, integrate tightly with the rest of our infrastructure (which the current UI I've built for datapackage pipelines is doing), as well as make various other changes but I assume that is doable with a fork.

If so, do you have an updated timeline on when the stable v1 version will be released? I'd obviously prefer to fork post stable release.

**Comment by roll** [comment]
Hi @cschloer,

Sorry for the slow replying and updating. Really soon we might have absolutely great news on a partnership with a team that you actually know really well :smile: From January we will be shaping Frictionelss roadmap collaboratively with them and if you're interested we can just talk all together and look for the best approach.

Open Data Editor roadmap is also at work now and I hope we will provide it in December.

**Comment by nickolay** [comment]
> Would it be feasible to fork the [open data editor](https://github.com/okfn/opendataeditor) to run as a web application? I assume so because you've written it in react

Sorry to bump this, but as I was wondering about that too — seems like ODE [has switched to QT](https://github.com/okfn/opendataeditor/issues/712) and the web (react) components are [discontinued](https://github.com/frictionlessdata/components).

https://github.com/frictionlessdata/frictionless-ci which relied on those components for visualization seems to be abandoned too..
