### ISSUE TITLE
Errors with usual delimiter in version 5

### ISSUE THREAD

**Issue by jze** [frictionlessdata/frictionless-py#1430]
# Overview

I have discovered a regression in version 5 of the framework when using an unusual delimiter character. I try to describe how to reproduce the problem.

The data I work with is a CSV export of the German *Verwaltungsdaten-Informationsplattform* (government data information platform): https://www.verwaltungsdaten-informationsplattform.de/SiteGlobals/Functions/RegisterPublicExport/CSV/RegisterExporterCsv This is a ZIP file containing three CSV files. The names of the files within the ZIP file will probably change.

First I use the latest version of the 4.x branch of the Framework (currently 4.40.1):

```
pip install 'frictionless<5'
frictionless describe --dialect '{"delimiter":"~"}' --json 2023-02-16_13-05-39_Register.csv  > test4.json
frictionless validate test4.json
```

That works without problems. Now the same with the latest version from 5.x branch (currently 5.6.0):

```
pip install 'frictionless>=5'
frictionless describe --dialect '{"delimiter":"~"}' --json 2023-02-16_13-05-39_Register.csv  > test5.json
frictionless validate test5.json
frictionless validate test4.json
```

When I change the delimiter of the CSV file to TAB (before you can do that you have to remove the TAB characters contained in the original file) and repeat the whole process it also works with version 5.

**Comment by roll** [comment]
Thanks! I'm releasing a fix

**Comment by jze** [comment]
Thank you for the quick correction. With version 5.6.2 it works now.
