### ISSUE TITLE
extension `frictionless[wkt]` not found

### ISSUE THREAD

**Issue by jze** [frictionlessdata/frictionless-py#1448]
The processing of the `wkt` format moved to an extension. Somehow finding this extension does not work. Although `frictionless[wkt]` is installed I get this error message:

```
[error] Please install "frictionless[wkt]" 
```

Here is a minimal example to reproduce the problem:

```bash
docker run -it --rm python:3-alpine /bin/sh
pip install frictionless 
pip install frictionless[wkt]
touch test.csv
echo '{"name":"test","path":"test.csv","schema":{"fields":[{"name":"geometry","type":"string","format":"wkt"}]}}' > test.json
frictionless extract test.json
```

**Comment by roll** [comment]
Thanks @jze, unfortunately grako (that gives us WKT support) doesn't work in Python3.10+. I've added better error message
