### ISSUE TITLE
Add Quickstart section to README

### ISSUE THREAD

**Issue by davidgasquez** [frictionlessdata/frictionless-py#1465]
Hey there!

Would be awesome to have a small Quickstart section in the main README. Right now, it takes a few clicks to even get to  `pip install frictionless` (Right side URL, then _Getting Started_).

Personally, I got confussed as I wasn't sure this was the package that [superseeded `datapackage`](https://github.com/frictionlessdata/datapackage-py). Something like a small section sharing how it can be installed and what can you do with it quickly would have been very handy.

I'm thinking about something as simple as:

```Python
from frictionless import Package

package = Package('table.csv')

package.extract() # ...
package.describe() # ...
```

**Comment by shashigharti** [comment]
Thank you @davidgasquez for reporting.

**Comment by roll** [comment]
Thanks!

I returned the superseding notices (we had removed them at some point as another organization was planning to develop those libs separately):
- https://github.com/frictionlessdata/datapackage-py#datapackage-py
- https://github.com/frictionlessdata/tableschema-py#tableschema-py

Aslo, I added the installation command to the Readme (in-general, we have short readme just not to duplicated with the docs portal)
