### ISSUE TITLE
Validation bug: license should contain `path` or `name`

### ISSUE THREAD

**Issue by peterdesmet** [frictionlessdata/frictionless-py#1467]
A package `license` can be referenced via `path` and/or `name`: https://specs.frictionlessdata.io/data-package/#licenses. One of the two is sufficient, but validation in Frictionless 5.10.1 seems to require both, even though the help message mentions "path" or "name":

> The data package has an error: license requires "path" or "name": {'path': 'http://creativecommons.org/publicdomain/zero/1.0/'}  

The following fails validation (same if only `name` is provided), while it should pass:

```json
{
    "licenses": [
        {
            "path": "http://creativecommons.org/publicdomain/zero/1.0/"
        }
    ],
    "resources": [
        {
        "name": "test",
        "data": [
            {
            "id": 1,
            "individualName": "Reinaert",
            "scientificName": "Vulpes vulpes"
            }
        ]
        }
    ]
}
```

The following passes validation:

```json
{
    "licenses": [
        {
            "name": "CC0-1.0",
            "path": "http://creativecommons.org/publicdomain/zero/1.0/"
        }
    ],
    "resources": [
        {
        "name": "test",
        "data": [
            {
            "id": 1,
            "individualName": "Reinaert",
            "scientificName": "Vulpes vulpes"
            }
        ]
        }
    ]
}
```

**Comment by roll** [comment]
Thanks @peterdesmet !

**Comment by roll** [comment]
We're releasing `frictionless@5.10.2` with the fix

**Comment by peterdesmet** [comment]
I can confirm this is fixed.
