### ISSUE TITLE
Validation bug: `tabular-data-package` should require `schema` and `profile`

### ISSUE THREAD

**Issue by peterdesmet** [frictionlessdata/frictionless-py#1468]
A package with `"profile": "tabular-data-package"` [requires](https://specs.frictionlessdata.io/schemas/tabular-data-package.json) `resources` to have:

1. `name`
2. `data` or `path`
3. `schema`
4. `profile` (with value `tabular-data-resource`)

The same applies to a package with `"profile": "data-package"` where the resource has `"profile": "tabular-data-resource"`.

Frictionless v5.10.1 however **incorrectly lets the following things pass validation**:

package profile | resource profile | schema
--- | --- | ---
"data-package" | "tabular-data-resource" | missing
"tabular-data-package" | missing | provided
"tabular-data-package" | "tabular-data-resource" | missing
"tabular-data-package" | missing | missing

This was not the case in Frictionless v4.

Test with:

```json
{
  "profile": "tabular-data-package",
  "resources": [
    {
      "name": "test",
      "profile": "tabular-data-resource", <-- should fail if this is removed
      "schema": { <-- should fail is this is removed
        "fields": [
          {
            "name": "id",
            "type": "integer"
          },
          {
            "name": "individualName",
            "type": "string"
          },
          {
            "name": "scientificName",
            "type": "string"
          }
        ]
      },
      "data": [
        {
          "id": 1,
          "individualName": "Reinaert",
          "scientificName": "Vulpes vulpes"
        }
      ]
    }
  ]
}
```

**Comment by peterdesmet** [comment]
Note: I discovered this bug by **requiring** resources to have a `profile` in our own profile for camera trap data (https://github.com/tdwg/camtrap-dp/issues/311#issuecomment-1482862541). In Frictionless v5 adding that requirement fails the validation, even if the resources have a `profile`. This was not the case in v4.

**Comment by roll** [comment]
Thanks!

**Comment by augusto-herrmann** [comment]
I have found out that in some situations the `profile` attribute isn't preserved when reading data package descriptor metadata (#1480). This might influence your use case too, @peterdesmet.

**Comment by peterdesmet** [comment]
Thanks for the comment @augusto-herrmann. In my use case I used `json`, but it does look there is a broader issue with the `profile` property. I.e. in your case it isn't preserved, in my case it seems ignored in validation AND validation fails if I provide my own specs that include certain `profile` requirements.

**Comment by roll** [comment]
Interestingly, that the spec itself doesn't require a schema to be present:
- https://specs.frictionlessdata.io/data-resource
- https://specs.frictionlessdata.io/tabular-data-resource/

I'm curious whether it's a bug in the text or in the jsonschema

**Comment by peterdesmet** [comment]
The spec for `data-resource` does not require a schema (makes sense), the spec for `tabular-data-resource` does: https://specs.frictionlessdata.io/schemas/tabular-data-resource.json, line 11 and 19

**Comment by roll** [comment]
@peterdesmet 
I mean the text of the standard, which is a primary point of truth doesn't seem to require it (although it's hard to say what was the intention)

**Comment by peterdesmet** [comment]
Yeah, it is true that although https://specs.frictionlessdata.io/tabular-data-resource/ mentions `schema` at several places, it doesn't explicitly indicate that it is required.

**Comment by augusto-herrmann** [comment]
Doesn't it require? From [this excerpt](https://specs.frictionlessdata.io/tabular-data-resource/#introduction) it looks like to me that it does:

> Tabular [Data Resource](https://specs.frictionlessdata.io/data-resource/) extends Data Resource
> in following key ways:
> * The schema property MUST follow the [Table Schema](https://specs.frictionlessdata.io/table-schema/)
> specification, either as a JSON object directly under the property, or a string referencing another
> JSON document containing the Table Schema

**Comment by roll** [comment]
@augusto-herrmann 
TBH It's not clear as if we literally follow the specs language it's more like saying that "schema MAY be present but IF it's present it MUST be Table Schema"

**Comment by roll** [comment]
The fix has been released (compatible with the current JSON Schema)

**Comment by augusto-herrmann** [comment]
Awesome! Thank you, @roll.

**Comment by peterdesmet** [comment]
Excellent! That solves my [original bug](https://github.com/tdwg/camtrap-dp/issues/311#issuecomment-1482862541) too.
