### ISSUE TITLE
Sql Format documentation needs update when reading from a database

### ISSUE THREAD

**Issue by fjuniorr** [frictionlessdata/frictionless-py#1487]
# Overview

In `frictionless` [Sql Format docs](https://framework.frictionlessdata.io/docs/formats/sql.html) the code snippet for reading a data package from a SQL database is 

```python
from frictionless import Package
package = Package.from_sql('postgresql://database')
```

which generates the error `AttributeError: type object 'Package' has no attribute 'from_sql'`. The correct way (at least in version 5.10.5) is simply:

```python
from frictionless import Package
package = Package('postgresql://database')
```

**Comment by shashigharti** [comment]
Thanks @fjuniorr for reporting!
