### ISSUE TITLE
GTFS.zip extraction errors

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#1492]
I'm trying to understand why fictionless returns an error trying to extract from GTFS.zip:

`
PS C:\tmp> frictionless validate *
───────────────── Dataset ─────────────────
┏━━━━━━━━━━━━━━━━━┳━━━━━━┳━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓
┃ name            ┃ type ┃ path                ┃ status ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━╇━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩
│ agency          │ text │ agency.txt          │ VALID  │
│ calendar        │ text │ calendar.txt        │ VALID  │
│ calendar_dates  │ text │ calendar_dates.txt  │ VALID  │
│ fare_attributes │ text │ fare_attributes.txt │ VALID  │
│ fare_rules      │ text │ fare_rules.txt      │ VALID  │
│ feed_info       │ text │ feed_info.txt       │ VALID  │
│ routes          │ text │ routes.txt          │ VALID  │
│ shapes          │ text │ shapes.txt          │ VALID  │
│ stops           │ text │ stops.txt           │ VALID  │
│ stop_times      │ text │ stop_times.txt      │ VALID  │
│ trips           │ text │ trips.txt           │ VALID  │
└─────────────────┴──────┴─────────────────────┴────────┘
PS C:\tmp> frictionless describe *
───────────────── Dataset ─────────────────
┏━━━━━━━━━━━━━━━━━┳━━━━━━┳━━━━━━━━━━━━━━━━━━━━━┓
┃ name            ┃ type ┃ path                ┃
┡━━━━━━━━━━━━━━━━━╇━━━━━━╇━━━━━━━━━━━━━━━━━━━━━┩
│ agency          │ text │ agency.txt          │
│ calendar        │ text │ calendar.txt        │
│ calendar_dates  │ text │ calendar_dates.txt  │
│ fare_attributes │ text │ fare_attributes.txt │
│ fare_rules      │ text │ fare_rules.txt      │
│ feed_info       │ text │ feed_info.txt       │
│ routes          │ text │ routes.txt          │
│ shapes          │ text │ shapes.txt          │
│ stops           │ text │ stops.txt           │
│ stop_times      │ text │ stop_times.txt      │
│ trips           │ text │ trips.txt           │
└─────────────────┴──────┴─────────────────────┘
───────────────── Tables ──────────────────
PS C:\tmp> frictionless extract *
╭─ Error ─────────────────────────────────╮
│ No tabular data have been found in the source                                                                                                                                                                 │
╰──────────────────────────────────────╯

`

You can see the data I used @ [link](https://api.actransit.org/transit/gtfs/download?token=2512B81107A09D2DC44895CDDC650D47)

_Originally posted by @mpaine-act in https://github.com/frictionlessdata/frictionlessdata.io/discussions/807_

**Comment by shashigharti** [comment]
The `extract` function is not working because files are in '.txt' format. The current solution would be either converting the format to .csv file and re-running the `extract` command  or  explicitly specifying the format and running the command for each file

`frictionless extract agency.txt --format csv`

**Comment by mpaine-act** [comment]
I see now.  GTFS is wrong by its own definition (use .txt instead of .csv).   I'll use the explicit format parameter as suggested.
