### ISSUE TITLE
Missing value on a date column on excel throws validation error

### ISSUE THREAD

**Issue by fjuniorr** [frictionlessdata/frictionless-py#1503]
# Overview

I'm trying to validate a resource that stores data in an excel file in which of of the columns should be a date but missing values coded as 0 should be allowed. Here's the data:

![20230512T092224](https://github.com/frictionlessdata/framework/assets/4969445/847d7652-bc1a-4241-9ad0-7eabfe149f1d)

and the table schema

```json
      "schema": {
        "fields": [
          {
            "name": "id",
            "type": "integer"
          },
          {
            "name": "updated_at",
            "type": "date",
            "missingValues": [
              "0"
            ]
          }
        ]
      }
```

However, when I validate this resource I get a type error saying that

```
Type error in the cell "0" in row "3" and field "updated_at" at position "2": type is "date/default"
```

For a resource using a csv file to store data the same schema works.

There is a reproducible example available [here](https://github.com/splor-mg/datapackage-reprex/tree/main/20230512T084359).

**Comment by roll** [comment]
Thanks! We will investigate!

**Comment by fjuniorr** [comment]
Thanks for the fix @roll! Are you by any chance planning a new release to pypi anytime soon?

**Comment by roll** [comment]
Hi @fjuniorr,

Sorry for the delay, yes I hope we will release next week. Usually, we release straight after the fix but currently, we're temporary distribute Frictionless Application as a part of the framework and it requires a little bit more work before the release
