### ISSUE TITLE
Possible Bug on Windows: "FrictionlessException: [schema-error] Schema is not valid"

### ISSUE THREAD

**Issue by labanca** [frictionlessdata/frictionless-py#1505]
# Overview

I believe I'm facing a bug using Frictionless version 5.13.1 on Windows 10.

I'm trying to get a package from an URL with the following code:
```
from frictionless import Package

url = 'https://raw.githubusercontent.com/transparencia-mg/datapackage-reprex/foreign-key-constraint/datapackage.json'
package = Package(url)
```

and getting the following error:

`FrictionlessException: [schema-error] Schema is not valid: cannot retrieve metadata "https://raw.githubusercontent.com/transparencia-mg/datapackage-reprex/foreign-key-constraint\schema/estados.json" because "404 Client Error: Not Found for URL: [https://raw.githubusercontent.com/transparencia-mg/datapackage-reprex/foreign-key-constraint%5Cschema/estados.json"](https://raw.githubusercontent.com/transparencia-mg/datapackage-reprex/foreign-key-constraint%5Cschema/estados.json%22)`

The file [datapackage.json](https://raw.githubusercontent.com/transparencia-mg/datapackage-reprex/foreign-key-constraint/datapackage.json) exists and is available. 

I noted that the schema URL presented in the error message `https://raw.githubusercontent.com/transparencia-mg/datapackage-reprex/foreign-key-constraint\schema/estados.json` have a backslash instead of all regular slashes (foreign-key-constraint\schema/estados.json ) and **I suspect the error could be being caused by this malformed URL** . Checking the data package being accessed this error is not in it.

I tried 2 other versions of Frictionless (5.12.1 and 5.11.1) and got the same error.

I inferred that this might be a Windows bug because running the same snippet on a Mac OS works fine without this error.

**Comment by roll** [comment]
Thanks for reporting!
