### ISSUE TITLE
Decription function throwing Value error

### ISSUE THREAD

**Issue by RonanFog** [frictionlessdata/frictionless-py#1507]
# Overview

Hi I've been playing around with frictionless this last week but recently when I run the describe function it outputs a result from the validate function and then an error. the command then works when I run it a second time. Does anyone know why this is the case.

The issue is with the describe command.

Output:
```
[[10,
  'Start Date',
  '5/1/1997',
  'The value does not match the schema type and format for this field.',
  None],
 [13,
  'End Date',
  '9/31/2001',
  'The value does not match the schema type and format for this field.',
  None],
 [1855,
  'Start Date',
  '3/5/2008',
  'The value does not match the schema type and format for this field.',
  None]]
```
Error:
`ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
`

This has occurred after playing around with editing the data types of the same excel file. 

```
# Import statements
import frictionless as f
import pandas as pd
from pprint import pprint

# Read in the user defined schema
uploaded_schema = pd.read_csv('path_to_schema_csv')

# Set nissing valus rule
detector = f.Detector(field_missing_values=["#N/A", "null"])

# get data description
desc = f.describe("path_to_excel_data_file", detector=detector)

# Set all field types to that of the user generated fields
for i in range(len(desc.schema.fields)):
    desc.schema.set_field_type(desc.schema.fields[i].name, uploaded_schema[uploaded_schema['name'] == desc.schema.fields[i].name]['type'].values[0])

# get vaidation report and print
report = f.validate(desc)

pprint(report.flatten(["rowNumber", "fieldName", "cell", "description", "messsage"]))
```

The schema csv file is just a csv wit the column name an

| name       | type     |
|------------|----------|
| name       | string   |
| id         | string   |
| tite       | string   |
| start date | datetime |
| end date   | datetime |
| salary     | number   |

**Comment by shashigharti** [comment]
Thanks @RonanFog  for reporting!

**Comment by shashigharti** [comment]
Hi @RonanFog 

I tried running exact same code and could not replicate the error.  
frictionless version 5.13.1

The csv file that I am using is:

```text
name,id,tite,start date,end date,salary
test,1,developer,04/04/2022,04/04/2030,10000
```
![outoupt](https://github.com/frictionlessdata/framework/assets/5582809/9c01d354-d257-4fab-93b0-45464bc0bb67)

**Comment by shashigharti** [comment]
Closing for now. Please let me know if you need additional help.
