### ISSUE TITLE
Cannot create CSV/TSV file without header

### ISSUE THREAD

**Issue by rhorenov** [frictionlessdata/frictionless-py#1513]
# Problem Description

Hi there,
I was trying to create a CSV/TSV file WITHOUT header, but was not able to do it.

# Versions

Frictionless:
```
$ pip freeze | grep frictionless
frictionless==5.13.1
```
OS:
```
Microsoft Windows [Version 10.0.19045.2846]
```

# Sample code:
```
from frictionless import Dialect, Resource


def main():
    with Resource("capital-3.csv") as resource:
        print(f"Header: {resource.header}")
        print(f"Valid: {resource.header.valid}")

        new_table = "tmp_table.tsv"
        dialect = Dialect.from_descriptor({"header": False, "delimiter": "\t"})
        resource.write_table(new_table, dialect=dialect, encoding='utf-8')

    print()
    print("Result (expected WITHOUT header):")
    print(open(new_table).read())


if __name__ == "__main__":
    main()
```

I'm reading a simple CSV file with a header and two columns and writing it to another file. 

Note the 'header = False' in the dialect:

```dialect = Dialect.from_descriptor({"header": False, "delimiter": "\t"})```

# stdout
```
Header: ['id', 'name']
Valid: True

Result (expected WITHOUT header):
id	name
1	London
2	Prague
3	Berlin
```

# Current Result - 'tmp_table.tsv' file:
Header is present:
```
id	name
1	London
2	Prague
3	Berlin
```

# Expected Result - 'tmp_table.tsv' file:
Shall be WITHOUT header:
```
1	London
2	Prague
3	Berlin
```

# Conclusion
Is it a bug or a mistake of mine somewhere?

Regards,
Roman

**Comment by roll** [comment]
Thanks a lot for reporting!
