### ISSUE TITLE
Constrain one column depending on another

### ISSUE THREAD

**Issue by Pierlou** [frictionlessdata/frictionless-py#1521]
# Overview

Hi, I've searched accross the other issues and I haven't been able to find a similar topic: within the framework of the [schema.data.gouv.fr](https://schema.data.gouv.fr/) initiative, we have been looking for a way to constrain one column depending on another one in a TableSchema. For example:
- `col1` is constrained as a boolean
- we would like `col2` to be constrained as follows: if `col1` is `true`, `col2` is restrained to `['1', '2', '3']` ; if `col1` is `false`, `col2` is restrained to `['A', 'B', 'C']`

A slightly more complex case would be that `col1` is constrained with `enum` and then for each different value that `col1` can have, `col2` has a different set of `enum` constraints.
Is there a way to do so in the current state of the TableSchema standard?

**Comment by shashigharti** [comment]
@Pierlou it could be achieved through https://framework.frictionlessdata.io/docs/checks/row.html#row-constraint

`formula="col2 in [1,2,3] if col1 else col2 in [a,b,c]"`

It is not possible through `TableSchema standard`
