### ISSUE TITLE
frictionless update: I have "command not found: frictionless", after updating

### ISSUE THREAD

**Issue by aborruso** [frictionlessdata/frictionless-py#1552]
Hi,
I have just installed frictionless-5.14.2. Now if I run `frictionless --help`, I have this error: `zsh: command not found: frictionless`.

I have uninstalled it, and installed again `5.13.1`, and it works.

**Comment by aborruso** [comment]
@roll do you have any advice for me to solve this behavior? Thank you

**Comment by roll** [comment]
@aborruso Can you pleasy try "v5.14.5" (the latest fix)?

**Comment by aborruso** [comment]
> @aborruso Can you pleasy try "v5.14.5" (the latest fix)?

it works, thank you
