### ISSUE TITLE
Revise error message for query command

### ISSUE THREAD

**Issue by shashigharti** [frictionlessdata/frictionless-py#1555]
# Overview

The error message for `frictionless query` command is not clear and specific. 

![screenshot2](https://github.com/frictionlessdata/framework/assets/5582809/381067dd-fc91-41b8-bb2f-f6419ad2f0c1)

**Comment by roll** [comment]
Hi @shashigharti,

Will it show an error with the `--debug` flag?

**Comment by shashigharti** [comment]
@roll, yes it prints the error with --debug command.

**Comment by shashigharti** [comment]
Closing the issue, the error is displayed with --debug command.
