### ISSUE TITLE
Comment inside dialect/types.py causing mypy to fail

### ISSUE THREAD

**Issue by eliashenko** [frictionlessdata/frictionless-py#1561]
# Overview

`mypy` check for a project that uses `frictionless` fails with the error:
```
site-packages/frictionless/dialect/types.py:28:14: error: invalid syntax  [syntax]
```

frictionless version: **5.14.5**
mypy version: **1.4.1**

### Temporal workaround:
Use `frictionless==5.13.1` for now

**Comment by roll** [comment]
Thanks!

Really weird mypy's reaction to a comment by we will to remove it
