### ISSUE TITLE
Comment inside resource/types.py causing mypy to fail 

### ISSUE THREAD

**Issue by eliashenko** [frictionlessdata/frictionless-py#1563]
# Overview

It is similar to already fixed issue https://github.com/frictionlessdata/frictionless-py/issues/1561, but now it's in different place 😅.  Are there any more of these in the codebase?

mypy check for a project that uses frictionless fails with the error:

`/site-packages/frictionless/resource/types.py:14:15: error: invalid syntax  [syntax]`

frictionless version: 5.15.0
mypy version: 1.4.1

Temporal workaround:
Use frictionless==5.13.1 for now

**Comment by roll** [comment]
Thanks for reporting!

That's super weird as those are pretty valid comments. I guess they might have some special meaning for mypy. @shashigharti can you please investigate?

**Comment by roll** [comment]
Hi @eliashenko,

We removed those comments causing `mypy` to fail but in-general it doesn't pass `mypy` for now as it's configured for `pyright` as a static type checker. I created an issue for it https://github.com/frictionlessdata/frictionless-py/issues/1575
