### ISSUE TITLE
Resource property checklist not automatically included in validation

### ISSUE THREAD

**Issue by pschumm** [frictionlessdata/frictionless-py#1595]
According to the information [here](https://framework.frictionlessdata.io/blog/2022/08-22-frictionless-framework-v5.html#resource), a checklist can be included as a property in a resource descriptor. However, it seems that [such a checklist is not automatically included](https://github.com/frictionlessdata/frictionless-py/blob/ecbedaa5464e454ac4140e5ea9d224c54c8b4cd7/frictionless/resource/resource.py#L598) when calling `validate()` on the resource; instead, you have to specify it manually. Is this behavior intentional, or just an oversight?

**Comment by roll** [comment]
Hi @pschumm, yes, it was disabled for now:

> Since frictionless@5.7 this experimental feature (resource.checklist/pipeline) has been disabled to conform better with the standards.

**Comment by pschumm** [comment]
Ah, sorry I missed that. Makes sense. Thanks very much @roll for your response.
