### ISSUE TITLE
Support optional fields/columns?

### ISSUE THREAD

**Issue by hredestig** [frictionlessdata/frictionless-py#161]
# Overview

It's about having an ability to have an optional field/column e.g.:
```
schema fields: field1, field2, field3, optional
table1 columns: col1, col2, col3, optional # provided
table2 columns: col1, col2, col3 # not provided
```
### Option 1

Full `specs` support  - https://github.com/frictionlessdata/specs/issues/540

### Option 2

A `goodtables` argument:

```python
# actual
validate('table1', schema=schema) # valid
validate('table2', schema=schema) # NOT valid because of missing-header/column

# expected (not existent argument for now)
validate('table1', schema=schema, optional_fields=['optional']) # valid
validate('table2', schema=schema, optional_fields=['optional']) # valid
```

---

_From @hredestig_

is there a way to indicate in the schema that a column may or may not be present, if it is, then the constraints for the field should apply but field may also be missing altogether?

**Comment by roll** [comment]
@hredestig 
There is no such option for now. We will take a look on it.

**Comment by patcon** [comment]
Hitting this with `pattern` constraint, but can do work-around via regex

**Comment by roll** [comment]
@patcon 
We will be doing pre-v1 iteration soon to process all this issues.

**Comment by pwalsh** [comment]
@roll was this addressed with spec v1 support?

**Comment by hredestig** [comment]
That looks great but indeed not what I was thinking of, I thought of situations where the user e.g. may want to include a certain column, say, 'temperature', and if so, there would be constraints saying that it has to be numeric, but that specifying temperature is not strictly required and while the user now could get around this by simply including a column with all missing values, it would appear more natural to me to be allowed to not include that column at all.

**Comment by roll** [comment]
@hredestig 
Thanks! So it seems my initial understanding was correct. It's about having an ability to have an optional field/column e.g.:
```
schema fields: field1, field2, field3, optional
table1 columns: col1, col2, col3, optional # provided
table2 columns: col1, col2, col3 # not provided
```
And we call goodtables like this:
```python
# actual
validate('table1', schema=schema) -> valid
validate('table2', schema=schema) -> not valid
# expected
validate('table1', schema=schema, optional_fields=['optional']) -> valid
validate('table2', schema=schema, optional_fields=['optional']) -> valid
```

**Comment by patcon** [comment]
Hm. Ok, my understanding was not the same as @hredestig, but about having an optionally missing value in a column. I seem to recall that not being possible when a pattern was specified. (But perhaps I'm misremembering.)

**Comment by roll** [comment]
@patcon 
Now `goodtables` is rebased on specs-v1 where all constraints are applied after casting so your use case should work:

```python
from goodtables import validate

source = [
    ['id', 'person'],
    ['1', 'Alex'],
    ['2', ''],
    ['3', 'John'],
]
schema = {
    'fields': [
        {'name': 'id', 'type': 'integer'},
        {'name': 'person', 'constraints': {'pattern': r'\w{4}'}},
    ]
}
report = validate(source, schema=schema)
report['valid'] # True
```

**Comment by roll** [comment]
So I suppose there was two different issue and:
- initial issue is a feature request (not implemented for now)
- second issue is a bug fixed in latest versions of `goodtables`

**Comment by pwalsh** [comment]
@roll the feature request is actually a Table Schema spec feature request, and not a good tables feature request, as I read it. Can you open up an issue for discussion on the specs tracker.

**Comment by roll** [comment]
@pwalsh 
I've created the specs issue - https://github.com/frictionlessdata/specs/issues/540. 

I think this feature either could be implemented on `specs/goodtables` level OR only on `goodtables` level. And my thinking for now that second option is way easier.

**Comment by roll** [comment]
In [Frictionless Framework](https://github.com/frictionlessdata/frictionless-py) there is a `sync_schema` argument for `extract/validate/etc` functions that will adjust a provided schema for cases like this - https://colab.research.google.com/drive/1is_PcpzFl42aWI2B2tHaBGj3jxsKZ_eZ#scrollTo=myOn0wYQcIHY

So if a schema has more fields than a provided data file those fields will be ignored

PS.
Missing values property can be used for fields that can have missing values (as an opposite to a whole field missing).
