### ISSUE TITLE
Remove mentions of API server from documentation

### ISSUE THREAD

**Issue by megin1989** [frictionlessdata/frictionless-py#1669]
# Overview

How can I activate the API server in Python?

Can you please describe the steps?

**Comment by pierrecamilleri** [comment]
The API Server seems to be no longer a feature from frictionless-py, cf [v5.14 changelog](https://github.com/frictionlessdata/frictionless-py/blob/main/CHANGELOG.md#v514). 

@roll, has this functionality been migrated or deleted ?

I keep the issue open as a reminder to remove the remaining mentions of this feature from the documentation (e.g. [here](https://framework.frictionlessdata.io/#features))

**Comment by roll** [comment]
Hi @pierrecamilleri, yes it's been moved to the Open Data Editor codebase

**Comment by pierrecamilleri** [comment]
The docs have been udpated. 

@megin1989, I invite you to have a look at the[ Open Data Editor documentation](https://opendataeditor.okfn.org/contributing/architecture/#server) if you are interested by this functionality. 

However, I draw your attention to this note :

> Note
> 
> API doesn’t use full REST API approach for simplicity. The main reason for this is that the API is designed to be used by the Open Data Editor client and not by external clients.
