### ISSUE TITLE
Frictionless support

### ISSUE THREAD

**Issue by megin1989** [frictionlessdata/frictionless-py#1672]
# Overview

The following are my findings about Frictionless(Please check the link below). Can you please tell me if they are correct or not?

https://docs.google.com/spreadsheets/d/1iPE-CpxW0YlNgFZCvJhwEsUgP2MfqzfBkXxgSgrvtFM/edit?usp=sharing

**Comment by pierrecamilleri** [comment]
After a quick glance, the following values are surprising: 'format not supported' & 'csv dialect not directly supported'; but I don't know what you mean by these terms. 

I'll close the issue, we don't have the time to understand, parse and verify your table, but feel free to open new tickets if the documentation is not clear enough and doesn't seem to answer more specific questions.
