### ISSUE TITLE
object validation

### ISSUE THREAD

**Issue by mingjiecn** [frictionlessdata/frictionless-py#1673]
Frictionless Schema can validate object type according to documentation here: https://specs.frictionlessdata.io/table-schema/#types-and-formats. But there is no details. My question is can it validate the properties of the object and how?

**Comment by jgunstone** [comment]
have you seen this bit: 
https://framework.frictionlessdata.io/docs/guides/validating-data.html

**Comment by mingjiecn** [comment]
Hi, I already checked the documentation. I don't see anywhere give details on how to validate a value that is an object. Or how to create a schema for a filed that is an object type. Do you have any detailed example that you can share? Thanks!

**Comment by jgunstone** [comment]
I don't have a deep understanding of the library so there is probably someone who can provide a more correct comment - 
but my reading is that if you define a field as an object type, then validation will just validate that it is a valid json string (e.g. something like: 
`"{'a': 'a string', 'b': 1}"`

but it wont let you define specific object validation for fields `a` and `b`... 

it might be worth thinking about your datastructure... every row in a table is effectively an object, and the fields of a table can be defined and validated.

**Comment by mingjiecn** [comment]
Thank you so much for your reply. That is what I figured too. I will close this issue.
