### ISSUE TITLE
How to Validate a CSV Column with External JSON Values Using Frictionless JSON Schema?

### ISSUE THREAD

**Issue by megin1989** [frictionlessdata/frictionless-py#1698]
I have a CSV file that I need to validate using a Frictionless JSON schema. One of the columns in the CSV, ORGANIZATION_TYPE, should only contain values from a predefined set, which is specified in an external JSON file (for example, [CodeSystem-organization-type.json](https://terminology.hl7.org/6.0.2/CodeSystem-organization-type.json)).

Is it possible to validate the CSV data in Frictionless using these predefined values from the external JSON file? If so, could you please describe the steps and provide examples?

**Comment by pierrecamilleri** [comment]
You will need to write some code to do this. For instance : 

- write a schema _template_ (e.g. [jinja](https://jinja.palletsprojects.com/en/stable/templates/)), where the enum values are a template variable.
- parse the set of allowed values in your json file 
- Render the template with these values into an operational table schema
- Validate with the rendered schema

**Comment by megin1989** [comment]
Ok, thank you. So, I need to call an API to load the `ORGANIZATION_TYPE` data from an external source, parse the values, and then insert them into the JSON schema template for validation, right?

**Comment by pierrecamilleri** [comment]
>  I need to call an API to load the ORGANIZATION_TYPE data from an external source

If your external source of truth is returned by an API, yes. 

Depending on your needs, you can choose to update your schema for every validation, or not (cache the schema for some time,  trigger regularly a schema update or update manually the schema when needed).

Of course, this procedure only makes sense if the source of truth may change with time. If not, then you are better off doing it once and for all (even by hand given the low number of modalities), and not bother with writing and maintaining the parsing code.

**Comment by megin1989** [comment]
Thank you.
