### ISSUE TITLE
How can I validate a CSV field with a combination of predefined values?

### ISSUE THREAD

**Issue by megin1989** [frictionlessdata/frictionless-py#1704]
Hi,

I'm working with Frictionless to validate a CSV file, and I need to validate a field (shod_domain) against a predefined set of values. The set of allowed values is:

 
```
sdoh-category-unspecified
food-insecurity
housing-instability
homelessness
inadequate-housing
transportation-insecurity

```
The problem is that the field in the CSV file sometimes contains a comma-separated combination of these values. For example:

`Homelessness, Housing Instability`
I want to validate each value in the field to make sure that it's part of the predefined set. If there are any invalid values, I need to report them.

How can I implement this validation using Frictionless? Specifically, I would like to create a custom validation that checks if each comma-separated value in the shod_domain field belongs to the allowed set.

Any help or example code would be greatly appreciated!

Thanks!

**Comment by pierrecamilleri** [comment]
To keep track, here are the answers obtained on Slack : 

@peterdesmet 
> This type of conditional constraint is currently not possible. It is a desired feature though

@e-lo
> Please add your use cases to the discussion I just created here: https://github.com/frictionlessdata/datapackage/discussions/1058

And your own reply :
> I think this link is useful for this
https://datapackage.org/recipes/relationship-between-fields/

I'll add for clarity that the last link relates to a recipe, and does therefore not document something that is part of the official standard.
