### ISSUE TITLE
Validate single resource with `datapackage.json`

### ISSUE THREAD

**Issue by rgieseke** [frictionlessdata/frictionless-py#221]
Is it possible to validate an individual resource file (CSV) against the schema in `datapackage.json`.

I have separate processing scripts for each resource and like to run `goodtables` for each individually.

Setting `schema` didn't work (as `datapackage.json` is not a Table schema I assume).

**Comment by roll** [comment]
@rgieseke 
I think it should be something like:

```python
from datapackage import Package
from goodtables import validate

package = Package('datapackage.json')
for resource in package.resources:
    if resource.tabular:
        report = validate(resource.source, schema=resource.schema.descriptor)
```

**Comment by rgieseke** [comment]
Excellent, thanks! 

I use this now for "resource_name" as an example:
```py
package = Package('datapackage.json')
resource = package.get_resource("resource_name")
report = validate(resource.source, schema=resource.schema.descriptor)
```

**Comment by fjuniorr** [comment]
Is it possible to validate a single resource from a `datapackage.json` from the command line?

I've searched the docs and the help `frictionless validate --help` but couldn't find anything relevant for this use case.

**Comment by roll** [comment]
Hi,

I think it's not possible ATM I've changed it to a feature request

**Comment by lwinfree** [comment]
Oh this would be nice!

**Comment by shashigharti** [comment]
@roll Will it be like this?

```
report = validate(resource, name="resource_name")
frictionless validate --type resource --name resource_name
```

**Comment by roll** [comment]
@shashigharti 

```
report = validate("datapackage.json", resource_name="some")
frictionless validate datapackage.json --resource-name some
```

The idea is getting validation for only 1 resource from N datapackage's resources
