### ISSUE TITLE
Make metadata errors more informative

### ISSUE THREAD

**Issue by rgieseke** [frictionlessdata/frictionless-py#239]
# Overview

For the metadata errors we use:
- Frictionless Data Specs in a form of JSONSchemas
- the `jsonschema` library

For some errors like mentioned in the initial issue (see below) the message from `jsonschema` is not useful at all. We need to find a way to make it better. See similar issue created for JavaScript libraries.

# Initial Issue

Goodtables was again quite helpful in getting a Data Package ready for publication, but one warning message was a bit confusing:

Consider `datapackage.json`:

```json
{
    "name": "test",
    "resources": [
        {
            "path": "data.csv",
            "format": "csv",
            "schema": {
                "fields": [
                    {
                        "name": "id",
                        "type": "string"
                    },
                    {
                        "name": "name",
                        "type": "string"
                    }
                ]
            }
        }
    ]
}
```
and data.csv:
```
id,name
one,oneone
two,twotwo
```
I get
> Warning: Data Package "datapackage.json" has a validation error "Descriptor validation error: {'path': 'data.csv', 'format': 'csv', 'schema': {'fields': [{'name': 'id', 'type': 'string'}, {'name': 'name', 'type': 'string'}]}, 'profile': 'data-resource', 'encoding': 'utf-8'} is not valid under any of the given schemas at "resources/0" in descriptor and at "properties/resources/items/oneOf" in profile"

Adding a field "name" to the resource fixes this, but this wasn't clear from the message.

**Comment by roll** [comment]
It's been fixed in v5 (#1119) (will be release this month)
