### ISSUE TITLE
Support precise foreign-key validation even though the reference table is invalid

### ISSUE THREAD

**Issue by ajpallares** [frictionlessdata/frictionless-py#372]
# Overview

Wrong `foreign-key` errors are generated when the destination row of the foreign key attribute has a `required-constraint` error.

## Steps to reproduce

1. Have two csv files. CSV1 will have an empty field and CSV2 will have a column that is a foreign key to a column of CSV1 and all the foreign keys are found in CSV1. **The empty field in CSV1 must not belong to the column destination of the foreign key of CSV2**.
2. Create a Data Package json file for the two files with the previously defined foreign-key relationship and specifying that the column for the empty field in CSV1 is `required`.
3. Perform the validation of the two files using the previous data package. The validation should be done, at least, for the checks 'schema' and 'foreign-key'.

## Current behavior

The generated report not only reports the `required-constraint` error for the empty field in CSV1 but it also reports as many `foreign-key` errors as the number of rows in CSV2. This errors have a message of the type:
```
Foreign key violation caused by invalid reference table: [owners] There are 1 cast errors (see exception.errors) for row \"3\"
```

If the `required` constraint is removed for the column with the empty field in CSV1, then the validation generates no errors.

## Expected behavior

The generated report should only report the `required-constraint` error for the empty field in CSV1. CSV2 should not generate any errors since all the foreign keys are present in CSV1.

## System and versions

* goodtables version 2.4.16
* Python 3.8.2
* macOS 10.15.5

## Example

[Example_files.zip](https://github.com/frictionlessdata/goodtables-py/files/4750583/Example_files.zip)

* CSV1 (Owners.csv):

|Name  |Surname |ID |
|------|--------|---|
|Tom   |Smith   |1  |
|      |Haggings|2  |
|Robert|Johnson |3  |

Observe that the 2nd row in the CSV has the `Name` field empty.

* CSV2 (Cars.csv):

|Brand |Model   |Plate|Owner_ID|
|------|--------|-----|--------|
|Tesla |Model X |3E-6230|1       |
|BMW   |X4      |JUX•580|2       |
|Mercedes|C 300 Coupe|557 AZW|3  |

* Data package for validation

```json
{
    "resources": [
        {
            "name": "cars",
            "path": "Cars.csv",
            "schema": {
                "fields": [
                    {
                        "name": "Brand",
                        "type": "string",
                        "format": "default"
                    },
                    {
                        "name": "Model",
                        "type": "string",
                        "format": "default"
                    },
                    {
                        "name": "Plate",
                        "type": "string",
                        "format": "default"
                    },
                    {
                        "name": "Owner_ID",
                        "type": "integer",
                        "format": "default",
                        "constraints": {
                            "required": true
                        }
                    }
                ],
                "missingValues": [
                    ""
                ],
                "foreignKeys": [
                    {
                        "fields": "Owner_ID",
                        "reference": {
                            "resource": "owners",
                            "fields": "ID"
                        }
                    }
                ]
            }
        },
        {
            "name": "owners",
            "path": "Owners.csv",
            "schema": {
                "fields": [
                    {
                        "name": "Name",
                        "type": "string",
                        "format": "default",
                        "constraints": {
                            "required": true
                        }
                    },
                    {
                        "name": "Surname",
                        "type": "string",
                        "format": "default"
                    },
                    {
                        "name": "ID",
                        "type": "integer",
                        "format": "default"
                    }
                ],
                "missingValues": [
                    ""
                ]
            }
        }
    ]
}
```

Note that:

1. The column `Owner_ID` in the cars csv points to the `ID` column in the Owners.csv via `foreign-key`.
2. The column `Name` in the owners csv is marked as `required`.

Performing the data package validation with the checks 'schema' and 'foreign-key' generates a report of this type:

```json
{
    "time": 0.046,
    "valid": false,
    "error-count": 4,
    "table-count": 2,
    "tables": [
        {
            "datapackage": "DataPackage.json",
            "resource-name": "cars",
            "time": 0.028,
            "valid": false,
            "error-count": 3,
            "row-count": 4,
            "source": "[...]/Cars.csv",
            "headers": [
                "Brand",
                "Model",
                "Plate",
                "Owner_ID"
            ],
            "scheme": "inline",
            "format": "inline",
            "encoding": "no",
            "schema": "table-schema",
            "errors": [
                {
                    "code": "foreign-key",
                    "row": [
                        "Tesla",
                        "Model X",
                        "3E-6230",
                        "1"
                    ],
                    "row-number": 2,
                    "message": "Foreign key violation caused by invalid reference table: [owners] There are 1 cast errors (see exception.errors) for row \"3\"",
                    "message-data": {}
                },
                {
                    "code": "foreign-key",
                    "row": [
                        "BMW",
                        "X4",
                        "JUX\u00e2\u20ac\u00a2580",
                        "2"
                    ],
                    "row-number": 3,
                    "message": "Foreign key violation caused by invalid reference table: [owners] There are 1 cast errors (see exception.errors) for row \"3\"",
                    "message-data": {}
                },
                {
                    "code": "foreign-key",
                    "row": [
                        "Mercedes",
                        "C 300 Coupe",
                        "557 AZW",
                        "3"
                    ],
                    "row-number": 4,
                    "message": "Foreign key violation caused by invalid reference table: [owners] There are 1 cast errors (see exception.errors) for row \"3\"",
                    "message-data": {}
                }
            ]
        },
        {
            "datapackage": "DataPackage.json",
            "resource-name": "owners",
            "time": 0.021,
            "valid": false,
            "error-count": 1,
            "row-count": 4,
            "source": "[...]/Owners.csv",
            "headers": [
                "Name",
                "Surname",
                "ID"
            ],
            "scheme": "inline",
            "format": "inline",
            "encoding": "no",
            "schema": "table-schema",
            "errors": [
                {
                    "code": "required-constraint",
                    "row": [
                        "",
                        "Haggings",
                        "2"
                    ],
                    "row-number": 3,
                    "column-number": 1,
                    "message": "Column 1 is a required field, but row 3 has no value",
                    "message-data": {}
                }
            ]
        }
    ],
    "warnings": [],
    "preset": "datapackage"
}
```

Notice how the cars csv has 3 errors with code `foreign-key`. But these 3 errors should not arise. Only the `required-constraint` error in the owners csv should be reported.

In fact, removing the required constraint for the `Name` column in the owners csv, results in a report with no errors. 

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Thanks @ajpallares,

For now, this behavior is expected as underlying `tableschema/datapackage` libraries don't properly allow reading data and ignoring errors.

I'm targeting of shipping this improvement with https://github.com/frictionlessdata/goodtables-py/tree/v3 at some point (when I re-implement reading mechanism in the underlying libs)

**Comment by roll** [comment]
Fixed in [Frictionless Framework](https://github.com/frictionlessdata/frictionless-py).

For example, see https://github.com/frictionlessdata/frictionless-py/blob/master/tests/validate/test_package.py#L294
