### ISSUE TITLE
Loading error leads to success

### ISSUE THREAD

**Issue by timtroendle** [frictionlessdata/frictionless-py#373]
# Overview

Goodtables returns a success error code (0) when there is an error loading the JSON. In our case, this leads to our CI falsly reporting success.

Minimal example:
``` json
{
    "profile": "tabular-data-package",
    "resources": [
          {
            "path": "test.csv",
            "profile": "tabular-data-resource",
            "schema": {
                "fields": [
                    {
                        "name": "test
                        "
                    }
                ]
            }
        }
    ]
}
```

Running `goodtables test.json` returns a `0` return code and the following output:

```bash
DATASET
=======
{'error-count': 0,
 'preset': 'nested',
 'table-count': 0,
 'time': 0.001,
 'valid': True}
---------
Warning: Data Package "test.json" has a loading error "Unable to parse JSON at "test.json". Invalid control character at: line 10 column 36 (char 261)"
```

goodtables 2.5.0

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi @timtroendle,

It's a design problem of `goodtables@2`. It's going to be fixed in `goodtables@3` (you can try if you're curious `pip install goodtables --pre`) but it's about a month before the release

**Comment by roll** [comment]
The new version is now released under the name `frictionless`. See in more details here - https://github.com/frictionlessdata/frictionless-py#frictionless-for-python

The behavior is correct now:

```
$ frictionless validate tmp/invalid.json
$ echo $?
1
```

It's not possible to fix it for the `goodtables` branch unfortunately as it mentioned above.
