### ISSUE TITLE
Ability to pass tabulator.Stream to the validate function

### ISSUE THREAD

**Issue by isichei** [frictionlessdata/frictionless-py#374]
# Overview

I would expect to be able to pass a Stream object from tabulator into the validate function:

```
from goodtables import validate
from tabulator import Stream

schema = {'$schema': 'https://frictionlessdata.io/schemas/table-schema.json',
 'fields': [{'name': 'my_int',
   'type': 'integer',
   'format': 'default',
   'constraints': {'required': True, 'minimum': 10, 'maximum': 20}},
  {'name': 'animal',
   'type': 'string',
   'format': 'default',
   'constraints': {'required': True,
    'enum': ['cat', 'dog', 'fish', 'chicken']}},
  {'name': 'my_email',
   'type': 'string',
   'format': 'default',
   'constraints': {}},
  {'name': 'my_datetime',
   'type': 'datetime',
   'format': 'any',
   'constraints': {}},
  {'name': 'my_date', 'type': 'date', 'format': 'any', 'constraints': {}}],
 'missingValues': ['']}


resp = validate("table1.csv", schema=schema) # valid resp['valid'] = True

resp = validate(Stream("table1.csv"), schema=schema) # valid resp['valid'] = False  => 'message': 'Only byte streams are supported.'
```

I would have expected to just be able to pass a `Stream` object to the validate as it looks like the validate function creates a stream obj to read in the file name?

The current workaround I use is to just read in the data from the stream myself. And then pass that into validate which works.

```python
data = Stream("table1.csv").open().read()
resp = validate(data, schema=schema) 
```
However, I was wondering if when you use stream inside `validate` do you just read all the data or do you use the iterator to avoid reading large datasets into memory?

### Further notes:

 `table1.csv` is:
```
my_int,animal,my_email,my_datetime,my_date
16,fish,omar65@waller.info,2013-01-14 15:54:20,1993-09-27
13,cat,nataliechavez@hotmail.com,2006-12-16 01:44:21,1989-04-08
13,dog,stephanie12@leblanc.com,1972-06-19 11:22:59,2006-10-01
```
---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi @isichei,

I think it will be a nice feature. As a current workaround with proper streaming, you can pass a table iterator:

```
source = Stream('path.csv').iter()
report = validate(source, schema=schema) 
```

**Comment by isichei** [comment]
Thanks that's super useful!

**Comment by roll** [comment]
With Frictionless Framework:

```python
from frictionless import Table, validate

with Table("data/table.csv") as table:
    validate(table)
```

I'm closing the issue as I think it's close enough. The syntax is more verbose just because a user in many cases needs to keep control of opening/closing a table.
