### ISSUE TITLE
Column with non matching header causes an exception when order_fields is set to True

### ISSUE THREAD

**Issue by ajpallares** [frictionlessdata/frictionless-py#376]
# Overview

Validating a table with a column whose header name is not included in the schema causes an exception/crash.

## System and versions
* goodtables version 2.5.0
* Python 3.8.2
* macOS 10.15.5

## Example

Here is a example that demonstrates the issue:

```python
from goodtables import validate

def main():
    data_exception = [
        ["Name", "Type", "Extra"],
        ["A", "Type A", "extra info A"],
        ["B", "Type B", "extra info B"],
    ]

    descriptor = {
        "resources": [
            {
                "name": "example",
                "data": data_exception,
                "schema": {
                    "fields": [{
                        "name": "Name",
                        "type": "string"
                    },
                        {
                            "name": "Type",
                            "type": "string"
                        }
                    ]
                }
            }
        ]
    }

    validate(descriptor, order_fields=True)


if __name__ == '__main__':
    main()

```

## Possible solution

The issue seems to be originated in the `non_matching_header.py` file. In line 62 (version 2.5.0 of goodtables):

```python
new_cell = create_cell(header=None, field=cell.get('field'))
```

The variable `cell` is being accessed without having been previously declared.

I believe that a valid fix would simply be to declare it right before:
```python
cell = cells[index]
```

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by ajpallares** [comment]
@roll I can send a PR for this, if you want me to.

**Comment by roll** [comment]
@ajpallares 
Hi, sure, please

**Comment by roll** [comment]
It's fixed in [Frictionless Framework](https://github.com/frictionlessdata/frictionless-py).

```python
from pprint import pprint
from frictionless import validate


def main():
    data_exception = [
        ["Name", "Type", "Extra"],
        ["A", "Type A", "extra info A"],
        ["B", "Type B", "extra info B"],
    ]

    descriptor = {
        "resources": [
            {
                "name": "example",
                "data": data_exception,
                "schema": {
                    "fields": [
                        {"name": "Name", "type": "string"},
                        {"name": "Type", "type": "string"},
                    ]
                },
            }
        ]
    }

    report = validate(descriptor, sync_schema=True)
    pprint(report)


if __name__ == "__main__":
    main()
```

I'm closing the PR - https://github.com/frictionlessdata/frictionless-py/pull/377. If you really need to merge this fix for `goodtables`, could you please create a new PR for the goodtables branch? Anyway, I really recommend migrating to `frictionless` as this logic e.g. field reordering was significantly improved.
