### ISSUE TITLE
Tables are not validated if columns are not in order

### ISSUE THREAD

**Issue by gegenschall** [frictionlessdata/frictionless-py#380]
# Overview
I'm trying to validate a table using a provided schema. If the columns in the table are in arbitrary order goodtables will not validate them correctly. Am I missing something here? Do I need to supply an option to enable this?

I'm currently using version 3.0.0-alpha.6

Here is a test case for this problem:
```python
def test_goodtables_validates_unordered_tables():
    rows = [
        ['headerB', 'headerA'],
        ['valueB', 'valueA']
    ]

    schema = {
        "fields": [
            {
                "name": "headerA",
                "type": "string",
                "format": "default",
                "constraints": {
                    "required": True,
                    "enum": ["valueA"]
                }
            },
            {
                "name": "headerB",
                "type": "string",
                "format": "default",
                "constraints": {
                    "required": True,
                    "enum": ["valueB"]
                }
            }
        ]
    }

    report = goodtables.validate_table(rows, schema=schema)
    assert report['valid']  # this fails
```

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Sorry for the late reply,

there is now the `sync_schema` option to resolve this problem - https://colab.research.google.com/drive/1is_PcpzFl42aWI2B2tHaBGj3jxsKZ_eZ#scrollTo=myOn0wYQcIHY (the example is for extracting data but it will also work for the `validate` function):

```python
validate(..., sync_schema=True)
```

`goodtables@3` was released under the name `frictionless` - https://github.com/frictionlessdata/frictionless-py#frictionless-for-python
