### ISSUE TITLE
Add an option to ignore cases in headers

### ISSUE THREAD

**Issue by Thomas-Hirsch** [frictionlessdata/frictionless-py#381]
# Overview

The `non-matching-header` test can be too strict, if the headings in the data are a different case from the schema. Curiously, the `_check_with_ordering()` method applies the `_slugify()` method in the check, but the `_check_without_ordering()` doesn't. It's not clear why - I think it's just an inconsistency, but I'm not sure of the rationale behind this function. I'd suggest either the test is case-insensitive by default (possibly with a warning if the only discrepancy is case), or have an option to disable case checking that's more user-friendly than creating a custom check to replace it.

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Thanks, not I see.

I'm marking it as a feature request as it seems there is no trivial solution for it. Data including headers is case sensitive but I agree that we need to accept the `ignore_headers_case` option.

**Comment by roll** [comment]
Hi, it's now available with `frictionless@3.23` - https://colab.research.google.com/drive/1is_PcpzFl42aWI2B2tHaBGj3jxsKZ_eZ#scrollTo=YJjaIcmoQEip
