### ISSUE TITLE
Validator will not except None as an acceptable missing value in data when schema states that the field is nullable.

### ISSUE THREAD

**Issue by isichei** [frictionlessdata/frictionless-py#382]
# Overview

Validator will not except `None` as an acceptable missing value in data when schema states that the field is nullable.

```python
from goodtables import validate

test_data = [
    {'employee_id': 660148, 'employee_name': 'Michael Roth'},
    {'employee_id': 157311,'employee_name': None}
]

schema = {
  '$schema': 'https://frictionlessdata.io/schemas/table-schema.json',
  'fields': [
    {
      'name': 'employee_id',
      'type': 'integer',
      'format': 'default',
      'constraints': {'required': True, 'minimum': 100000, 'maximum': 999999}
    },
    {
      'name': 'employee_name',
      'type': 'string',
      'format': 'default',
      'constraints': {'required': False},
    }
 ],
'missingValues': []
}
resp = validate(test_data, schema=schema) # resp["valid"] = False
```

The resp dict gives

```python
{'time': 0.105,
 'valid': False,
 'error-count': 1,
 'table-count': 1,
 'tables': [{'time': 0.001,
   'valid': False,
   'error-count': 1,
   'row-count': 2,
   'source': 'inline',
   'headers': ['employee_id', 'employee_name'],
   'format': 'inline',
   'schema': 'table-schema',
   'errors': [{'code': 'missing-value',
     'row': [157311],
     'row-number': 2,
     'column-number': 2,
     'message': 'Row 2 has a missing value in column 2',
     'message-data': {}}]}],
 'warnings': [],
 'preset': 'table'}
```

From the above you can see the row given in the failed response shows that the validated row drops the second item in the list (this also happens if you provide your data as a list of lists rather than list of dictionaries). I would expect the row to still be `[157311, None]` and not `[157311]`.

This will pass validation if I set the schema's `missingValues` property to `[""]` and then replace `None` in the data with `""`. But I would assume that the validator should treat a `None` as missing as it's Python's native value for `null` (and is also what is returned from the `Stream` class if using that to read your data). I have tried added `None` to the list of possible values allowed to be missing but I get an error stating None is not valid for type String.

Is there a way to tell the validator that None is an acceptable missing value?

_Using goodtables version 2.5.0_

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by isichei** [comment]
Ok so have looked at this a bit further and I am not sure if it is actually an issue or a definitions thing...

I believe the [_remove_none_values](https://github.com/frictionlessdata/goodtables-py/blob/master/goodtables/cells.py#L58-L63) function is what is dropping the `None` values from the jsonl when passed through the validator. Ideally I think it would be good to keep `None` values in the response where it shows you the row as it may be import to the user to know the difference between a key having a null value and the key not existing. However... 

With jsonl data it is valid to have missing keys for different lines. It is not ideal, but for treating it as tabular data it'd be rare to need to infer a difference between these two lines e.g. the below _should_ be equivalent (at least in my experience).

```jsonl
{"a": 1, "b": null}
{"a": 1}
```

So with the example I raised previously you can get the correct responses by just skipping the `missing-value` check (as the constraints check will pick up if a col is stated as being required and is missing.

e.g. (continuing on from the previous code example)

```
resp = validate(test_data, schema=schema, skip_checks=['missing-value']) # resp["valid"] = True

# This will still catch missing values if you set required to be true
schema['fields'][1]['constraints']['required': True]
resp = validate(test_data, schema=schema, skip_checks=['missing-value']) # resp["valid"] = False
# error message for row  'Column 2 is a required field, but row 2 has no value'
```

So it might just be that the structural check `missing-value` is not applicable for jsonl data. Which you can get around fairly easily. Not sure if it is still an issue (so happy to close or change the label to enhancement - if you agree) but there might be some stuff that needs to drop that check if the validator infers the datatype as jsonl / ndjson.

**Comment by roll** [comment]
Fixed in `frictionless-py`

```python
from pprint import pprint
from frictionless import validate

test_data = [
    {"employee_id": 660148, "employee_name": "Michael Roth"},
    {"employee_id": 157311, "employee_name": None},
]

schema = {
    "$schema": "https://frictionlessdata.io/schemas/table-schema.json",
    "fields": [
        {
            "name": "employee_id",
            "type": "integer",
            "format": "default",
            "constraints": {"required": True, "minimum": 100000, "maximum": 999999},
        },
        {
            "name": "employee_name",
            "type": "string",
            "format": "default",
            "constraints": {"required": False},
        },
    ],
    "missingValues": [],
}
report = validate(test_data, schema=schema)
pprint(report.valid) # True
```
