### ISSUE TITLE
Infer more datetime formats

### ISSUE THREAD

**Issue by cpina** [frictionlessdata/frictionless-py#394]
See the attached file (`create_datapackage_header.txt`)

`frictionless describe --json ~/Baixades/create_datapackage_header.csv` outputs:
```
    "fields": [
      {
        "name": "Datetime_UTC [YYYY-MM-DDTHH:MM:SS+00:00]",
        "type": "string"
      },
```

For strings like `2016-12-28T15:05:00+00:00` I would expect to recognise as a datetime.

[create_datapackage_header.txt](https://github.com/frictionlessdata/frictionless-py/files/5104725/create_datapackage_header.txt)

Version: 0.6.1

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
MERGED into vhttps://github.com/frictionlessdata/frictionless-py/issues/423

**Comment by roll** [comment]
Hi @cpina, I'm releasing `frictionless@3.17` that should solve this problem
