### ISSUE TITLE
Error message: "generator raised StopIteration" for a generated schema

### ISSUE THREAD

**Issue by cpina** [frictionlessdata/frictionless-py#395]
I'm following: https://github.com/frictionlessdata/frictionless-py/blob/master/docs/target/validating-data/README.md#validating-resource

Same file as the attached file (but named as .csv instead of .txt as Github doesn't support .csv files)

[create_datapackage_header.txt](https://github.com/frictionlessdata/frictionless-py/files/5104778/create_datapackage_header.txt)

I've done:
```
describe ~/Baixades/create_datapackage_header.csv --json > test.json
frictionless validate test.json 
[invalid] test.json

row    field    code          message
-----  -------  ------------  ----------------------------------------------------------------------------------------------
                source-error  The data source has not supported or has inconsistent contents: generator raised StopIteration
```

I expected validation errors or all good but not this error message.
frictionless version: 0.6.1

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi @cpina,

Could you please re-attach the file? It doesn't seem downloadable

**Comment by cpina** [comment]
Sadly I don't have this file any more (it was a temporary file when I was testing this). I'll try to find out where the original file came from and reproduce it again.

**Comment by roll** [comment]
@cpina 
Thanks. BTW if you just remember what special was about this file (shape/header/types/etc) I will probably be able to reproduce the error if it's not fixed yet

**Comment by roll** [comment]
@cpina 
The answer was really simple :smiley: 

```
$ frictionless validate test.json # tries to validate it as a JSON data table
$ frictionless validate test.resource.json # reads and validates as a resource descriptor
$ fircitonless validate test.json --source-type resource # force handle as a resource
```

I just had to update the tabular error:
```
$ frictionless validate test.json
[invalid] test.json

row    field    code          message
-----  -------  ------------  -----------------------------------------------------------------------------------------------------
                source-error  The data source has not supported or has inconsistent contents: cannot extract tabular data from JSON
```

**Comment by cpina** [comment]
Excellent, thanks! :+1:

**Comment by roll** [comment]
Maybe at some point we just need to start considering any `json` files as metadata but for now it looks for `*.package.json` and `*.resource.json`

**Comment by lwinfree** [comment]
@roll my opinion here is that we should consider any json file as metadata. I've found that people are confused about this.

**Comment by roll** [comment]
Thanks, @lwinfree, I agree - https://github.com/frictionlessdata/frictionless-py/issues/462 - current behavior is a mostly historical artifact of `tabulator`
