### ISSUE TITLE
Clearly communicate new package name to users and write a blog

### ISSUE THREAD

**Issue by chris48s** [frictionlessdata/frictionless-py#416]
# Overview

If I am a current user of goodtables the name change has not been communicated clearly.
If I have `goodtables==2.5.0` in my `requirements.txt` what happened? One day I just stopped getting updates..
If I look at https://pypi.org/project/goodtables/ there's nothing that tells me this is old/deprecated and I should use https://pypi.org/project/frictionless/ instead for my new project.

I appreciate we maybe aren't ready to do this just yet, but when we are, here's my suggestion: release one final goodtables release: `goodtables==2.5.1` with no functional changes but:

1. Include a single changelog entry explaining the name has changed + to upgrade, change your requirement to `frictionless==3.9.1`. Users who use dependabot/pyup/rennovate/etc will be able to see that changelog entry when their tool bumps them from 2.5.0 to 2.5.1
2. Add a note at the top of the README (or comepletely replace the README) so that if you view https://pypi.org/project/goodtables/ there is a clear notice saying "this is deprecated - go install https://pypi.org/project/frictionless/ instead"
3. When you import the goodtables module, issue a deprecation warning e.g:

```py
import warnings

warnings.warn('goodtables-py has been renamed to frictionless-py for more info see [bla]', DeprecationWarning)
```

This will help make it clearer to existing/potential users that the rename has taken place and if they want to use the package or continue receiving updates, they need to download frictionless or migrate to it.

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Thanks @chris48s, 

I'll add the note from https://github.com/frictionlessdata/frictionless-py#frictionless-for-python to `goodtables` branch/PyPi also.

Currently, we're not deprecating `goodtables` and `v2.x` will be updated (bug-fixes) for the foreseeable future as people migrating to `frictionless`. So it will be more gradual than your scenario. As the note says there are no actions required to current `goodtables` users.

Another problem, that any note in any place will be seen by very few real users. You usually don't go to your dependencies readmes very often. I think @lwinfree and I will release a blog post to communicate the change ATM.

When everything is settled down I see at some point in 2021 we will be ready to issue the deprecation warning for `goodtables` lib as you recommend in point 3 so everyone will get the message.

**Comment by roll** [comment]
I would preserve this issue till we have a blog post released cc @lwinfree

**Comment by roll** [comment]
DONE 

https://frictionlessdata.io/blog/2020/10/08/frictionless-framework/
