### ISSUE TITLE
Publish frictionless on conda-forge

### ISSUE THREAD

**Issue by suvayu** [frictionlessdata/frictionless-py#426]
Would be great if `frictionless` is available on `conda-forge`, `goodtables` already was.

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Thanks @suvayu,

We will add it to Anaconda soon

**Comment by roll** [comment]
It's been merged to Conda Forge - https://github.com/conda-forge/staged-recipes/pull/12731 - so it will be available soon

**Comment by suvayu** [comment]
Thanks!
