### ISSUE TITLE
[Q] Difference between `datapackage` and `frictionless`

### ISSUE THREAD

**Issue by suvayu** [frictionlessdata/frictionless-py#428]
I'm struggling a bit to understand the difference in functionality between the classes available from [`datapackage`](https://github.com/frictionlessdata/datapackage-py) (like `Package`, `Resource`, `Schema`, etc) as opposed to the newly added, identically named classes in this repo.  Is the `datapackage` library deprecated by `frictionless`?

I have quite some code that uses the classes from `datapackage`, should I be rewriting them to use the corresponding classes from `frictionless`?

Thanks for any clarification. 

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi @suvayu,

A quick answer - NO, you shouldn't rewrite it as `datapackage` is going to be maintained for the foreseeable future.

In general, `frictionless` is our new generation software while `tabulator/tableschema/datapackage/goodtables` is our previous generation software. Frictionless has a lot of improvements over them. 

For example, working with packages, following 2 snippets do an identical thing:

```python
# dataptackage
package = Pacakge({'resources': [{'name': 'table', 'path': 'table.csv'}])
package.descriptor.resources[0]['name'] = 'name'
package.commit()
print(package.descriptor)
```

```python
# frictionless
package = Package(resources=[Resource(name='table', path='table.csv')])
package.get_resource('table').name = 'name'
print(package)
```

So a slightly longer answer - if you have a chance, migrating to `frictionless` is something to consider now or in the near future.

**Comment by roll** [comment]
Please re-open if it didn't help :+1:

**Comment by suvayu** [comment]
Thanks, that's helpful.  I'll keep using the existing setup then.  But will plan to migrate to `frictionless` in the coming months.

Cheers,
