### ISSUE TITLE
Options to zip data package with remote/inline resources

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#439]
# Overview

For now only `local` resources will be zipped - https://github.com/frictionlessdata/datapackage-py/issues/18

Also see this issue - https://github.com/frictionlessdata/datapackage-py/issues/273 - we need to be able to stream to zip

**Comment by niconoe** [comment]
I'd be also very interested in this feature.

I'm using https://github.com/frictionlessdata/datapackage-pipelines-sql-driver to create a data pipeline where a data package is loaded to SQLite, transformed using into SQL and saved back as a data package with embedded CSV files. AFAIK, there's currently no easy way to perform this last step (get updated data from the database and save everything to a new fully-featured data package).
