### ISSUE TITLE
migrating from goodtables - varying headers

### ISSUE THREAD

**Issue by Thomas-Hirsch** [frictionlessdata/frictionless-py#449]
# Overview

We have developed a [package called `data_linter`](http://github.com/moj-analytical-services/data_linter) for validating data for pulling it into our systems. I'm seeking to migrate to `frictionless` for the performance benefits, but am having difficulty with dealing with headers, as the functionality changed in a fundamental way.

The important function is [here](https://github.com/moj-analytical-services/data_linter/blob/master/data_linter/validation.py#L247). A key issue in our use case is that our metadata schema requires the headings to be all lowercase, but the data can have upper case headers, or none at all. Hence we have a line in our function to specify the headers either as the headers sent to lowercase, or as the headers in the metadata where necessary, and then pass those to the `validate` function.

However, I realise the `validate` function's `headers` parameter doesn't work the same way any more, and is the source of the `dialect-error` reports I get when running the equivalent code. I've tried playing around with the dialects, but `Dialect(headers=False` doesn't work for my test CSV without headers, and `CsvDialect(case_sensitive_header)` doesn't help for non-case sensitive headers.

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi @Thomas-Hirsch, 

I would rewrite this function like this (showing in a very simplified form):

```python
def source():
    with Table(path) as table:
        # Copy and modify the headers as you need
        yield table.headers
        yield from table.data_stream

report = validate(source, schema=schema)
```

I think it can quick-fix your problem for now but also I'm going to work on https://github.com/frictionlessdata/frictionless-py/issues/381 this month

I'm closing in favor of #381. Let me know there if you have something else to add fo the feature
