### ISSUE TITLE
Add support for IBM DB2

### ISSUE THREAD

**Issue by bonaparte911** [frictionlessdata/frictionless-py#458]
Is there a possibility to include support for IBM DB2 databases via the [sqlalchemy interface](https://github.com/ibmdb/python-ibmdbsa/tree/master/ibm_db_sa)?

The connection scheme would be "db2+ibm_db" or "ibm_db_sa" (both work the same).

For now using

`with Table(
        'db2+ibm_db://username:password@host:port/database'
) as table:`

(with proper credentials) results in following error: 

`
...\lib\site-packages\frictionless\loader.py in read_byte_stream(self)
    114         except IOError as exception:
    115             error = errors.SchemeError(note=str(exception))
--> 116             raise exceptions.FrictionlessException(error)
    117         except config.COMPRESSION_EXCEPTIONS as exception:
    118             error = errors.CompressionError(note=str(exception))

FrictionlessException: [scheme-error] The data source could not be successfully loaded: [Errno 22] Invalid argument: 'db2+ibm_db://...'
`

Kind regards

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi @bona922,

Thanks, we will definitely be happy to implement it. 

As a workaround for now, can you please try something like:

```python
import sqlalchemy from sa
from frictionless import Resource

resource = Resource.from_sql(engine=sa.create_engine('db2+ibm_db://username:password@host:port/database'))
resource.read_rows() # or resource.to_table() etc
```

**Comment by roll** [comment]
There is a chance that it will also not work as we need to specify support for this database in the SQL plugin anyway. But please let me know

**Comment by bonaparte911** [comment]
Hi @roll,

unfortunately I was unable to utilise the workaround.

The error message is:

`   return storage.read_resource(name)
  File "c:\Users\...\lib\site-packages\frictionless\plugins\sql.py", line 196, in read_resource
    errors.StorageError(note=note))
frictionless.exceptions.FrictionlessException: [storage-error] The storage has an error: Resource "test" does not exist`

After that, I tried to unfold your code in the following way, where `conn_db2` is the connection based on SQLalchemy (working using just SQLalchemy routines):

`mystorage = system.create_storage("sql", engine=conn_db2)`

`sql_table = mystorage._SqlStorage__metadata.tables.get('test')`

For `mystorage._SqlStorage__metadata` I get: `MetaData(bind=<sqlalchemy.engine.base.Connection object at 0x0000020B18E28FC8>)` and `mystorage._SqlStorage__metadata.tables` is an `immutabledict({})`.

In contrast the working code with SQLalchemy:

`meta = sa.MetaData()`
`meta.reflect(bind=conn_db2, schema="MYSCHEMA")`
`sql_table = meta.tables.get('test')`

I suspect the reason in the needed `schema` argument for my database.

Kind regards

**Comment by roll** [comment]
Thanks, it seems the support needs to be added explicitly.

**Comment by roll** [comment]
Hi @bona922,

`frictionless@3.22` is being released with the support of DB2. There is a problem that we haven't set up Windows CI yet so we basically can't test it.

Could you please try and let me know:

```python
from frictionless.plugins.sql import SqlDialect

dialect = SqlDialect(table='your table', namespace='your SQL scheme')
with Table('db2+ibm_db://username:password@host:port/database', dialect=dialect ) as table:
    # ...
```

Please re-open if it doesn't work
