### ISSUE TITLE
Docstrings used by click for "--help" text are informative

### ISSUE THREAD

**Issue by khughitt** [frictionlessdata/frictionless-py#459]
# Overview

When running `frictionless` from the command-line, the automatically generated `--help` text based on function docstrings are not informative and result in confusing out, e.g.:

```
$frictionless --help
Usage: frictionless [OPTIONS] COMMAND [ARGS]...

  Main program

  API      | Usage -------- | -------- Public   | `$ frictionless`

Options:
  --version  Print version
  --help     Show this message and exit.

Commands:
  api        Start API API | Usage -------- | -------- Public | `$...
  describe   Describe data API | Usage -------- | -------- Public | `$...
  extract    Extract data API | Usage -------- | -------- Public | `$...
  transform  Transform data API | Usage -------- | -------- Public | `$...
  validate   Validate data API | Usage -------- | -------- Public | `$...
```

This appears to be due to the fact that click automatically generates the help text based on function docstrings which, at present, contain some descriptive API information about the functions, but not something useful / readily parsable by click.

**System Info**:

- Arch Linux 5.8.12 64-bit
- Python 3.8.5
- frictionless 3.17.0
- py-yaml 5.3.1

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Thanks

**Comment by roll** [comment]
The fix is being released. We're going to ship other improvements to the CLI soon - https://github.com/frictionlessdata/frictionless-py/issues/386
