### ISSUE TITLE
Integration with Zenodo as a data portal

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#484]
# Overview

```
# Read from datapackage file
package = Package("https://zenodo.org/record/6599273")

# Create package from present files
package = Package("https://zenodo.org/record/6835898")

# More requirements will be added
# ...
```

PS.
The implementation is already prototyped in v5 branch

**Comment by zaneselvans** [comment]
We've done a little bit of integration with Zenodo to archive our raw input files for PUDL [in this repository](https://github.com/catalyst-cooperative/pudl-zenodo-storage) but it would be **great** to have more generalized functionality.

**Comment by peterdesmet** [comment]
Yes please, would be awesome if the Zenodo deposit metadata editor had the option to read from an uploaded `datapackage.json` so that populating metadata could be done directly from the package metadata if one so chooses.

**Comment by peterdesmet** [comment]
For reference: here's a list of published data packages on Zenodo: https://zenodo.org/search?page=1&size=20&q=frictionlessdata&type=dataset Relevant metadata was copied manually.
