### ISSUE TITLE
conda-forge packaging still lists obsolete statistics package as a requirement

### ISSUE THREAD

**Issue by zaneselvans** [frictionlessdata/frictionless-py#491]
# Overview

It looks like the Python 2.x backport of the Python 3.4 `statistics` standard library has been removed from the frictionless requirements with the deprecation of Python 2, but it's still showing up in the `meta.yaml` recipe on conda-forge, and this unsatisfied ghost dependency is causing dependent packages to fail. See e.g. @ezwelty's [attempt to package goodtables-pandas-py](https://github.com/conda-forge/staged-recipes/pull/12946).

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi @zaneselvans,

Thanks, I've answered here - https://github.com/conda-forge/staged-recipes/pull/12946#issuecomment-714287138

I'm closing this issue for now as it seems we can't change for this project ATM as `goodtables` depends on this package in Python2 and we want to preserve `goodtables` branch not breaking.
