### ISSUE TITLE
numberish strings failing validation

### ISSUE THREAD

**Issue by Thomas-Hirsch** [frictionlessdata/frictionless-py#492]
Hopefully simple query: I have some csvs with columns where the values can be a mix of numeric and alphanumeric (for example, "000835", "z00382"), so in the schema they're defined as strings. With goodtables this was previously fine, but with frictionless, I now get the following error: `'incompatible type: type is '"string/default"`. It seems like it's falling afoul of Python's type coercion when seeing numberish strings. The message is also slightly unhelpful - it would be better to see something like "the schema was expecting a string, but the data is a number".

Is there something in the Formats to tell it to treat as strings even if they look numerical?

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi @Thomas-Hirsch,

Can you please share an example column like this? Or the whole script you're running.

**Comment by Thomas-Hirsch** [comment]
A cut of data looks like this:
```
row   code        my_column
110   357           000868
111   383           001112
112   373           000870
113   375           000003
114   358           000660
115   381           000000
116   368           000047
117   370           z00052
118   374           000921
119   379           000088
```
Code is integer, my_column should be a string, and is according to the raw database it's extracted from. Running `describe` on just this cut correctly identifies it as a string; however, running it on the whole table (which is 454 rows, 4 of which have nonnumeric characters) interprets it as an integer. 

Having dug through the Frictionless source code a bit, it looks like the type inferrer has a score-based "best guess" as to what the data type is. In this case I think the scoring is too confident in itself - if there's a nonnumeric character in a value, you'd expect the field to be a string, regardless of the rest of the values. Even if all the characters were numeric, `"000123"` is arguably different from `123`.

**Comment by roll** [comment]
Hi @Thomas-Hirsch 

You can adjust all the infer options - https://colab.research.google.com/drive/1eIq1ZTUntJplRxkGHxmqlxZ0zyXCm0wU#scrollTo=7M_-na--0c53

Type inferring is just heuristic so it's hard to say what default confidence is "right". My opinion that something like 3 of 100 cells having a different type will be a data error more often than something different. So the validation tool is better to notify a user about this anomaly and if it's expected the user can use the `infer_confidence` option to tweak the default behavior or update the schema using `patch_schema`.

I hope it's helpful for you. Please re-open if needed.
