### ISSUE TITLE
[goodtables] Hash and bytes validating incorrectly in zero length compressed resources

### ISSUE THREAD

**Issue by zaneselvans** [frictionlessdata/frictionless-py#495]
With `goodtables` 2.5.2 (not sure about subsequent versions) I'm finding that the `hash` and `bytes` values which are calculated for compressed resources during tabular data package validation are those of the **uncompressed** resource, when the resource has zero data rows (it's just a header row).

It seems like it's probably some weird edge case.  For resources containing data rows, it correctly (according to the [Note: in the compressed resources pattern](https://specs.frictionlessdata.io/patterns/#compression-of-resources)) calculates the file size and hash values based on the compressed file.

Not sure if it matters, but these resources are also part of a resource `group` -- and I wasn't really able to find any documentation of the data resource level `group` property in the frictionless specs, which seemed funny.

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by zaneselvans** [comment]
Installing `frictionless` 3.23.4 I get a different behavior, where instead it complains specifically about not finding any data in the resource. So, are tabular data resources required to have more than 0 rows of data?
```
[invalid] data/hourly_emissions_epacems_1995_id.csv.gz

row    field    code          message
-----  -------  ------------  -----------------------------------------------------------------------------------------------------------
                schema-error  The data source could not be successfully described by the invalid Table Schema: there is no data available

[invalid] data/hourly_emissions_epacems_1996_id.csv.gz

row    field    code          message
-----  -------  ------------  -----------------------------------------------------------------------------------------------------------
                schema-error  The data source could not be successfully described by the invalid Table Schema: there is no data available

```

**Comment by roll** [comment]
Thanks @zaneselvans, I'll investigate

**Comment by roll** [comment]
> With goodtables 2.5.2 (not sure about subsequent versions) I'm finding that the hash and bytes values which are calculated for compressed resources during tabular data package validation are those of the uncompressed resource, when the resource has zero data rows (it's just a header row).

> It seems like it's probably some weird edge case. For resources containing data rows, it correctly (according to the Note: in the compressed resources pattern) calculates the file size and hash values based on the compressed file.

In `goodtables` all bytes/hash calculations happen on decompressed data sources (I re-checked it for tables with rows). We weren't able to change it due to the complexity of underlying libraries and the way they work. Basically, it's one of many reasons, why we decided to start a brand-new Frictionless Framework not having all those legacy complications. So I'm marking it as `wontfix` for `goodtables` and it's "fixed" in Frictionless.

I'm going to investigate no data behaviorour Frictionless has just right now.

**Comment by roll** [comment]
WONTFIX [goodtables]
MOVED to https://github.com/frictionlessdata/frictionless-py/issues/533 [frictionless]
