### ISSUE TITLE
Resource.read_lookup() does not respect Resource.query

### ISSUE THREAD

**Issue by ezwelty** [frictionlessdata/frictionless-py#503]
# Overview

Related to my efforts to migrate https://github.com/ezwelty/goodtables-pandas-py from `goodtables` to `frictionless`, as discussed previously at https://github.com/conda-forge/staged-recipes/pull/12946.

My hope was to perform an initial validation with `validate` (metadata and header errors), check for content errors with `pandas`, and update the report as needed. This would allow me to most closely match the `frictionless.validate` API. However, even with `validate(query=Query(limit_rows=1))`, it is slow for large tables. Here is what I figured out:

- `validate_package()` calls `Resource.read_lookup()`, which is slow for large tables because it iterates over every row (of the reference table).
- `Resource.read_lookup()` returns all keys, regardless of `Resource.query`, because `Resource.to_table()` does not pass `Resource.query` to `Table.query`. If this is fixed, `validate_package()` could then set `Resource.query=options['query']` before calling `Resource.read_lookup()`. Alternatively, `Resource.read_lookup()` could take `query` as an option and `validate_package()` could call `Resource.read_lookup(query=options['query'])`. But not loading the full set of reference keys would lead to wrong foreign-key errors. So perhaps the right strategy here is for `Resource.read_lookup()` to be skipped if 'foreign-key-error' is not one of the error types to be checked (e.g. in `skip_errors`).
- The report `time` is wrong for tables, since it does not currently include the time taken to run `Resource.read_lookup()`.

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Thanks @ezwelty, 

I'll work on it. 

BTW have you tried lower-level APIs?

**Comment by ezwelty** [comment]
> I'll work on it.

Thanks!

> BTW have you tried lower-level APIs?

I have. The "small data sample" still takes about one second per table, which seems unfortunate since all I need is the header.

I noticed that setting `Resource.query` after initialization does not limit `Resource.read_header()` rows.

```python
resource = package.get_resource('resource')
resource.query = Query(limit_rows=1)
resource.read_header()
```

But setting `Resource.query` during initialization does:

```python
resource = Resource(path='table.csv', query=Query(limit_rows=1), trusted=True)
resource.read_header()
```

Using `Table(..., query=Query(limit_rows=1))` also works.

**Comment by roll** [comment]
Hi @ezwelty,

Here are two PRs to improve the situation:
- https://github.com/frictionlessdata/frictionless-py/pull/514 (fixing `resource.to_table`)
- https://github.com/frictionlessdata/frictionless-py/pull/515 (adding `validate_package(nolookup=True)`)

I hope it will help you to migrate. Feel free to open other issues you there is still something missing.

> I noticed that setting Resource.query after initialization does not limit Resource.read_header() rows.

It's intended as Query doesn't limit header rows and the row counting starts from the first data row.
