### ISSUE TITLE
How to use cli?

### ISSUE THREAD

**Issue by ppKrauss** [frictionlessdata/frictionless-py#504]
# Overview

I have good ODS  from [official Brazilians ibge.gov.br tables](https://www.ibge.gov.br/geociencias/organizacao-do-territorio/estrutura-territorial/23701-divisao-territorial-brasileira.html?=&t=downloads&utm_source=landing&utm_medium=explica&utm_campaign=codmun), and instlalled fresh frictionless-py by `pip3` with no errors  (installed also tabulator[ods] and was fine), all in Ubuntu 20 LTS. I try something to test installations:

* `tabulator /tmp/RELATORIO_DTB_BRASIL_MUNICIPIO.ods` fine, good and consistent CSV as result.
* `frictionless extract /tmp/RELATORIO_DTB_BRASIL_MUNICIPIO.ods | more`

## Need for help on error

Now, perhaps it is not a bug, seems that I try something that is wrong but `--help` and README say nothing:
* `frictionless extract --json /tmp/RELATORIO_DTB_BRASIL_MUNICIPIO.ods` = ERROR, <br/>*'str' object has no attribute 'year'*
* `frictionless describe /tmp/RELATORIO_DTB_BRASIL_MUNICIPIO.ods` = ERROR, <br/>*[resource-error] The data resource has an error: path "['/tmp/RELATORIO_DTB_BRASIL_MUNICIPIO.ods']" is not safe*
* ...

## Need for help on a complete task
And there are no clues about how to do basic tasks on terminal...  What I need, ideally by pipelining commands: 
1. read ODS file: seems ok to write it as CSV first, by `tabulator`, but it is possible by `frictionless`?
2. filter some coluns (not need all columns)
3. write a SQL dump, createing a table and inserting content (of item 2) into it. 

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Thanks @ppKrauss,

I'll investigate

**Comment by roll** [comment]
@ppKrauss 
For the second part of your question (filtering columns, writing to CSV/SQL etc) there is now Frictionless Transform - https://colab.research.google.com/drive/1C4dFWDExyxzGIwLUovrDQZghZK4JK2PD

It can look somewhat like this:

```python
from pprint import pprint
from frictionless import Resource, transform, steps

source = Resource(path="table.ods")
target = transform(
    source,
    steps=[
        steps.field_remove(names=["name1", "name2"]),
        steps.table_write('postgresql://database', dialect={'table': 'table_name'}) # or you can save to csv
    ],
)
```

I'm working on a fix for the error you mentioned before

**Comment by roll** [comment]
> frictionless extract --json /tmp/RELATORIO_DTB_BRASIL_MUNICIPIO.ods = ERROR,
'str' object has no attribute 'year'

> frictionless describe /tmp/RELATORIO_DTB_BRASIL_MUNICIPIO.ods = ERROR,
[resource-error] The data resource has an error: path "['/tmp/RELATORIO_DTB_BRASIL_MUNICIPIO.ods']" is not safe

These two are fixed and being released.

Also, Here https://github.com/frictionlessdata/frictionless-py/issues/386 I'm working on `frictionless extract --csv` option to provide a CSV output for the extract function for the CLI
