### ISSUE TITLE
Integration with Datahub

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#511]
# Overview

We'd like to be able to read and write from there.

**Comment by augusto-herrmann** [comment]
Does this mean integration with the original [DataHub.io](https://datahub.io/) (a data repository) or LinkedIn's [DataHub](https://datahubproject.io/) (a data management tool)?

**Comment by roll** [comment]
Hi @augusto-herrmann,

It's about https://datahub.io/ but I would close this issue as DataHub uses data packages as an interface so all the data can already be read from there (regarding writing - we're currently have CKAN, Zenodo, etc with higher priority - so not sure we need a dedicated writer to datahub)
