### ISSUE TITLE
Resource names coming from 'infer' should not retain uppercase characters

### ISSUE THREAD

**Issue by mwvaughn** [frictionlessdata/frictionless-py#531]
# Overview

In working on a dataset where some of the filenames contain uppercase characters, I see that those characters are retained in the resource names when one processes them with `infer`. 

For example, `RAW_input_stream_1.csv` will be given a resource name of `RAW_input_stream_1`. This violates the JSONschema, which allows only lowercase letters: `^([-a-z0-9._/])+$`

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi @mwvaughn,

Thanks for your input! 

Both issues are fixed and being released as `frictionless@3.34.1`
