### ISSUE TITLE
Failure to parse .ods file

### ISSUE THREAD

**Issue by kgeographer** [frictionlessdata/frictionless-py#539]
# Overview
When I run 

`validate_table('/some/path/myfile.ods, schema='myschema.json',skip_errors=['missing-cell'],sync_schema=True)` 

on a .ods spreadsheet I get the following result (partial), but `pip install frictionless[ods]` returns `no matches found` (python 3.7.4, frictionless 3.31.0)

```
{            'compression': 'no',
             'compressionPath': '',
             'dialect': {},
             'encoding': 'utf-8',
             'errors': [{'code': 'error',
                         'description': 'Error',
                         'message': 'Please install "frictionless[ods]"',
                         'name': 'Error',
                         'note': 'Please install "frictionless[ods]"',
                         'tags': []}],
             'format': 'ods',
             'hashing': 'md5',
             'partial': False,
             'path': '/some/path/myfile.ods',
             'query': {},
```

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi @kgeographer,

It's really weird as `pip install frictionless[ods]` works fine for me and on Travis CI.

It can be some weird connectivity/caching pip/PyPi problem may be, it's hard to say. To resolve the problem you can install `ezodf` directly `pip install ezodf`.
