### ISSUE TITLE
Extend syncing schema functionality

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#546]
# Overview

Initial thread - https://github.com/frictionlessdata/specs/issues/704#issuecomment-733171792

---

Probably we need another argument to achieve the behavior mentioned above but the requirements should be analyzed first.

**Comment by peterdesmet** [comment]
See also https://github.com/frictionlessdata/project/discussions/636#discussioncomment-1341223

**Comment by roll** [comment]
MERGED into #922
