### ISSUE TITLE
Improve error message and print the resource name

### ISSUE THREAD

**Issue by cpina** [frictionlessdata/frictionless-py#567]
# Overview

We were using frictionless-py and got this error:
```
============  =====================================================================================================
code          message                                                                                              
============  =====================================================================================================
source-error  The data source has not supported or has inconsistent contents: cannot extract tabular data from JSON
============  =====================================================================================================
```

It would have been easier for us to know which data resource is not supported or has inconsistent contents.

To reproduce: rename the attached files from .txt to .json and execute `frictionless validate datapackage.json` (this happened in a real datapackage, I've simplified this for this bug)
[datapackage.txt](https://github.com/frictionlessdata/frictionless-py/files/5630039/datapackage.txt)
[tableschema.txt](https://github.com/frictionlessdata/frictionless-py/files/5630041/tableschema.txt)

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Thanks, good catch
