### ISSUE TITLE
Integrate "Table Schema -> Excel Templates" library

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#584]
# Overview

There is a great library - https://github.com/hubmapconsortium/tableschema-to-template - to create Excel Templates from Table Schema. We can provide a convenient wrapper e.g. `schema.to_excel_template()`.

**Comment by ezwelty** [comment]
FYI, I wrote some Python software (https://gitlab.com/wgms/dbc) that includes functionality for generating spreadsheet templates (both Microsoft Excel and Google Sheets) from Frictionless Tabular Data Package metadata. Unlike https://github.com/hubmapconsortium/tableschema-to-template, it supports multiple tables, foreign keys, and more field constraints. I hope to find time to split out this functionality into a standalone package on GitHub/PyPi.

**Comment by lwinfree** [comment]
Very cool @ezwelty!!

**Comment by sapetti9** [comment]
Hi @ezwelty, this is very cool indeed! A lot of people in the community would be interested in knowing more about it. Would you be up to writing a tutorial about this and/or demo at one of our community calls later in the year? Drop me an email at sara.petti[at]okfn.org, or ping me in the community slack channel: https://frictionlessdata.slack.com/messages/general
