### ISSUE TITLE
Add field description for SQL resources

### ISSUE THREAD

**Issue by edgarrmondragon** [frictionlessdata/frictionless-py#595]
# Overview

Hello,

Currently (`3.46.0`) when reading a package or resource from a SQL storage, field descriptions are left empty even when columns have `COMMENT`.

```python
from pprint import pprint
from frictionless import Package

package = Package.from_sql(url='postgres://postgres@localhost:5432/postgres')
pprint(printpackage.get_resource('my_table').schema.fields[0])
# {'constraints': {'required': True},
#  'name': 'id',
#  'type': 'integer'}
```

Fixing this should be as simple as passing [`schema=column.comment`][1] when the field is created from a column:

https://github.com/frictionlessdata/frictionless-py/blob/0c3829eebc348acd9475e3553f38c3e1a835570e/frictionless/plugins/sql.py#L238

I can open a PR.

---

Please preserve this line to notify @roll (lead of this repository)

[1]: https://docs.sqlalchemy.org/en/14/core/metadata.html#sqlalchemy.schema.Column.params.comment

**Comment by roll** [comment]
Hi, thanks!

> I can open a PR.

It would be great. Can you please add a test? For testing you can use e.g. `sqlite_url` fixture
