### ISSUE TITLE
Allow path in contributors to be null

### ISSUE THREAD

**Issue by peterdesmet** [frictionlessdata/frictionless-py#596]
# Overview

- `contributors` in the package metadata MAY have a `path` attribute ([see specs](https://specs.frictionlessdata.io/data-package/#metadata)). Indeed, when this attribute is not listed (see Cookie Monster in example), it passes validation.
- However, if the `path` attribute is present with the `null` value (see Ernie in example), it results in an error message:

```
code           message
-------------  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------
package-error  The data package has an error: "None is not of type 'string'" at "contributors/1/path" in metadata and at "properties/contributors/items/properties/path/type" in profile
```

- I think the `null` value should not result in an error. Note that expected behaviour for the very similar property `organization`.

To repeat error, run `frictionless validate datapackage.json` on `datapackage.json` content below.

## datapackage.json

```
{
  "name": "period-table",
  "title": "Periodic Table",
  "profile": "tabular-data-package",
  "licenses": [{
    "id": "CC0-1.0",
    "title": "CC0 1.0",
    "url": "https://creativecommons.org/publicdomain/zero/1.0/"
  }],
  "contributors": [
    {
      "title": "Bert",
      "email": "bert@example.com",
      "path": "https://example.com",
      "role": "contributor",
      "organization": "Sesame street"
    },
    {
      "title": "Ernie",
      "email": "ernie@example.com",
      "path": null,
      "role": "contributor",
      "organization": null
    },
    {
      "title": "Cookie Monster",
      "email": "cm@example.com",
      "role": "contributor"
    }
  ],
  "resources": [{
    "path": "https://raw.githubusercontent.com/frictionlessdata/examples/master/periodic-table/data.csv",
    "name": "data",
    "profile": "tabular-data-resource",
    "format": "csv",
    "mediatype": "text/csv",
    "encoding": "UTF-8",
    "schema": {
      "fields": [{
          "name": "atomic number",
          "type": "integer",
          "format": "default"
        },
        {
          "name": "symbol",
          "type": "string",
          "format": "default"
        },
        {
          "name": "name",
          "type": "string",
          "format": "default"
        },
        {
          "name": "atomic mass",
          "type": "number",
          "format": "default"
        },
        {
          "name": "metal or nonmetal?",
          "type": "string",
          "format": "default"
        }
      ]
    }
  }]
}
```

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Thanks,

It must be a problem with the specs' JSONSchema. I'll check

**Comment by roll** [comment]
Hi @peterdesmet,

I think it's correct behavior based on the specs type system.

For example, this is also an invalid descriptor:

```python
from frictionless import Package

package = Package({"resources": [], "title": None})
assert not package.metadata_valid
```

A title can be omitted but if it's provided it has to be a string. The same for your `contributors.path` case.

Could you please open an issue here - https://github.com/frictionlessdata/specs/issues - if you think it should be changed in the specs (and this framework uses their JSON Schema for validation). But TBH I think the current type concept is the right approach.

**Comment by peterdesmet** [comment]
Just out of curiosity, why doesn’t `”organization": null` result in a similar error?

**Comment by roll** [comment]
I think there is a bug in JSON Schema - https://specs.frictionlessdata.io/schemas/data-package.json (organisation vs organization)

**Comment by roll** [comment]
@peterdesmet 
I've created a PR - https://github.com/frictionlessdata/specs/pull/716

**Comment by peterdesmet** [comment]
Excellent! Thanks.
