### ISSUE TITLE
Docs needs copy editing

### ISSUE THREAD

**Issue by loganbyers** [frictionlessdata/frictionless-py#597]
# Overview

I have noticed some typos and other grammatical issues with the docs. I can fix some of them in PR #598, but might not be able to review the python files and API reference fully.

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by lwinfree** [comment]
Hi @loganbyers thanks for this! We are aware that there are some typos, and are going to be working on fixing them in January. I'll check out your PR now, but I wanted to let you know that this is on our radar and will be fixed soon :-)

**Comment by loganbyers** [comment]
Thanks for looking at this so quickly. 

I don't know what the planned updates will cover, or what the normal processes look like, but I would be willing to provide similar assistance in copy editing / reviewing the content when it's available.

**Comment by lwinfree** [comment]
Thanks @loganbyers! We are going to be focusing on finalizing the docs in Jan-Feb-March, and part of that process will be getting feedback from users in paid feedback sessions (likely end of January). I'll be announcing those on our Discord channel (https://discord.com/invite/j9DNFNw) and it would be awesome to get your thoughts then.

**Comment by lwinfree** [comment]
Hi @loganbyers we're doing these feedback sessions soon. Here's more info (including a link to sign up if you are interested!): https://blog.okfn.org/2021/01/12/partnering-with-odi-to-improve-frictionless-data/

**Comment by loganbyers** [comment]
Thanks for the awareness, I signed up. Also want to say that I feel this type of engagement falls under the scope of work with my employer, so I will need to decline the personal payment for the feedback. Just getting that into the open... We are also a nonprofit, so I want to congratulate you on incentivizing user feedback on data tools!
