### ISSUE TITLE
rdfType no longer supported for table fields?

### ISSUE THREAD

**Issue by richardostler** [frictionlessdata/frictionless-py#599]
Hi, I'm trying out frictionless-py and encountering an AttributeError when I try to add an rdfType to a field:

`AttributeError: 'Field' object has no attribute 'rdfType'`

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi @richardostler,

Thanks, it's related to https://github.com/frictionlessdata/frictionless-py/issues/587

BTW, you can just set this property directly:

```python
field = Field()
field['rdfType'] = '<value>'
```

**Comment by roll** [comment]
I'm merging it with https://github.com/frictionlessdata/frictionless-py/issues/587. I'll add `field.rdf_type` property as a part of that issue
