### ISSUE TITLE
Underscores being replaced by dash in resource names

### ISSUE THREAD

**Issue by richardostler** [frictionlessdata/frictionless-py#600]
I've got resources (CSV files) with underscores in the names. When I use `describe_resource` on the resource any underscores in the original name for the CSV being unexpectedly replaced by dashes in the descriptor. I can see the below line in setup.py (line 21), but not sure if its the offending line:
`NAME = PACKAGE.replace("_", "-")`

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Thanks, I'll investigate
