### ISSUE TITLE
dialect/commentChar is not respected during extraction

### ISSUE THREAD

**Issue by ethho** [frictionlessdata/frictionless-py#610]
# Overview

In a Tabular Data Resource, [`dialect/commentChar`](https://specs.frictionlessdata.io/csv-dialect/#specification) is not respected when extracting from a CSV resource. Attempting to extract a Data Resource with a comment character raises the following error. The error is the same if `dialect` field is removed from `dataresource.json`.

```bash
$ frictionless validate dataresource.json
---
invalid: data.csv
---

===  =====  ==========  ===============================================================
row  field  code        message
===  =====  ==========  ===============================================================
  2      2  extra-cell  Row at position "2" has an extra value in field at position "2"
  3      2  extra-cell  Row at position "3" has an extra value in field at position "2"
  4      2  extra-cell  Row at position "4" has an extra value in field at position "2"
  5      2  extra-cell  Row at position "5" has an extra value in field at position "2"
===  =====  ==========  ===============================================================
```

# Details to Reproduce

```bash
$ tree .
.
├── data.csv
└── dataresource.json
```

`data.csv`:
```csv
# some metadata
user,balance
fred,0
george,100
bill,10
```

`dataresource.json`:
```json
{
    "name": "data",
    "path": "data.csv",
    "profile": "tabular-data-resource",
    "dialect": {
        "commentChar": "#"
    }
}
```

## Environment

```bash
$ frictionless --version
3.48.0
$ python --version
Python 3.8.3
$ echo $SHELL
/bin/zsh
```

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Thanks,

I'll investigate

**Comment by roll** [comment]
Hi @eho-tacc,

It's not supported ATM as there is a new `Table Dialect` proposal - https://github.com/frictionlessdata/specs/issues/697 - and probably a Table Query proposal is coming.

In Frictionless Framework, all data filtering (horizontal and vertical) can be done using Tabel Query:

```python
    path = "data/skip-rows.csv"
    query = Query(skip_rows=["#", 5])
    resource = Resource(path=path, query=query)
    assert resource.read_rows() == [
        {"id": 1, "name": "english"},
    ]
```

**Comment by roll** [comment]
https://frictionlessdata.io/tooling/python/extracting-data/#table-query
