### ISSUE TITLE
conflicting validation results between goodtables and frictionless for data package.json 

### ISSUE THREAD

**Issue by duncdrum** [frictionlessdata/frictionless-py#614]
# Overview

my `datapackage.json` validates fine with `goodtables v2`

```shell
goodtables validate csv/datapackage.json    

[…]

TABLE [3]
=========
{'datapackage': 'csv/datapackage.json',
 'encoding': 'no',
 'error-count': 0,
 'format': 'inline',
 'headers': ['agent_id',
             'old_id',
             'language',
             'commentary',
             'note',
             'created',
             'created_by',
             'last_modified',
             'last_modified_by'],
 'resource-name': 'agent',
 'row-count': 657,
 'schema': 'table-schema',
 'scheme': 'inline',
 'source': ~/Documents/gits/ReadAct/csv/data/Agent.csv',
 'time': 1.189,
 'valid': True}

[…]
```

 but frictionless complains:

```shell
frictionless validate csv/datapackage.json
---
invalid: csv/datapackage.json
---
=============  ==============================================================
code           message                                                       
=============  ==============================================================
package-error  The data package has an error: resource "Agent" does not exist
=============  ==============================================================
```
---

so the table and schema are very much there, and working.  

I can reproduce this on macOS `10.15.7` local and on ubuntu `20.04` on travis. 

[failed log run ci](https://travis-ci.com/github/readchina/ReadAct/builds/212367698)
[passing run ci](https://travis-ci.com/github/readchina/ReadAct/builds/212003349#L568)

[repo](https://github.com/readchina/ReadAct)

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Thanks, I'll investigate

**Comment by roll** [comment]
@duncdrum 
Goodtables doesn't validate foreign keys by default so it's the reason why the results differ.

Here - https://github.com/readchina/ReadAct/blob/master/csv/schema/Act.json#L143 -  the schema uses resource "Agent" for a foreign key although the resource is called "agent" (not capitalized). I think other references also need to be updated.

The error message is totally cryptic though so I'll include the fix to v4 which is going to be released soon

**Comment by duncdrum** [comment]
@roll great the improved error message would have made things a lot easier. thx
