### ISSUE TITLE
absent primaryKey column causes a task-error (using sync_schema=True)

### ISSUE THREAD

**Issue by pierredittgen** [frictionlessdata/frictionless-py#619]
# Overview

I use `sync_schema=True` option in `frictionless.validate_table()` to skip errors relative to missing or supernumerary columns in validation report. It's really convenient to use.

But I encountered a problem when the missing column is declared as `primaryKey` in the schema. E.g.
```python
import frictionless

schema = {
    "fields": [
        {"name": "country_code"},
        {"name": "country_name"},
        {"name": "currency"},
    ],
    "primaryKey": ["country_code"],
}

source = [["country_name", "currency"], ["USA", "US dollar"], ["Germany", "euro"]]

report = frictionless.validate_table(source, schema=schema, sync_schema=True)
```

Validation then reports a general `task-error` error where the missing field (`country_code`) is mixed in `message` and `note` properties:
```
{'errors': [{'code': 'task-error',
             'description': 'General task-level error.',
             'message': "The validation task has an error: 'Row does not have "
                        "a field country_code'",
             'name': 'Task Error',
             'note': "'Row does not have a field country_code'",
             'tags': ['#general']}],
 'stats': {'errors': 1, 'tables': 0},
 'tables': [],
 'time': 0.033,
 'valid': False,
 'version': '3.48.0'}
```

I'd really like to get either:
- no error
- a more meaningful error (`PrimaryKeyError`?) carrying missing field as a `fieldName` property

Would it be possible?

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi @pierredittgen,

I think it's been already fixed in preparation to `frictionless@4`:

```
{'errors': [{'code': 'schema-error',
             'description': 'Provided schema is not valid.',
             'message': 'The data source could not be successfully described '
                        'by the invalid Table Schema: primary key '
                        '"[\'country_code\']" does not match the fields '
                        '"[\'country_name\', \'currency\']"',
             'name': 'Schema Error',
             'note': 'primary key "[\'country_code\']" does not match the '
                     'fields "[\'country_name\', \'currency\']"',
             'tags': ['#table', '#schema']}],
 'stats': {'errors': 1, 'tasks': 0},
 'tasks': [],
 'time': 0.179,
 'valid': False,
 'version': '4.0.0a8'}
```

It's a schema error as schema validation doesn't pass because of incorrect primaryKey.

Do you think it's better to classify this error as `primary-key-error`?

**Comment by pierredittgen** [comment]
Thanks for this fix @roll

I agree, there's no need to create a new `primary-key-error` where a `schema-error` is good enough.

**Comment by roll** [comment]
Thanks!
