### ISSUE TITLE
Possibility of restricting the list of possible values ​​in an "array" type field 

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#627]
# Overview

There is an issue for the specs that can be supported in advance in Frictionless-py as it's blocking for french open data task force Etalab (cc @lwinfree)

https://github.com/frictionlessdata/specs/issues/712

**Comment by roll** [comment]
Prioritizing this one to unblock Etalab cc @lwinfree

**Comment by roll** [comment]
Hi @johanricher,

Could you please try with `frictionless@4.1`:

```python
from pprint import pprint
from frictionless import Resource, Schema, Field

field = Field(name="key", type="array", array_item={"constraints": {"enum": ["a", "b"]}})
resource = Resource([["key"], [["a"]], [["b"]], [["c"]]], schema=Schema(fields=[field]))
pprint(resource.read_rows())
```

**Comment by roll** [comment]
Here is details - https://github.com/frictionlessdata/specs/issues/409#issuecomment-623423909

**Comment by geoffreyaldebert** [comment]
Hello @roll
First of all, thanks for your answer and proposition. Indeed, the solution works on python.

But the command line does not seems to work properly when we try to validate a file.

Example of schema :

```
...
   "fields":[
      {
         "name":"array_field",
         "title":"Array field",
         "description":"Array field description",
         "type":"array",
         "example":"",
         "array_item":{
            "constraints": {
               "enum": ["a", "b"]
            }
         }
      }
   ]
...
```

Example of csv file : 

```
array_field
"[""a""]"
"[""a"",""b""]"
"[""a"",""b"",""c""]"
"[""c""]"
```

Value `c` is not in the enum list however when I execute `frictionless validate --schema schema.json exemple-valide.csv` the output message does not mention any error : 
![image](https://user-images.githubusercontent.com/3721168/110963323-371aeb00-8352-11eb-8ba4-ebfa93406029.png)

You have the repo for test here : https://github.com/geoffreyaldebert/schema-test

Any idea why this is working on python but not with CLI ?

Thanks for your help !

Geoffrey

cc @johanricher

**Comment by geoffreyaldebert** [comment]
@roll sorry for my latest message, I found the answer.

Property `array_item` was not good (it was `arrayItem`). With this new implementation, it works fine.

Thanks you can keep this issue closed !

cc @johanricher

**Comment by johanricher** [comment]
Great news @geoffreyaldebert! Thank you so much @roll, we really appreciate it. :+1:

**Comment by roll** [comment]
Great! Thanks. 

Please create an issue if you run into any troubles using it
