### ISSUE TITLE
Create a showcase notebook on Google Colab

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#631]
# Overview

Get some real-world example and solve it using Frictionless aka what Frictionless can do (based on @amercader suggestion)

# Tasks

- [ ] add notebooks section to nav?
- [ ] add videos section not nav?

**Comment by lwinfree** [comment]
this is a great idea & can be one of the tutorials we work on in a few weeks

**Comment by danalclop** [comment]
Hi folks! I saw this issue and it got my attention, can I give you a hand with this? I really enjoy writing tutorials and explanations for a general audience.

**Comment by roll** [comment]
Hi @danalclop,

Sure. ATM we're working on the documentation and the plan is to make it comprehensive conceptually and providing tutorials and references for more isolated use cases. What we're looking at with the notebooks is describing some cool cases that show different aspects of Frictionless Framework.

I'm going to write one showing e.g. how we can take sports teams and players validate relations using foreign keys, extract and inspect remote data, join or aggregate (avg points e.g.) something using transform, and upload as a ckan dataset. Just off the top of my mind. 

Currently, we use https://colab.research.google.com/ for writing notebooks but I wouldn't say that it's a requirement. We're going to link those notebooks from the docs site so other platforms will work either.

**Comment by roll** [comment]
DONE https://colab.research.google.com/drive/1x5tbNm-i_kbCnBbK42GD1ogDcHTCAAbj
