### ISSUE TITLE
getting-started webpage is not reachable

### ISSUE THREAD

**Issue by aborruso** [frictionlessdata/frictionless-py#632]
Hi,
if I open https://docs.frictionlessdata.io/guides/getting-started I have 404.

Thank you

**Comment by lwinfree** [comment]
Hi @aborruso! We are updating the docs right now, so they can currently be seen here: https://frictionlessdata.io/tooling/python/getting-started/

Can you please let me know if you were following a link to https://docs.frictionlessdata.io/guides/getting-started and I can look into getting it rerouted. Thanks!

**Comment by aborruso** [comment]
@lwinfree I wanted to continue my study and could not find the guide.
Now I can continue, thanks
