### ISSUE TITLE
Introduction guide: Transforming Data and cli

### ISSUE THREAD

**Issue by aborruso** [frictionlessdata/frictionless-py#633]
Hi,
in the [transforming data section](https://github.com/frictionlessdata/frictionless-py/blob/master/docs/guides/introduction-guide.md#transforming-data) there is the update of the metadata file, using python:

```python
from frictionless import Resource, describe

source = Resource("tmp/countries.resource.yaml")
target = describe("tmp/countries-cleaned.csv")
target.schema.foreign_keys = source.schema.foreign_keys
target.to_yaml("tmp/countries-cleaned.resource.yaml")
```

What's the cli way to create `countries-cleaned.resource.yaml` file?

I have tried using the below command but it's wrong

```
frictionless describe tmp/countries-cleaned.csv --scheme tmp/countries.resource.yaml
```

The error is 

```
[scheme-error] The data source could not be successfully loaded: cannot create loader "tmp/countries.resource.yaml". Try installing "frictionless-data/countries.resource.yaml"
```

Thank you

**Comment by roll** [comment]
For now, transforms cant be done on CL.

We're working on the ability to run transform pipelines on the CLI (it's experimental now) although it anyway will require some non-CLI actions like editing the pipeline metadata in a text editor

**Comment by aborruso** [comment]
@roll I had a problem related to #644 

Using only the cli, then I need to run

```
frictionless describe tmp/countries-cleaned.csv --yaml >tmp/countries.resource.yaml
```

then I can edit this yaml manually in a text editor, and then I can run 
```
frictionless extract tmp/countries.resource.yaml --basepath .
```

Am I right?

**Comment by roll** [comment]
@aborruso 
Yes :+1:
