### ISSUE TITLE
Remove command-prompt from documentation examples

### ISSUE THREAD

**Issue by thill-odi** [frictionlessdata/frictionless-py#636]
# Overview

This is a minor annoyance, but ... while it's great to provide the option to copy code snippets in the [documentation interface](https://framework.frictionlessdata.io/docs/guides/introduction-guide), it's annoying to use this with the command-line, as the 'copy' command also copies the command-prompt '$' sign. The result is that copying the suggested command into the CLI and then hitting enter generates an error.

The fix would be to remove the preceding '$' sign from all copyable contexts.

---

**Comment by roll** [comment]
Thanks,

We need to think if it's possible to remove the sign during the copying or completely as I think for some people command-line indicator is favorable for code snippet understanding.

**Comment by chris48s** [comment]
Not sure if this is possible with the markdown to HTML process, but a really nice solution would be if we could add the $ using a CSS `::before` in the rendered docs for certain blocks (e.g: `<code class="terminal">`)

Then it would be visible, but it wouldn't select when you copy it. E.g:

```html
<style>
.terminal::before {
  content: "$ ";
}
</style>

<!-- no leading $ -->
Do thing with code:
<pre><code>import frictionless

frictionless.do_thing('foobar.csv')</code></pre>

<!-- leading $ -->
Do thing in the terminal:
<pre><code class="terminal">frictionless do-thing foobar.csv</code></pre>
```

**Comment by fjuniorr** [comment]
From my experience begginers tend to have difficulty with _where_ they should type things (eg. terminal vs python console)  and _what_ they should type (ie. should I type the `$` or not). Therefore the copy and paste error can be indeed very confusing _and_ is important to signal where they should type things.

One idea to make the distinction even clearer, apart from the prompt sign, would be to add something like what [Software Carpentry](https://software-carpentry.org/about/) uses in their [lessons](https://github.com/swcarpentry/python-novice-inflammation/blob/gh-pages/_episodes/12-cmdline.md) (with a  )

![Command-Line_Programs_–_Programming_with_Python](https://user-images.githubusercontent.com/4969445/105861641-b3898280-5fcd-11eb-8a98-1bd066973f99.png)

**Comment by roll** [comment]
Can an exclamation point be used instead of `$`? 

It's a Jupiter notebook-style notation and it seems to be working in shells as it is.

```bash
! pip install frictionless
```

WDYT?

**Comment by lwinfree** [comment]
+1 to all these! I most like @chris48s's solution (if it works!)

**Comment by fjuniorr** [comment]
@roll I'm not a big fan of the exclamation point because I think it's not that widespread. 

I've seen it before in some of the [docs](https://github.com/frictionlessdata/frictionless-py/blob/9ac7779480c12cd340741b80cf044246ecca9e7e/docs/guides/extracting-data.md) but I never typed because I didn't knew that it did :joy:.

**Comment by roll** [comment]
Thanks @fjuniorr 

I think some js/css magic on displaying on clicking on the Copy button will be the best option then. Also, we need to highlight the type of the snippet as you suggested

**Comment by roll** [comment]
@chris48s 
I didn't find how to hook into the "Copy" button action so went with your solution. Works great!
