### ISSUE TITLE
report stats "rows" property not found

### ISSUE THREAD

**Issue by pierredittgen** [frictionlessdata/frictionless-py#642]
# Overview

I'm migrating from frictionless-py 3.48.0 to 4.0.0a10 and I can't find stats `rows` property in validation report anymore. Has it be removed or can I still use this metrics in another form?

Thx.

### Using frictionless-py `3.48.0` 

```python
validation_report = validate_table(...)
print(validation_report["tables"][0]["stats"]["rows"])
```

ok

### Using frictionless-py  `4.0.0a10` 

```python
validation_report = validate_resource(...)
print(validation_report["tasks"][0]["stats"]["rows"])
```

KeyError: 'rows'

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi @pierredittgen,

V4 is about to be released but not yet fully documented. I'm going to create a migration document soon. In this version validation report just incapsulates resources so it will be:

```python
from frictionless import validate


report = validate("data/table.csv")
print(report["tasks"][0]["resource"]) # full resource's metadata
print(report["tasks"][0]["resource"]["stats"]["rows"])
# OR if you have only one resource
print(report.task.resource.stats["rows"])
```

**Comment by pierredittgen** [comment]
Thanks @roll
