### ISSUE TITLE
How to install v4.0.0a10 version

### ISSUE THREAD

**Issue by aborruso** [frictionlessdata/frictionless-py#643]
Hi,
after running `pip3 install --upgrade frictionless`, I have always `3.48.0` version.

But I read that the latest version is `4.0.0a10`. How to install it?

Thank you

**Comment by chris48s** [comment]
Hello. `3.48.0` is the latest stable version. `4.0.0a10` is a pre-release. By default, pip only finds stable versions. You'll need to `pip install` with the `--pre` flag if you want `4.0.0a10`.

**Comment by aborruso** [comment]
Thank you
