### ISSUE TITLE
Gaps in documentation of migration process from goodtables

### ISSUE THREAD

**Issue by mccalluc** [frictionlessdata/frictionless-py#651]
# Overview

Migrating from goodtables to frictionless has been a bit harder than it needed to be because of gaps in the documentation. Just some little things:

- Starting from https://pypi.org/project/goodtables/, the link to "Migration Guide" is broken: it is [this](https://github.com/frictionlessdata/frictionless-py/blob/master/docs/target/migration-guide/README.md) but it should be [this](https://github.com/frictionlessdata/frictionless-py/blob/master/docs/guides/migration-guide.md#from-goodtables) ... consider pushing a last update to pypi to update the link?
- On the [migration guide](https://github.com/frictionlessdata/frictionless-py/blob/master/docs/guides/migration-guide.md#validate) it does not mention that the `delimiter` kwarg is no longer valid.
- On frictionlessdata.io, the site search can not be used to find docs for `validate_table` (Added note to [an existing issue](https://github.com/frictionlessdata/project/issues/566).)
- Once on the docs for [`validate_table`](https://frictionlessdata.io/tooling/python/validating-data/#table), for further details I am directed to “Extracting Data”: Plain text could be replaced with link to https://frictionlessdata.io/tooling/python/extracting-data/.

Once on that page, I can scroll down to find https://frictionlessdata.io/tooling/python/extracting-data/#table-dialect, and I think this is what I need. Thanks!

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Thanks @mccalluc,

We will fix it

**Comment by roll** [comment]
Hi @mccalluc,

We created a proper documentation portal. The function you were looking for - https://framework.frictionlessdata.io/docs/references/api-reference/#validate_resource (`Table/Resource` was merged)

---

https://pypi.org/project/goodtables/ is fixed now
