### ISSUE TITLE
RFE: Allow a proxy server to be used for downloading files

### ISSUE THREAD

**Issue by ThrawnCA** [frictionlessdata/frictionless-py#656]
# Overview

When calling `validate()`, it should be possible to define a proxy server for downloading the file.

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi,

Could you please try:

```python
from frictionless import validate
from frictionless.plugins.remote import RemoteControl

control = RemoteControl(http_session=<requests.Session>)
report = validate(URL, control=control)
```

My guess that it should be possible configuring `requests.Session`

**Comment by ThrawnCA** [comment]
Ah, that does look promising; thanks. Is there any version of frictionless that has RemoteControl and supports Python 2?

**Comment by roll** [comment]
It's possible to do the same with `goodtables` (`goodtables` supports Python 2 while `frictionless` is written for Python 3 only):

```python
from goodtables import validate

http_session=<requests.Session>
report = validate(URL, http_session=http_session)
```

**Comment by ThrawnCA** [comment]
Perfect :). Thanks for that.

I'm opening a pull request to let our `ckanext-validation` fork make use of this feature. Would you like me to assemble a pull request for upstream?

**Comment by roll** [comment]
Thanks, it would be great cc @amercader
