### ISSUE TITLE
Describe doc questions/suggestions 

### ISSUE THREAD

**Issue by hbruch** [frictionlessdata/frictionless-py#680]
As I'm just skimming through the describe guide, I note the questions and gotchas here:
* The examples show how to create the metadata file programmatically. May I just pipe the CLI output to a file as well? (question was asked on slack as well). Apparently not, running `frictionless describe my_dataset.csv --type package > datapackage.yaml`  and afterwards `frictionless extract datapackage.yaml` resulted in 
```
[package-error] The data package has an error: cannot extract metadata "datapackage.yaml" because "expected a single document in the stream
  in "<file>", line 2, column 1
but found another document
  in "<file>", line 3, column 1"
  ```
After I removed the first three lines, extract worked. Perhaps the first three line do more harm than good and should not be generated, or should datapackage.yaml parser tolerate and ignore such a comment header(?)
* Are there any naming conventions for the metadata files? I thought a datapackage file should by convention be named datapackage.[json|yaml], but the examples use country.package.yaml(?)
* Via `frictionless describe --help` I figured out that I can generate the metadata as json files as well. Though a tutorial can not and should not describe every option, perhaps an additional hint e.g. that `--help` reveals many other options like rendering as json via the `--json` flag, would invite beginners to dig a bit deeper here...
---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Thanks I've created an issue regarding frontmatter - https://github.com/frictionlessdata/frictionless-py/issues/683

**Comment by hbruch** [comment]
I just continue here with my questions regarding describe.

After reading describe-doc, I wonder how nullable fields are returned by describe. The guide does not mention this case. Running describe on a dataset with columns containing null values, it looks to me as this results in a type "any", and hence loosing all type information. Am I missing something? I'd expect describe to guess about required=true/false. 

Probably related: to figure out field types etc, describe will inspect a certain number of rows, I guess. `frictionless describe --help` lists an `--limit-rows` argument which I set sufficiently large to include all rows of my dataset, but nevertheless columns containing at least one string were described as fields with `type: any`. Am I missing something here? I suggest to explain the inner workings of describe, so results of metadata inference can be influenced. Or perhaps there is a more detailed documentation for describe I am missing?

**Comment by roll** [comment]
Hi @hbruch,

Here is a missing values example;

```csv
id,name
1,one
na1,two
na2,free
4,four
```

```bash
$ frictionless describe tmp/missing.csv --field-missing-values na1,na2
---
metadata: tmp/missing.csv
---

encoding: utf-8
format: csv
hashing: md5
name: missing
path: tmp/missing.csv
profile: tabular-data-resource
schema:
  fields:
    - name: id
      type: integer
    - name: name
      type: string
  missingValues:
    - na1
    - na2
scheme: file
```

**Comment by roll** [comment]
And to change the sample size:

```bash
$ frictionless describe data/table.csv --sample-size 10000 # defaults to 100
```

**Comment by roll** [comment]
I think we need to add it to the guide cc @lwinfree

**Comment by roll** [comment]
I'll add it today  :+1:

**Comment by hbruch** [comment]
Meanwhile I saw that there is a (still empty) [detector-guide](https://github.com/frictionlessdata/frictionless-py/blob/master/docs/guides/detector-guide.md) page, which might be a good place for a more in depth description of the parameters and which could be linked from the describe doc.

**Comment by roll** [comment]
Thanks @hbruch,

The guide is done now - https://framework.frictionlessdata.io/docs/guides/detector-guide/

I've added a link from the Describe. Although we might need something more prominent cc @lwinfree

**Comment by roll** [comment]
Updated link - https://framework.frictionlessdata.io/docs/guides/framework/detector-guide
