### ISSUE TITLE
Consider remove frontmatter from default CLI output

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#683]
# Overview

It seems to be more confusing than helpful. On the other hand, it creates some visual focus and separation:

![2](https://user-images.githubusercontent.com/557395/107607799-4f142780-6c4b-11eb-9b1f-a005186f1313.png)

![1](https://user-images.githubusercontent.com/557395/107607801-520f1800-6c4b-11eb-8fe3-650ba9588e30.png)

**Comment by lwinfree** [comment]
Could it be an option to include it? Like a flag for more info?

**Comment by hbruch** [comment]
Another approach could be to use  yaml comments (#). Not sure if the header is expected by some functionality(?)

(Edit) Ah, wasn't aware of frontmatter syntax. Prefixing with hashes is not an option then. Should the yaml parser ignore frontmatter sections?

**Comment by chris48s** [comment]
> Could it be an option to include it? Like a flag for more info?

This is normally called `-v`/`--verbose`

Another option: If this is useful for humans but we don't want it when piping, you can use `isatty()` to work out if the session is interactive or not and output it (or not) based on that

**Comment by roll** [comment]
@hbruch 
Wow I think `#` can be quite an eloquent solution

@lwinfree 
@chris48s 
I think the main problem that current behavior is already quite standard:

```bash
$ frictionless describe # user-friendly
$ frictionless describe --yaml # machine-friendly
$ frictionless describe --json # machine-friendly
```
We use user-friendly default and provide options to export in other formats.

BUT

The default is too similar to YAML and it's confusing. I would give the '#' solution a try
