### ISSUE TITLE
Validation for URI too limited?

### ISSUE THREAD

**Issue by karlcz** [frictionlessdata/frictionless-py#695]
# Overview

If I am not mistaken, it seems that resource validation expects a column of type "string" with format "uri" to actually satisfy `validators.url` which appears to use a naive pattern requiring an HTTP or FTP URL and rejecting all other valid URIs.

However, my understanding of web standards is that the class of URI includes URNs which can have different schemes and may not have an internet address (i.e. the "authority" part of an HTTP URI).  The `validators.url()` test will reject a DOI.

Is this expected behavior, or would you agree it is a bug?  If not, how can we suppress this overly strict validation test when using `frictionless.validate_package()`?

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi,

Thanks I think it's a bug if it contradicts to the specs

**Comment by karlcz** [comment]
FWIW, my colleague indicates that the older frictionless tableschema package seemed to use a more appropriate URI validator for this case...
