### ISSUE TITLE
"Email protection" obscures Frictionless@4 in documentation

### ISSUE THREAD

**Issue by tripleee** [frictionlessdata/frictionless-py#697]
# Overview

The welcome page has this banner at the top

> [email protected] is now live! Please read the migration guide

where [email protected] is a link to information about email protection.

Apparently this is meant to show as 

> Frictionless@4 is now live! Please read the migration guide

There are similar problems across the documentation.

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi,

Thanks but I can't reproduce it:

> https://framework.frictionlessdata.io/docs/guides/introduction

![fd](https://user-images.githubusercontent.com/557395/108201441-dfada480-7130-11eb-84e4-66c50a8eaace.png)

Or it's a wrong page?

**Comment by tripleee** [comment]
Sorry, looks like this is a combination of NoScript and Cloudflare and nothing you can do anything about. The linked page https://framework.frictionlessdata.io/cdn-cgi/l/email-protection explains that this might happen if you have JavaScript disabled, which indeed I do. If I allow JavaScript for frictionlessdata.io it displays fine.
