### ISSUE TITLE
ImportError: cannot import name 'Table' from 'frictionless'

### ISSUE THREAD

**Issue by fardokhtsadat** [frictionlessdata/frictionless-py#701]
Hello,

I am using frictionless version 4.0.3 with python 3.8, and I cannot import Table from frictionless. I get the following error:

ImportError: cannot import name 'Table' from 'frictionless' (/home/PycharmProjects/project/venv/lib/python3.8/site-packages/frictionless/__init__.py)

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi @fardokhtsadat 

The Table class was merged with the Resource class in v4 - https://framework.frictionlessdata.io/docs/development/migration#from-frictionless3

**Comment by roll** [comment]
Please re-open if needed :+1:
