### ISSUE TITLE
docs homepage: replace images

### ISSUE THREAD

**Issue by lwinfree** [frictionlessdata/frictionless-py#716]
As noted by Adria, the images on the homepage have the shutterstock logo on them https://framework.frictionlessdata.io/

(@roll)

**Comment by roll** [comment]
Yes, that's from a prototype cc Sara

**Comment by roll** [comment]
Also, we might need transparent ones because of the night mode:

![ff](https://user-images.githubusercontent.com/557395/109465453-427c3580-7a79-11eb-9d46-7559223be0d9.png)

Though, I'm not sure what's the best

**Comment by roll** [comment]
cc @sapetti9

**Comment by roll** [comment]
DONE
