### ISSUE TITLE
Extracting data from ODS does not work

### ISSUE THREAD

**Issue by sirex** [frictionlessdata/frictionless-py#720]
# Overview

```
$ pipx install "frictionless[ods]"
  installed package frictionless 4.0.5, Python 3.9.1

$ frictionless extract data.ods
[general-error] General error: Please install "frictionless[ods]"
```

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Thanks for reporting! 

`ezodf` somehow doesn't include `lxml` in its dependency list. I'm releasing the fix
