### ISSUE TITLE
Multiple namespaces in the same package leads to 'Resource "xxx" does not exist' error

### ISSUE THREAD

**Issue by rbngz** [frictionlessdata/frictionless-py#749]
# Overview

We are confronted with the following error when trying to retrieve a package object from an SQL storage:

`frictionless.exceptions.FrictionlessException: [storage-error] The storage has an error: Resource "xxx" does not exist`

The issue is not that the resource does not exist, but the frictionless code appends the name of the resource to the namespace before referencing the resource in the the sql storage. (E.g., 'namespace.xxx')

See line 328 in frictionless-py/frictionless/plugins/sql.py

`sql_name = ".".join((self.__namespace, sql_name))`

We are using a DB2 database where one table contains foreign key references to another area of the DB where another namespace is used. The desired result should be a package with resources having multiple namespaces.

I have already tried to correct the problem in the PR #732 
This works in our case, but I am struggling to pass all the required tests. I am hoping somebody would be able to help us with correcting this issue.

Thanks!

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by rbngz** [comment]
#732

**Comment by roll** [comment]
Hi @rbngz,

The resource's name property doesn't cover different database schemes routing but you can use [SQL Dialect](https://framework.frictionlessdata.io/docs/references/formats-reference#sql):

```python
from frictionless import Package, Resource

path = "postgresql://localhost/movies"
package = Package(
    resources=[
        Resource(
            path=path,
            name="countries",
            format="sql",
            dialect={"table": "countries", "namespace": "public"},
        ),
        Resource(
            path=path,
            name="years",
            format="sql",
            dialect={"table": "years", "namespace": "special"},
        ),
    ]
)
print(package.get_resource("countries").read_rows(size=1))
print(package.get_resource("years").read_rows(size=1))
```

**Comment by roll** [comment]
Please re-open if it didn't help in your use case
