### ISSUE TITLE
I'm having some trouble validating a package with primary/foreign key relations -  I get the following:

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#755]
I'm having some trouble validating a package with primary/foreign key relations -  I get the following:
```
{
    "version": "4.1.0",
    "time": 0.036,
    "errors": [
        {
            "code": "task-error",
            "name": "Task Error",
            "tags": [],
            "note": "'str' object has no attribute 'keys'",
            "message": "The task has an error: 'str' object has no attribute 'keys'",
            "description": "General task-level error."
        }
    ],
    "tasks": [],
    "stats": {
        "errors": 1,
        "tasks": 0
    },
    "valid": false
}
```
Primary keys and foreign keys seem to be defined ok and I'm at a loss to know what this error means.

The package follows a basic star schema and if I remove the  FK relations on the main data table resource the package validates fine. I've copied the FK definition which appears at the end of the table resource (I've tried the fields both with and without an array - the documentation is a bit confusing, but the result re the error is the same):
```
"foreignKeys": [
          {
            "fields": [
              "crop_type"
            ],
            "reference": {
              "resource": "crop_types_data",
              "fields": [
                "crop_name"
              ]
            }
          },
          {
            "fields": [
              "liming_factor_level"
            ],
            "reference": {
              "resource": "liming_factor_data",
              "fields": [
                "factor_level_name"
              ]
            }
          },
          {
            "fields": [
              "p_factor_level"
            ],
            "reference": {
              "resource": "p_factor_data",
              "fields": [
                "factor_level_name"
              ]
            }
          },
          {
            "fields": [
              "k_factor_level"
            ],
            "reference": {
              "resource": "k_factor_data",
              "fields": [
                "factor_level_name"
              ]
            }
          }
        ]
```

Any idea why this is happening?

_Originally posted by @sapetti9 in https://github.com/frictionlessdata/project/discussions/623_

**Comment by richardostler** [comment]
Hi @roll I've attached the complete JSON, let me know if you need more
[01-RothLTliming-grain.json.txt](https://github.com/frictionlessdata/frictionless-py/files/6182708/01-RothLTliming-grain.json.txt)

**Comment by roll** [comment]
@richardostler can you please also share some CSV excerpts or dummy files?

**Comment by richardostler** [comment]
@roll I've attached the main data file and a couple of related files - its just a subset of the data as this is to accompany a journal article which hasn't yet been published.

[crop_types_data.csv.txt](https://github.com/frictionlessdata/frictionless-py/files/6182825/crop_types_data.csv.txt)
[grain_data.csv.txt](https://github.com/frictionlessdata/frictionless-py/files/6182826/grain_data.csv.txt)
[mn_factor_data.csv.txt](https://github.com/frictionlessdata/frictionless-py/files/6182827/mn_factor_data.csv.txt)

**Comment by roll** [comment]
Hi @richardostler,

The error wasn't helpful enough but the problem that you use:

```
"constraints": "1978 and 1995 only"
``` 

while it's a part of the Table Schema spec and needs to be a mapping.

**Comment by roll** [comment]
I've improved the error message in `frictionless@4.2.1`
