### ISSUE TITLE
Support an ability of string fields to be a PK in MySQL/DB2/etc 

### ISSUE THREAD

**Issue by rbngz** [frictionlessdata/frictionless-py#777]
# Overview

When a field in the schema is indicated as of type 'string', the __write_convert_type() function of the sql plugin will map the type to the sa.Text type similar as if no explicit type is mentioned for a field. In the created SQL statement this will result in a column of type CLOB which cannot be used as primary key. 
Would it make sense to replace the line 483 and map the value to a sa.String type when explicitly marked as of type 'string'? This would then use the more common VARCHAR type within the SQL statement.

Or is there maybe an option to override the mapping? Please let me know if I missed something :)

https://github.com/frictionlessdata/frictionless-py/blob/eb3f83b5d39514ffc352844fadf5101fa9e58b40/frictionless/plugins/sql.py#L475-L486

@roll

**Comment by roll** [comment]
Thanks @rbngz 

I'll investigate

**Comment by roll** [comment]
@rbngz 
For a general case, switching to `VARCHAR` is not possible as we don't know the width beforehand. Also, `TEXT` works fine as PK for Postgres and I guess for other databases. You use db2 right?

I think we might switch to `VARCHAR` (for some subset of databases?) in a case when a user provides the `field.constraints.maxLengh` constraints. WDYT? Will it solve your problem?

**Comment by roll** [comment]
I've investigated it seems that text PKs are only supported in Postgresql (Sqlite?). I've requalified this issue as a feature

**Comment by rbngz** [comment]
@roll 
I think using `VARCHAR` whenever a `field.constraints.maxLength` constraint is provided would solve the issue in our case.

**Comment by roll** [comment]
Hi @rbngz,

Can you please test it with `frictionless@4.4`?

I used this snippet for tests but we don't have a DB2 environment:

```python
source = Resource("data/table.csv")
source.infer()
source.schema.primary_key = ["name"]
source.schema.get_field("name").constraints["maxLength"] = 100 # will fail without this line
target = source.write(mysql_url, dialect=SqlDialect(table="name"))
with target:
    assert target.schema.primary_key == ["name"]
    assert target.header == ["id", "name"]
    assert target.read_rows() == [
        {"id": 1, "name": "english"},
        {"id": 2, "name": "中国人"},
    ]
```

**Comment by rbngz** [comment]
Hello @roll 

Thanks a lot! 
In our case, `self.__connection.engine.dialect.name` yields  `'ibm_db_sa'` instead of `'db2'`. 
The connection string builds the engine using the [IBM_DB_SA adapter](https://github.com/ibmdb/python-ibmdbsa/tree/master/ibm_db_sa), which will set the value of `self.__connection.engine.dialect.name`. I don't think I am able to change it from our coding. Could you maybe include `'ibm_db_sa'`?

```python
elif const == "maxLength":
    # Only Postgresql and Sqlite support TEXT to be a Primary Key
    # https://github.com/frictionlessdata/frictionless-py/issues/777
    if self.__connection.engine.dialect.name in ["mysql", "db2", "ibm_db_sa"]:
        column_type = sa.VARCHAR(length=value)
    checks.append(Check("LENGTH(%s) <= %s" % (quoted_name, value)))
```
Thank you and sorry for all the trouble.

**Comment by roll** [comment]
Hi, can you please try with `frictionless@4.5.1`. It will be released in a few minutes

**Comment by rbngz** [comment]
Works perfectly, thanks!
