### ISSUE TITLE
Use CLI/Python codeblocks in intermediate guides

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#783]
# Overview

In #782 we added CLI/Python codeblocks to quick-start and basic-examples. It's very nice to have codeblocks like this but it greatly increases the complexity of documentation and makes it's harder to change and maintain.

I would suggest thinking about adding the same feature to describe/extract/validate/transform guides when it's fully stable like closer to Q3/Q4 2021.

**Comment by lwinfree** [comment]
Yay this is awesome! I agree - let's aim to add this functionality to the rest of the docs later this year. Thanks for implementing this!

**Comment by shashigharti** [comment]
@roll for code examples such as this where we do not have command line equivalent shall I keep it as it is or add a tab for python only?
https://framework.frictionlessdata.io/docs/guides/extracting-data#reading-bytes

**Comment by roll** [comment]
@shashigharti 
I think "as it is" is ok
