### ISSUE TITLE
Use resource.to_view() in the documentation guides

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#785]
# Overview

Currently, we only use `pprint` which might be not perfect for readability (esp. in the transform guide). Also, we might use some graphics like Pandas does - https://pandas.pydata.org/docs/getting_started/intro_tutorials/03_subset_data.html#how-do-i-select-specific-columns-from-a-dataframe

# Plan

- [ ] identify places in the documentation where we print data using `pprint`
- [ ] replace them by using `resource.to_view()`
- [ ] (optional) consider implementing `package.to_view()` calling underlying `resource.to_view()` -- let's discuss

**Comment by roll** [comment]
Related to #1029

**Comment by shashigharti** [comment]
@roll for sections like this:
```
rows = extract('capital-3.csv')
pprint(rows)
```
Can I use?
```
rows = Resource(extract('capital-3.csv'))
print(rows.to_view())
```

**Comment by roll** [comment]
No, in this case we need to show that extract return row objects

**Comment by shashigharti** [comment]
So would it be like:

```
rows = extract('capital-3.csv')
pprint(Resource(rows).to_view())
```

or shall I skip this part?

**Comment by roll** [comment]
Yea just skip. Maybe I was too optimistic about amount of places we can use to_view...

**Comment by roll** [comment]
Although I think at least the whole transform guide can be rebased on it

**Comment by shashigharti** [comment]
okay! Then I will apply it to those parts where we have resource object/s and displaying the data such as this 

```
# Apply transform steps
target = transform(
    source,
    steps=[
        steps.table_normalize(),
        steps.field_add(name="cars", type="integer", formula='population*2'),
    ],
)

# Print resulting schema and data
pprint(target.schema)
pprint(target.read_rows())
```

Here I think we can replace 
`pprint(target.read_rows()) `with `to_view() .` WDYT?

**Comment by roll** [comment]
Yea exactly 💯
