### ISSUE TITLE
Converter from JSON Schema to Table Schema

### ISSUE THREAD

**Issue by spitschan** [frictionlessdata/frictionless-py#787]
# Overview

It would be a great addition to have an automatic converter that takes a JSON Schema and converts it into Table Schema. As an example, ECRIN has [data schemas](https://ecrin-mdr.online/index.php/Study_JSON_v5) specified in JSON Schema, and one use case will be to automatically generate a Table Schema from this.

I'm also tagging @ghammad as I have discussed this at length with him. I also discussed this with @roll on the Frictionless discord.

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Thanks for creating the issue @spitschan!

**Comment by roll** [comment]
Hi @spitschan,

I'm releasing `frictionless@4.5` with the first version of the converter. It works like this - https://github.com/frictionlessdata/frictionless-py/blob/main/tests/test_schema.py#L318

**Comment by spitschan** [comment]
Works like a charm. Thank you.

> Hi @spitschan,
> 
> I'm releasing `frictionless@4.5` with the first version of the converter. It works like this - https://github.com/frictionlessdata/frictionless-py/blob/main/tests/test_schema.py#L318

**Comment by roll** [comment]
Awesome! 

Let me know (or PR :smiley:) if you'd like to map some other metadata (maybe `arrayItem` etc)
