### ISSUE TITLE
to_json() only accessible to file owner

### ISSUE THREAD

**Issue by brockfanning** [frictionlessdata/frictionless-py#788]
# Overview

When I use the .to_json() method for package metadata, the file that is produced is only accessible to the owner. Eg:

```
-rw-------   1 brockfanning brockfanning 1363 Mar 31 05:09 datapackage.json
```

I would have expected: `-rw-r--r--`

In case it's relevant:

```
python --version
Python 3.8.5
```

Is that expected behavior? My goal is to use this to post the files to a web server, and with this issue users are getting access-denied when they try to download the file. I assume that I can add some code to change the permissions after writing the file, but it seemed like maybe something that should be automatic.

Thank you for any advice!

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi @brockfanning,

Thanks I'll fix it. I think it should be `rw-r-r`

**Comment by roll** [comment]
Hi,

can you please test with `frictionless@4.4.2`?

**Comment by roll** [comment]
Not yet on PyPi - something wrong with uploading to the registry...
