### ISSUE TITLE
Support renaming resource/field in transform

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#793]
# Overview

We can use `resource/field_update` with a new `new_name` argument signaling that the renaming is requested.

**Comment by bkarolina** [comment]
I will be really happy once this is implemented :-)

**Comment by roll** [comment]
@bkarolina 
It's about to be released as `frictionless@4.10`

The `steps.resource/field_update` now accepts the `new_name` argument for renaming.
