### ISSUE TITLE
JSON validation is failed

### ISSUE THREAD

**Issue by Kiollpt** [frictionlessdata/frictionless-py#794]
# Overview
first I tried auto infer the schema by using `schema = Schema(path)`  but `schema.field_names` is empty. 
So I decided to create `Resource` with schema by manually
however,  I got this **error** below after the validation.

```
{'version': '4.3.2', 'time': 0.003, 'errors': [{'code': 'scheme-error', 'name': 'Scheme Error', 'tags': [], 'note': 'cannot create loader "". Try installing "frictionless-"', 'message': 'The data source could not be successfully loaded: cannot create loader "". Try installing "frictionless-"', 'description': 'Data reading error because of incorrect scheme.'}], 'tasks': [], 'stats': {'errors': 1, 'tasks': 0}, 'valid': False}


```

## Here is my code:
```python

d = json.load(open(path,"r"))
schema = Schema({'fields': [{'name': 'price', 'type': 'integer'}]})
res = Resource(data=d,schema=schema)

res.name = 'new-name'
res.title = 'New Title'
res.description = 'New Description'


print(validate_resource(res))


```

Please preserve this line to notify @roll (lead of this repository)

**Comment by Kiollpt** [comment]
## UPDATED

After I remove `Schema` it works, but it was the way of creating a schema from the document.
``` python
schema = {"fields": [{"name": "price", "type": "integer"}]}
res = Resource(data=d,schema=schema)

res.name = 'new-name'
res.title = 'New Title'
res.description = 'New Description'
pprint(report.flatten(spec=["rowPosition", "fieldPosition", "code","message"]))
```
I got the weird report with the data:

`d = [{"tmp":"aa"},{"price":"abc"},{"price":"kk"}]`

```python

[[None,
  1,
  'incorrect-label',
  'Label "tmp" in field price at position "1" does not match the field name in '
  'the schema'],
 [2,
  1,
  'type-error',
  'Type error in the cell "aa" in row "2" and field "price" at position "1": '
  'type is "integer/default"'],
 [3, None, 'blank-row', 'Row at position "3" is completely blank'],
 [4, None, 'blank-row', 'Row at position "4" is completely blank']]

```
Why the row position shows `None` ?
row 3 should be type-error as well  and should not show row 4.

**Comment by roll** [comment]
Hi @Kiollpt,

Your data written in default form looks like this:

```csv
[1] tmp -> incorrect label as first field is "price" (header errors doesn't have row position)
[2] aa -> type error because "aa" is not integer
[3] n/a,abc -> emty row because the schema has only 1 field
[4]:n/a,kk -> emty row because the schema has only 1 field
```

Please let me know if it didn't help

**Comment by Kiollpt** [comment]
@roll 
Thank you for the reply.
I am wondering that I am using the `json` not `csv`, so it already means there is no header. 
Do we still need the header error involved?
And the row positions might follow the index from the json array ( {"tmp":"aa"}->1 , {"price":"abc"}->2 , {"price":"abc"}->3 )

`n/a,abc ` this return  `blank-row`. I don't understand that this row is not exactly empty. it still have the "abc" value.

**Comment by roll** [comment]
> Do we still need the header error involved? And the row positions might follow the index from the json array ( {"tmp":"aa"}->1 , {"price":"abc"}->2 , {"price":"abc"}->3 )

Yes. That's how parsing protocol works for keyed inline data:

```python
resource = Resource(data=[{"tmp": "aa"}, {"price": "abc"}, {"price": "kk"}])
pprint(resource.read_lists())
```
```
[['tmp'], ['aa'], [None], [None]]
```

> n/a,abc this return blank-row. I don't understand that this row is not exactly empty. it still have the "abc" value.

That's how the validator (print above) sees your data. It uses the keys from the first element as a header row and picks corresponding values from the following rows. You can alter this behaviour providing `InlineDialect`:

```python
data = [{"tmp": "aa"}, {"price": "abc"}, {"price": "kk"}]
dialect = InlineDialect(keys=["tmp", "price"])
resource = Resource(data=data, dialect=dialect)
pprint(resource.read_lists())
```
```
[['tmp', 'price'], ['aa', None], [None, 'abc'], [None, 'kk']]
```
