### ISSUE TITLE
Support time zone aware datetimes in the Pandas integration

### ISSUE THREAD

**Issue by The-Aniliner-Gerstung** [frictionlessdata/frictionless-py#799]
# Overview
Hello roll and frictionless team. First of all: great work! We are using frictionless in production and it really helps us managing data consistently.
However I noticed that when I read a datapackage or resource with a datetime field that contains time zone aware timestamps, the time zone information is discarded when converting to pandas.

# Reproduce
python version: `3.8.0`
frictionless version: `4.5.1`
pandas version: `1.2.3`

I create a pandas dataframe and write that to a csv file. Infer the csv file with frictionless, read the resource and convert to pandas. Compare the dtypes between the written and read dataframe:

```
import frictionless as fl
import pandas as pd
import pprint

df_out = pd.DataFrame()
df_out["timestamp"] = pd.date_range("2020-01-01", periods=5, freq=pd.to_timedelta("1h"), tz="Europe/Oslo")
df_out["value"] = [3, 5, 7, 9, 4]
df_out.to_csv("data.csv", index=False, date_format="%Y-%m-%dT%H:%M:%S%z")

res = fl.Resource("data.csv")
res.infer()
res.to_json("resource.json")

df_in = fl.Resource("resource.json").to_pandas()

print("DF Write -----------")
print(df_out["timestamp"].dtype)
pprint.pprint(df_out)

print("\nDF Read -----------")
print(df_in["timestamp"].dtype)
pprint.pprint(df_in)
```
Output:
```
DF Write -----------
datetime64[ns, Europe/Oslo]
                  timestamp  value
0 2020-01-01 00:00:00+01:00      3
1 2020-01-01 01:00:00+01:00      5
2 2020-01-01 02:00:00+01:00      7
3 2020-01-01 03:00:00+01:00      9
4 2020-01-01 04:00:00+01:00      4

DF Read -----------
datetime64[ns]
            timestamp  value
0 2020-01-01 00:00:00      3
1 2020-01-01 01:00:00      5
2 2020-01-01 02:00:00      7
3 2020-01-01 03:00:00      9
4 2020-01-01 04:00:00      4
```

This also happens when I manually add `"format": "%Y-%m-%dT%H:%M:%S%z"` to the `resource.json` `timestamp`-field.

Any hints on what I am doing wrong or is it a reproducible bug?

---
Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi @The-Aniliner-Gerstung,

Thanks for reporting. It's a current limitation of the `pandas` plugin - https://framework.frictionlessdata.io/docs/tutorials/formats/pandas-tutorial/#writing-data

We would like to implement it. 

If you're interested in creating a PR for it - also would be great.

**Comment by The-Aniliner-Gerstung** [comment]
Hi @roll , 

thanks for the clarification. I haven't found that particular tutorial, but now it is clear. I am afraid that I am not able to create a PR for that issue, I'm just not deep enough on subject without breaking anything, sorry. We will probably continue to store all timestamps in UTC and explicitly localize them after reading.

Keep up the good work!

**Comment by aivuk** [comment]
@roll I'm working on the problem and the main culprit is here https://github.com/frictionlessdata/frictionless-py/blob/main/frictionless/plugins/pandas.py#L197 where we are losing the timezone information. I checked that we are using passing a dtype to pandas without the timezone information `datetime64[ns]` at https://github.com/frictionlessdata/frictionless-py/blob/main/frictionless/plugins/pandas.py#L244. I couldn't find a way to set the initial timezone for the datetime64 type, but we can load all the column and convert it after that with something as  df_in.timestampe = df_in.timestamp.dt.tz_localize('Europe/Oslo'). Problems with this approach:

 * we will need to extract the timezone information name to pass to tz_localize, but probably there is a simpler way to do that
 * if we have a mixed timezone in a datetime column, this will generates erroneous data in the dataframe. Maybe we need to add an option to the converter, where the user says what to do in case of mixed timezone information?

**Comment by roll** [comment]
Yea it might be tricky. Although we can try something to implement but need to keep performance in mind and not get too hacky
