### ISSUE TITLE
A CSV that should return no errors

### ISSUE THREAD

**Issue by aborruso** [frictionlessdata/frictionless-py#803]
# Overview

Hi,
I have a bad CSV. But it seems to me it does not have any RFC 4180 error.

It's a CR/LF file, and inside the cells you have some LF char. And it's iso8859-1 encoded.

If download it

```
curl "https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_22022013102700.csv" | iconv -f iso8859-1 -t UTF-8 >./output.csv
```

and then run

```
frictionless validate output.csv --json
```

I have the below output. I have some notes:

- the field delimiter is not recognized;
- the empty row error, is not an error. I have no empty row, I have some line feeds inside some cells.

If I run `dos2unix output.csv` the command `frictionless validate` give me no error, and it recognizes properly the field separator.

Is it mandatory to convert DOS CSV file to UNIX?

Thank you

```json
{
  "version": "4.6.0",
  "time": 0.102,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "path": "tmp.csv",
        "name": "tmp",
        "profile": "tabular-data-resource",
        "scheme": "file",
        "format": "csv",
        "hashing": "md5",
        "encoding": "utf-8",
        "schema": {
          "fields": [
            {
              "name": "Cariche;Competenze",
              "type": "string"
            }
          ]
        },
        "stats": {
          "hash": "8b7f86d6ec91e1e06113d06d946a8f99",
          "bytes": 3860,
          "fields": 1,
          "rows": 64
        }
      },
      "time": 0.102,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [],
          "rowNumber": 42,
          "rowPosition": 43,
          "code": "blank-row",
          "name": "Blank Row",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "",
          "message": "Row at position \"43\" is completely blank",
          "description": "This row is empty. A row should contain at least one value."
        }
      ],
      "stats": {
        "errors": 1
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 1,
    "tasks": 1
  },
  "valid": false
}
```

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Thanks, I'll investigate

**Comment by roll** [comment]
@aborruso 
Under the hood, we use the built-in Python's CSV sniffer and it seems to not be able to detect the delimiter properly for this file (I tried a few times using different approaches). In this case, we just need to provide the delimiter manually (this command will work since `frictionless@4.7`):

```bash
$ frictionless describe --dialect '{"delimiter": ";"}' https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_22022013102700.csv

dialect:
  delimiter: ;
encoding: iso8859-1
format: csv
hashing: md5
name: _22022013102700
path: https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_22022013102700.csv
profile: tabular-data-resource
schema:
  fields:
    - name: Cariche
      type: string
    - name: Competenze
      type: string
scheme: https
```

Is it a correct output (also, there are not validation errors)?

**Comment by aborruso** [comment]
hi @roll ,
I'm using the great frictionless to bulk validate hundreds of CSV files.

The output I have is very great for me:

- I can map a lot of errors;
- I can infer all the separators;
- I can infer all the encodings;
- I can read the dimensions (rows, columns and byte).

And I can use the report I build on these to tell the owner of the data to check the errors, normalize or to document the CSV separator, normalize or to document the file encoding, to stop to publish 2 rows x 2 columns files. These are examples.

Then I do now know what's the separator of each CSV source file. And without writing `--dialect '{"delimiter": ";"}'` I will have always an error.

If apply `dos2unix` frictionless is able to read properly the delimiter. And I'm using this bash check

```bash
if dos2unix <file.csv | cmp - file.csv; then
  echo "ok"
else
  dos2unix file.csv
fi
```

**Comment by roll** [comment]
Yea, it seems for this exact file `dos2unix` is the way to go then. In general (without may quoted new line chars), I think the CSV sniffer should detect delimiters properly
