### ISSUE TITLE
Simple Example of Using Frictionless for TableSchema-like validation

### ISSUE THREAD

**Issue by dcdanko** [frictionlessdata/frictionless-py#809]
# Overview

I'm trying to do something with frictionless that I expect is very simple but I can't find documentation or examples for it. I would suggest adding a small example to the docs.

I have a CSV file and a JSON Table Schema and I want to validate the CSV file against the schema. Basically I want to do exactly the scenario described in the [introduction to tableschema-py](https://github.com/frictionlessdata/tableschema-py#introduction). 

How can this be done in frictionless?

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi @dcdanko,

Do you mean something like this?

```python
from frictionless import validate

report = validate('table.csv', schema='schema.json')
print(report)
```

**Comment by dcdanko** [comment]
That does look like what I need yes.

For me it feels like some other basic examples would go a long way. For example based on the docs it seems like it should be possible to replace the file paths with objects but that does not seem to work.

e.g.
```
from frictionless import validate

tbl = {'a': 1}
schema = {'fields': {'name': 'a', 'type': 'number'}}

report = validate(tbl, schema=schema)  # report shows an error
```

**Comment by roll** [comment]
Yes, it's possible the data needs to be an array or rows and the fields needs to be an array as well:

```python
from pprint import pprint
from frictionless import validate

tbl = [{"a": 1}]
schema = {"fields": [{"name": "a", "type": "number"}]}

report = validate(tbl, schema=schema)
pprint(report)
```

**Comment by roll** [comment]
Also, an example similar to mimic what is written in the `tableschema-py` docs:

```python
resource = Resource('data.csv', schema='schema.json', onerror='raise')
pprint(resource.read_rows())
```

Please let me know if you need more help :+1:

**Comment by lwinfree** [comment]
I'm commenting here to remind myself to look at adding more info/examples/explanation to the docs or FAQs for these questions. Thanks David!

**Comment by dcdanko** [comment]
Thank you for the quick responses. these examples are really useful!

**Comment by only1chunts** [comment]
Is there a way to do the validation on the command line instead of having to use Python? 
I'm thinking something like
`frictionless validate my-table.csv --schema my-table.schema.yaml`

**Comment by roll** [comment]
Hi! Yes, sure - https://framework.frictionlessdata.io/docs/guides/validating-data.html
