### ISSUE TITLE
What's the difference between "any" and "string"

### ISSUE THREAD

**Issue by aborruso** [frictionlessdata/frictionless-py#812]
Hi all,
what's the difference between `type: any` and `type: string`?

I think `Any` is [this](https://docs.python.org/3/library/typing.html#the-any-type). But when does `frictionless describe` tell me that the field is of this type? What must happen?

Thank you

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
@aborruso 
It's from the specs - https://specs.frictionlessdata.io/table-schema/#any

For the framework, it means that this field (having type "any") will not have any validation/conversion and will persist as it is (based on the input data)

**Comment by aborruso** [comment]
@roll probably I have sometimes some stupid questions, if so, I apologize.

Ok, it means that this field will not have any validation/conversion. Thank you.

Imagine you only have an input file CSV, without any schema.  Than you have only inferencing.
When is `frictionless describe` returning this type of field? What characteristics a field must it have to return this type of field after inferencing? Why does it return `any` and not `string`?

Thank you for all

**Comment by roll** [comment]
@aborruso 
Here is an example:

```python
from pprint import pprint
from frictionless import describe

resource = describe([["value"], [1], ["a"]])
pprint(resource.schema)
```
```
{'fields': [{'name': 'value', 'type': 'any'}]}
```

I used a typed data source (INLINE) but it might have been JSON/EXCEL/etc. There are two native python values `1` (is not compatible with a string) and `a` (is not compatible with an integer) so, as a result, it's `any`.

It it were `string` or `integer` the validation would fail so it will only pass if it's `any`.

**Comment by roll** [comment]
```python
from frictionless import validate, Schema, Field

data = [["f"], [1], ["a"]]
print(validate(data, schema=Schema(fields=[Field(name="f", type="integer")])).valid) # FALSE
print(validate(data, schema=Schema(fields=[Field(name="f", type="string")])).valid) # FALSE
print(validate(data, schema=Schema(fields=[Field(name="f", type="any")])).valid) # TRUE
```

**Comment by aborruso** [comment]
Thank you very much @roll

**Comment by roll** [comment]
I think if we work with CSV it will always use `string` instead of `any`.

**Comment by aborruso** [comment]
> I think if we work with CSV it will always use `string` instead of `any`.

No, you can have `any` also for a CSV:

```
frictionless describe https://gist.githubusercontent.com/aborruso/9eac0ebed9f4b76471a1f412dd0a938f/raw/0f25382a4b55230b8bc217534cdc35209adcd8d8/input.csv
```

**Comment by roll** [comment]
Thanks. Great to know! It seems when there are many null values. We might need to improve the detection algorithm for this case.

**Comment by aborruso** [comment]
> Thanks. Great to know! It seems when there are many null values. We might need to improve the detection algorithm for this case.

That was why I persisted with this question, but couldn't explain myself. Thank you
