### ISSUE TITLE
steps meaning

### ISSUE THREAD

**Issue by aborruso** [frictionlessdata/frictionless-py#813]
Hi,
I'm very impressed from frictionless, and I'm writing a small Italian guide.

I'm studying the first steps of transformation, I'm reading [it](https://framework.frictionlessdata.io/docs/guides/basic-examples/#transforming-data). 

Where I can find the meaning of each step? Often the meaning can be deduced from the name, but other times I am not sure.
I do not find it in https://framework.frictionlessdata.io/docs/references/steps-reference/

What's in example the meaning of `table-normalize`?

Thank you

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
@aborruso 
There is a guide showing how all the steps work - https://framework.frictionlessdata.io/docs/guides/transform-steps

It was missing `normalize-table` but it's now been added

**Comment by aborruso** [comment]
@roll really very useful, thank you.

I think that it would be great to add some "human readable" short notes for every steps.

I give a hand with pleasure, for what I can imagine, as table_aggregate (I'm doing a PR):

```
The `table_aggregate` aggregates one or more fields, using an accumulator (sum, count, ecc.).
```

But I'm not sure to write the right things for steps like `table_recast`.

Thank you

**Comment by roll** [comment]
@aborruso 
Most of the Frictionless steps wrap PETL's transform under the hood for the data. For example, for the `aggretate` - https://petl.readthedocs.io/en/stable/transform.html?highlight=aggregate#petl.transform.reductions.aggregate

We haven't yet fully-added these docs so ATM you can add much more info here -https://petl.readthedocs.io/en/stable/transform.html
