### ISSUE TITLE
Inferencing of encoding

### ISSUE THREAD

**Issue by aborruso** [frictionlessdata/frictionless-py#824]
# Overview

Hi,
I'm doing a report of an open data portal, and in doing so I discover some behaviors that can be interesting for frictionless

Running `frictionless validate` on these bad CSV files:

- https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_10012018100714.csv
- https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_11012018092656.csv
- https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_11012018072326.csv

frictionless gives me error because is not able to map the encoding.

Using [chardet](https://github.com/chardet/chardet) via CLI, I have the right encoding for the first two (`ISO-8859-1` and `Windows-1252`), and I can use iconv to convert them in UTF-8.

For the last CSV I have not found an automatic tool to map the right encoding. Making visual attempts, I found that it is IBM850.

Could you useful to integrate chardet in encoding mapping? In any case, I hope that these files can be useful to optimize the current modes to inference encoding.

Best regards

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi @aborruso,

`chardet` uses a bigger byte sample (called a buffer in Frictionless terms). Frictionless uses `chardet` under the hood but it returns `ascii` for our default buffer size `10000`.

It works if we increase the buffer size:

```bash
frictionless validate --buffer-size 250000 https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_10012018100714.csv
frictionless validate --buffer-size 250000 https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_11012018092656.csv
```

Please let me know if it helped

**Comment by aborruso** [comment]
Really interesting, thank you!

it helped a lot
