### ISSUE TITLE
wrong duplicate-label error

### ISSUE THREAD

**Issue by aborruso** [frictionlessdata/frictionless-py#825]
# Overview

Hi,
I have this kind of CSV:

| Musei | 2011 | 2010 |
| --- | --- | --- |
| Galleria d'Arte moderna e mostre temporanee | 23.824 | 17.518 |
| Museo Pitrè | in restauro | in restauro |

If I run 

```
frictionless validate https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_22022013093551.csv
```

I have a strange error, because "in restauro" is not in the heading.

```
===  =====  ===============  ===========================================================================================
row  field  code             message
===  =====  ===============  ===========================================================================================
         3  duplicate-label  Label "in restauro" in the header at position "3" is duplicated to a label: at position "2"
===  =====  ===============  ===========================================================================================
```

Thank you

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
It was because of the too aggressive header guessing. I've handled this edge case and releasing a fix but we might need to relax it more later if we run into something similar

**Comment by aborruso** [comment]
Thank you very much @roll
