### ISSUE TITLE
Styling issue with Search / Github / Light or dark mode toolbar using Chrome desktop browser

### ISSUE THREAD

**Issue by StephenAbbott** [frictionlessdata/frictionless-py#826]
# Overview

Noticed a small styling issue on Chrome desktop browser when looking at the [https://framework.frictionlessdata.io](framework.frictionlessdata.io) homepage where the Back to main site / Github / Light and dark mode / Search box toolbar is hard to read as it is showing up half on the white top navbar and half on the dark background. Could this be adjusted so that the toolbar sits fully on the white top navbar? 

![FD Framework screengrab](https://user-images.githubusercontent.com/1506468/116049291-696c7780-a676-11eb-819d-53639c9182fb.png)

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by lwinfree** [comment]
+1 I see this too. Also on Chrome.

**Comment by roll** [comment]
I've slightly improved the situation although for a better solution we need to dive deeper into CSS
