### ISSUE TITLE
The task has an error: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by pierredittgen** [frictionlessdata/frictionless-py#833]
# Overview

frictionless reports an error which is hard to understand: `The task has an error: 'NoneType' object is not iterable`

### sample.csv

```csv
id,value
1,["a"]
2,
3,["b"]
```

### schema.json

```json
{
  "fields": [
    {
      "name": "id",
      "type": "number"
    },
    {
      "name": "value",
      "type": "array",
      "arrayItem": {
        "type": "string",
        "constraints": {
          "enum": ["a", "b", "c"]
        }
      }
    }
  ]
}
```

### validate_array_data.py

```python
#!/usr/bin/env python3
import json
import frictionless

report = frictionless.validate_resource("sample.csv", schema="schema.json")
print(json.dumps(report.to_dict(), indent=2))
```

## Output 

Running this python script returns:
```json
{
  "version": "4.9.2",
  "time": 0.09,
  "errors": [
    {
      "code": "task-error",
      "name": "Task Error",
      "tags": [],
      "note": "'NoneType' object is not iterable",
      "message": "The task has an error: 'NoneType' object is not iterable",
      "description": "General task-level error."
    }
  ],
  "tasks": [],
  "stats": {
    "errors": 1,
    "tasks": 0
  },
  "valid": false
}
```

Bug origin lays in [field.py](https://github.com/frictionlessdata/frictionless-py/blob/701d35150688c24d1068f5b677872a440f400cde/frictionless/field.py#L312) because `cell` is None.

It was not so easy for me to find the root of the problem. When such an exception arises, it's caught in [pipeline.py](https://github.com/frictionlessdata/frictionless-py/blob/701d35150688c24d1068f5b677872a440f400cde/frictionless/pipeline.py#L140) and its message is embedded into validation report but we lose stack trace.

Would it be possible to log complete exception stacktrace in `pipeline.py` to ease debugging when an unexpected exception occurs?

Thanks

- [validate_array_data.py.txt](https://github.com/frictionlessdata/frictionless-py/files/6397806/validate_array_data.py.txt)
- [schema.json.txt](https://github.com/frictionlessdata/frictionless-py/files/6397807/schema.json.txt)

- [sample.csv](https://github.com/frictionlessdata/frictionless-py/files/6397704/sample.csv)

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
@pierredittgen 
Thanks. It's definitely a good idea to have a debug mode - https://github.com/frictionlessdata/frictionless-py/issues/840 - thought about this many times. I created a feature request for it.

I'm going to fix this issue

**Comment by johanricher** [comment]
Thank you @roll!
