### ISSUE TITLE
"schema" cannot be used in the name of schema files

### ISSUE THREAD

**Issue by aborruso** [frictionlessdata/frictionless-py#838]
My input is

```
fieldA,fieldB
a,1
b,2
```

If I run `frictionless describe input.csv --yaml >input.schema.yaml` and then  `frictionless validate input.schema.yaml`, I have this error:

```
# -------
# invalid: input.schema.yaml
# -------
============  =====================================================================================================
code          message
============  =====================================================================================================
schema-error  Schema is not valid: "'fields' is a required property" at "" in metadata and at "required" in profile
============  =====================================================================================================
```

If I rename `input.schema.yaml` in `input.scema.yaml` I have no error

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by lwinfree** [comment]
Oh this is a great error to discover!

**Comment by roll** [comment]
@lwinfree 
@aborruso 

Frictionless Validate detects a type of the input - it might be a Data Package, Data Resource, or Table Schema - https://framework.frictionlessdata.io/docs/guides/validation-guide#validate-functions

So these calls are equivalent:

```bash
$ frictionless validate input.schema.yaml # detects input type to be a schema
$ frictionless validate --type schema input.schema.yaml
```

You can explicitly provide a type:

```bash
$ frictionless validate --type resource input.schema.yaml # forced to handle it as a resource
```

In general, I would suggest not mix schema/resource naming as it might be confusing going forward and would use suffixes (if using them at all):

```
input.schema.yaml - Table Schema # frictionless describe table.csv --type schema 
input.resource.yaml - Table Resource # frictionless describe table.csv --type resource 
input.package.yaml - Data Package # frictionless describe table.csv --type package
```

Please let me know if you think we might need to change this behavior - we can open a feature/enhancement issue then to discuss.

**Comment by aborruso** [comment]
> Please let me know if you think we might need to change this behavior - we can open a feature/enhancement issue then to discuss.

No, do not change it, I like it!

Is there some note in the documentation ("Pay attention, if in the file name you use is ..., frictionless will make that kind of validation")? 

Thank you

**Comment by roll** [comment]
I think no, do you think what place in the docs might be the best place for this?

**Comment by aborruso** [comment]
> I think no, do you think what place in the docs might be the best place for this?

In the [doc](https://framework.frictionlessdata.io/docs/guides/basic-examples) this is the first place in which you use a name that has a special meaning

![image](https://user-images.githubusercontent.com/30607/116979583-7831da80-acc5-11eb-9027-2c4789c97469.png)

Probably below it

**Comment by roll** [comment]
Thanks. I've added a paragraph to https://framework.frictionlessdata.io/docs/guides/describing-data#describe-functions (will have been deployed in a minute)

**Comment by aborruso** [comment]
> Thanks. I've added a paragraph to https://framework.frictionlessdata.io/docs/guides/describing-data#describe-functions (will have been deployed in a minute)

Very useful and clear, thanks
