### ISSUE TITLE
Feature request - Validation/Constraint - Rows (or table) only contains characters in ASCII characters

### ISSUE THREAD

**Issue by sjadata** [frictionlessdata/frictionless-py#845]
# Overview
Hello, 

Is it possible to add a validation function that flags whether or not a given Resource contains ASCII only characters? 

Example of valid and not valid data:

```
# Valid
A,B,C
1,2,3

# Not valid
A,B,C
1,µ,€
```

Example implementation:
```
# Basic implementation
my_checks = [frictionless.checks.isascii()]
frictionless.validate(data, checks=my_checks)

# Alternative implementation
# Flagging if any data is outside a list of allowed unicode codes or
# Flagging if any data is within a list of disallowed unicode codes. 
codes= range(1 to 100)
my_checks = [frictionless.checks.codes(whitelist=codes)]

codes= [85, 164, 302]
my_checks = [frictionless.checks.charset(blacklist=codes]
```

Thanks

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Thanks,

I think it's possible to implement something like this.

As a quick fix, you can just provide an `encoding` parameter:

```python
report = validate('table.csv', encoding='ascii')
```

It must get an `encoding-error`

**Comment by ezwelty** [comment]
How about using the equivalent regular expression as a pattern field constraint? 
For example `[0-9A-Za-z]*`, `[\u0020-\u00f6]*`, etc

Edit: This would only work if you wanted this check on an entire column, so may not meet your row-based needs.
