### ISSUE TITLE
Add Open Graph tags to Frictionless Framework website

### ISSUE THREAD

**Issue by johanricher** [frictionlessdata/frictionless-py#854]
The new [framework.frictionlessdata.io](https://framework.frictionlessdata.io/) website is truly awesome and I really want a lot of people to discover it. This could be a bit facilitated with some small SEO improvements like adding some basic [Open Graph metadata](https://ogp.me/) in particular an image:

![image](https://user-images.githubusercontent.com/10212787/114252850-a57db800-99a7-11eb-9c28-6d89dcf868f2.png)

This can be tested with [metatags.io](https://metatags.io/) and other metrics should probably be also [kept in check](https://web.dev/measure/) at the same time.

**Comment by roll** [comment]
@lwinfree 
I think it was meant for https://framework.frictionlessdata.io/ not https://frictionlessdata.io/ so it seems to be a more right place to keep track of

**Comment by aivuk** [comment]
Testing the current page https://framework.frictionlessdata.io/ on https://metatags.io/, I would suggest to change:

Title from: Describe, extract, validate, and fransform data in Python | Frictionless Framework
To: Frictionless Framework - Describe, extract, validate, and fransform data in Python

Putting the framework name first.

Description from: Data management framework for Python that provides functionality to describe, extract, validate, and transform tabular data

@roll @lwinfree Do you think it make sense to stick to *tabular*? I know it is the main use case, but a datapackage can also contains no tabular data. Maybe a more general term or just removing tabular? 

What is missing from the tag is an image, we could use the current logo or for the moment, until the new logo is done a screenshot of the current framework website, what do you think?

**Comment by lwinfree** [comment]
Thanks Edgar.

I think making this change is fine:

> Title from: Describe, extract, validate, and fransform data in Python | Frictionless Framework
> To: Frictionless Framework - Describe, extract, validate, and fransform data in Python

I don't have a strong opinion about _tabular_ either way. What about you @roll ?

For the image, please use the current logo (https://frictionlessdata.io/design/). This is the current framework logo: https://github.com/frictionlessdata/frictionless-py/blob/main/site/static/img/logo-bright.png

**Comment by roll** [comment]
I think it's still better to have `tabular data` as just `data` is too wide.

Currently, our "official" description is `Data management framework for Python that provides functionality to describe, extract, validate, and transform tabular data`

**Comment by johanricher** [comment]
Awesome, thanks!
