### ISSUE TITLE
Newline characters lead to broken CSV

### ISSUE THREAD

**Issue by n0rdlicht** [frictionlessdata/frictionless-py#865]
# Overview

When reading an html table that includes `\n` characters inside a cell, converting to CSV produces broken files.

```python
from frictionless import Resource
from frictionless.plugins.html import HtmlDialect

resource = Resource(path="data/table-with-newline-characters.html", dialect=HtmlDialect(selector="#id"))
resource.write(path="data/table-data.csv")
```

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Thanks @n0rdlicht, I'll investigate

**Comment by n0rdlicht** [comment]
Thank. Let me know if you need sample files/links.

**Comment by roll** [comment]
@n0rdlicht 
Can you please share the HTML file?

**Comment by n0rdlicht** [comment]
Sample file attached.

[construction-sites.html.zip](https://github.com/frictionlessdata/frictionless-py/files/6661472/construction-sites.html.zip)

**Comment by roll** [comment]
Thanks @n0rdlicht,

I run read html / write csv on this file and Frictionless outputs a valid CSV - https://gist.githubusercontent.com/roll/f9945f9dc31d739652912fcf9b23966c/raw/10d0083355cb3af46ed73ce7af6306ecad0fba65/construction.csv

Newlines are quoted so you can read it back:

```python
from pprint import pprint
from frictionless import Resource

resource = Resource('https://gist.githubusercontent.com/roll/f9945f9dc31d739652912fcf9b23966c/raw/10d0083355cb3af46ed73ce7af6306ecad0fba65/construction.csv')
pprint(resource.read_rows())
```

**Comment by roll** [comment]
I've added tests - https://github.com/frictionlessdata/frictionless-py/pull/866/files

Can you please re-open if you think there is still a problem
