### ISSUE TITLE
Support additionalProperties property from json schema

### ISSUE THREAD

**Issue by darthf1** [frictionlessdata/frictionless-py#867]
# Overview
I'm trying to validate a CSV file, based on a JSON schema which is transformed with the `from_jsonschema` function. Within the json schema spec, its possible to allow (or restrict) additional properties using the [`additionalProperties`](https://json-schema.org/understanding-json-schema/reference/object.html#additional-properties) property.

When I set it to `true`, I'm allowing additional properties in the file. However, this line has no effect for the generated schema in frictionless; whenever I add an additional property, the [Extra Label](https://framework.frictionlessdata.io/docs/references/errors-reference/#extra-label) error is still thrown.

So I'm not sure how much of the json schema spec you want to support, and I noticed the `from_jsonschema` function was only added quite [recently](https://github.com/frictionlessdata/frictionless-py/pull/797). Is it possible to support the `additionalProperties` option, which (I think) should disable or [skip](https://framework.frictionlessdata.io/docs/guides/validation-guide#pickskip-errors) the extra label check?

# Code
python:
```python
import click
import json
from frictionless import Schema, Resource, validate_resource

@click.command()
@click.option('-f', '--file', type=click.Path(exists=True), help='Absolute filepath of file to validate')
@click.option('-s', '--schema', type=str, help='The JSON Schema used for validation')

def cli(file, schema):
    schema = Schema.from_jsonschema(json.loads(schema))
    resource = Resource(source=file, schema=schema)
    report = validate_resource(source=resource)

    click.echo(json.dumps(report))

if __name__ == '__main__':
    cli()
```

Schema:
```json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"properties": {
		"code": {
			"type": "integer",
		},
	},
	"required": ["code"],
	"additionalProperties": true,
}
```

CSV:
```csv
code,description
100,"nice"
```

Message:
```json
{
    "line": 0,
    "message": "There is an extra label \"\" in header at position \"2\"",
    "description": "The header of the data source contains label that does not exist in the provided schema."
}
```

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi @darthf1,

In general, Table Schema doesn't support optional fields (it's static) but you can enable it for Frictionless Framework (for validation):

```python
detector = Detector(schema_sync=True)
resource = Resource(source=file, schema=schema, detector=detector)
```

https://framework.frictionlessdata.io/docs/references/api-reference/#detector
