### ISSUE TITLE
Add string format validation

### ISSUE THREAD

**Issue by peterdesmet** [frictionlessdata/frictionless-py#869]
Some data package properties have an expected string `format`, e.g.

```
"created": {
  "format": "date-time",
},
"contributors": [
  "email": {
    "format": "email",
  }
]
```

But `frictionless validate datapackage.json` does not seem to warn when a string does not meet that requirement. E.g. the following passes as valid:

```json
{
  "created": "not_a_datetime",
  "contributors": [
    {
      "title": "Peter Desmet",
      "email": "not_an_email"
    }
  ],
  "resources": [
    {
      "name": "test",
      "data": [
        { "a": 1, "b": 2 }
      ]
    }
  ]
}
```

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Thanks @peterdesmet looks like a bug

**Comment by roll** [comment]
@peterdesmet 
The fix is being relesed

**Comment by peterdesmet** [comment]
Tested and works. Thanks!
