### ISSUE TITLE
Extract/validate needs to guess descriptor type

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#874]
# Overview

Currently, this one will not work as expected:

```python
report = validate(descriptor='datapackage.yaml') # will be handled as a default (resource)
```

**Comment by mor120** [comment]
Hey,
I will take this issue.

Clarifying everything:

Assume this is the files tree:
```
+ my_dir
    + data
        - datapackage.json
        - table.xls
        - table-reverse.csv
    + issue874.py
```

issue874.py file's content:

```Python
from pprint import pprint
from frictionless import validate

report = validate(descriptor='data/datapackage.json') # will be handled as a default (resource)
pprint(report)
```
Prints 
```
'message': 'The data resource has an error....'
```

By adding **type** attribute like that:

```
report = validate(descriptor='data/datapackage.json', type="package")
````
The function works alright and prints:
```
{'errors': [],
 'stats': {'errors': 0, 'tasks': 2},
 'tasks': [{'errors': [],
            'partial': False,
            'resource': {'encoding': 'utf-8',
            .
            .
            .
```

@roll would like to know that indeed this is the issue.

Thanks.

**Comment by roll** [comment]
@mor120 
The improvement here is to detect a type by a descriptor if the type is not provided.

I think that the same as we create a file for the source here - https://github.com/frictionlessdata/frictionless-py/blob/main/frictionless/validate/main.py#L25 - we can create a file for a descriptor if it's provided and switch type to package if `file.type` is `package`

**Comment by mor120** [comment]
Hey @roll,

The problem is that when creating the file and checking what its type via 
```Python
file = system.create_file(source, basepath=options.get("basepath", ""))
type = "package" if file.multipart else file.type
```
file's attribute - **multipart** is False so the type is **table** instead.

I think the problem is under the file  frictionless-py/file.py when checking whether the file is multipart or not.:
https://github.com/frictionlessdata/frictionless-py/blob/main/frictionless/file.py#L110
```Python
multipart = not memory and (isinstance(path, list) or expandable)
```


The multipart file i'm working with is:
https://github.com/frictionlessdata/frictionless-py/blob/main/data/datapackage.json


What do you think?

**Comment by roll** [comment]
@mor120 
What I meant is to add an additional type check. Currently, we infer `source` type with the existent code. My idea is to add a similar inferring code to `descriptor` if it's provided.

So it's not a bug; it's a possible enhancement

**Comment by mor120** [comment]
Hey,
Just updating that I'm planning to work on the enhancement soon, probably on the weekend.
