### ISSUE TITLE
Allow passing authentication headers for metadata loading

### ISSUE THREAD

**Issue by adamhooper** [frictionlessdata/frictionless-py#883]
# Overview

I'm trying to publish a Frictionless dataset that requires authentication.

Maybe something like:

```
import requests
from frictionless import Package
from frictionless.plugins.remote import RemoteControl

session = requests.Session()
session.auth = ('username', 'password')

control = RemoteControl(http_session=session)
package = Package(path='https://non-public-data.com/secret/datapackage.json', control=control)
resource = package.resources[0]
resource.read_rows()
```

From what I can see, today, there's a `control` parameter for _Resource_, but not for _Package_.

Am I approaching this problem the wrong way? I can't find anything on frictionlessdata.io about how to publish a non-public Frictionless dataset....

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi @adamhooper,

Thanks for raising it. I think there is no mechanism to provide HTTP headers for metadata extractions (It's only implemented for resource's data).

I will mark it as a feature request

**Comment by roll** [comment]
As a workaround,

Currently, you can just download it outside of the Package class and provide a descriptor to Package constructor
