### ISSUE TITLE
Type and Field extension / change behavior

### ISSUE THREAD

**Issue by antoniocali** [frictionlessdata/frictionless-py#884]
# Overview

I'm using Frictionless pretty much as Schema Detector.
I have two issues here:
1. I would like to introduce a custom type called BigInt to be able to differentiate normal Integer from a BigInt. Issue is that for how it works the detector, as soon it find a correct type (https://github.com/frictionlessdata/frictionless-py/blob/a0cd70d03df4ca6571b1e8b26445e6274ba46c3d/frictionless/detector.py#L270), it will break from the loop of the runners, invalidate in case a custom BigInteger type cause the Integer type would always succeed before.

2. I have a issue also with datetime format, still in a scenario of schema detection. Since automatically the detector will apply a `default` as format, instead of a `any` for a timestamp, it will always arise a issue on the assert (https://github.com/frictionlessdata/frictionless-py/blob/a0cd70d03df4ca6571b1e8b26445e6274ba46c3d/frictionless/types/datetime.py#L32) avoiding in case a correct `parser.parse(cell)` for different format that doesn't follow isoformat.

I'm not sure how I could patch in case these two cases, and if it's even possible.

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi @antoniocali,

What do you think if I introduce something like `Type.infer_order` property to set so a custom registered type will be able to get injected into type detection algorithm in `detector.detect_schema`?

**Comment by antoniocali** [comment]
Well :D I follow your guidelines :D so any improve for this would be a great help :)

**Comment by roll** [comment]
OK. Thanks. I'll think

**Comment by antoniocali** [comment]
Sorry, after more investigation I think there's definetly another thing to hightlight

The way I'm understanding the whole schema detection works is pretty much this.
Resource -> Detector -> Schema -> Field -> System.create_type() -> Type

Now again here we are with few things.
In the Detector, the for loop for `Fields` is hard-coded to loop through
https://github.com/frictionlessdata/frictionless-py/blob/a0cd70d03df4ca6571b1e8b26445e6274ba46c3d/frictionless/detector.py#L248
that is a constant at the end of file
https://github.com/frictionlessdata/frictionless-py/blob/a0cd70d03df4ca6571b1e8b26445e6274ba46c3d/frictionless/detector.py#L302

So ok, it seems that it could be a choice to create my custom detector to pass to the Resource, but I still assume that having somehow a way to inject those `Fields` in the detector would be a great thing.

But let's say we have anyway a way to do so, to inject the FieldTypes in the Detector.
The next issue arrives following my first pipeline.
Detector generetes a empty Schema to be able to fill with Field.
Resource -> Detector -> Schema -> **Field** -> System.create_type() -> Type
https://github.com/frictionlessdata/frictionless-py/blob/a0cd70d03df4ca6571b1e8b26445e6274ba46c3d/frictionless/detector.py#L249

Now inside the Field, the method `metadata_process` is called
https://github.com/frictionlessdata/frictionless-py/blob/a0cd70d03df4ca6571b1e8b26445e6274ba46c3d/frictionless/field.py#L408

This will follow back again the pipeline
Resource -> Detector -> Schema -> Field -> **System.create_type()** -> Type

Inside the `create_type` we have

https://github.com/frictionlessdata/frictionless-py/blob/a0cd70d03df4ca6571b1e8b26445e6274ba46c3d/frictionless/system.py#L257

so here we are at kind of our endpoint.
Even if I create my custom_type like

```
from frictionless import Type

class BigInt(Type):
    """Datetime type implementation.
    API      | Usage
    -------- | --------
    Public   | `from frictionless import types`
    """

    code = "bigint"
    builtin = True
    constraints = [
        "required",
        "minimum",
        "maximum",
        "enum",
    ]

    # Read

    def read_cell(self, cell):
        pass

    # Write

    def write_cell(self, cell):
        pass

```

since my class won't belong to the `vars(import_module("frictionless.types")).values()` because is not in the correct module, I won't be able to use at all my custom type for my schema.

I hope what I wrote makes sense.

**Comment by roll** [comment]
@antoniocali 
Thanks, I'm going to review all this to indicate what's missing

Regarding new type registration, it's implemented via plugin registration - https://github.com/frictionlessdata/frictionless-py/blob/main/tests/test_type.py

I think what is missing is the way to hook into type detection and might be something else. I'm going to work on it having your use case in mind

**Comment by antoniocali** [comment]
Thank you a lot 👍

**Comment by roll** [comment]
@antoniocali
Hi, from `frictionless@4.16` there is a `plugin.create_candidates` hook. Here is a full example with a custom type:

```python
    # Type
    class CustomType(Type):
        def read_cell(self, cell):
            return [cell] # make everything an array just for example

    # Plugin
    class CustomPlugin(Plugin):
        def create_candidates(self, candidates):
            candidates.insert(0, {"type": "custom"})

        def create_type(self, field):
            if field.type == "custom":
                return CustomType(field)

    # System
    plugin = CustomPlugin()
    system.register("custom", plugin)
```

That's how `system.create_candidates` returns without custom plugins (a detector will try these types on an detected cell from top to bottom):

```python
[{'type': 'yearmonth'},
 {'type': 'geopoint'},
 {'type': 'duration'},
 {'type': 'geojson'},
 {'type': 'object'},
 {'type': 'array'},
 {'type': 'datetime'},
 {'type': 'time'},
 {'type': 'date'},
 {'type': 'integer'},
 {'type': 'number'},
 {'type': 'boolean'},
 {'type': 'year'},
 {'type': 'string'}]
```

Using this hook you can also alter other detections details, for example, insert `{'type': 'datetime', 'format': 'any'}` before the default `datetime` candidate.

**Comment by antoniocali** [comment]
Thank you. It was very on point!
