### ISSUE TITLE
CKAN: Issue with mixed resource types

### ISSUE THREAD

**Issue by n0rdlicht** [frictionlessdata/frictionless-py#898]
# Overview

When using the built-in CKAN extension against some CKAN instances, e.g. `data.stadt-zuerich.ch` requests fail due to issues with some resources attached to a dataset. The requested [dataset](https://data.stadt-zuerich.ch/dataset/ted_taz_verkehrszaehlungen_werte_fussgaenger_velo) has a mixture of CSVs and PDFs as resources. The failing resource seems to be the PDF one.

## Example

e.g. running

```python
from frictionless import Package
from frictionless.plugins.ckan import CkanDialect

package = Package.from_ckan(
    "https://data.stadt-zuerich.ch", 
    dialect=CkanDialect(
        dataset="ted_taz_verkehrszaehlungen_werte_fussgaenger_velo",
    ),
)

package.resource_names
```

Results in
```
FrictionlessException: [storage-error] The storage has an error: CKAN returned an error: {"message": "Nicht gefunden: Resource \"f5d31b06-98df-44da-90cb-daf570ba84b1\" was not found.", "__type": "Not Found Error"}
```

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by n0rdlicht** [comment]
As a side issue: requests to the datastore api might want to exclude a total calculation as it adds a lot of overhead to each requests, see https://github.com/cividi/TransparenZRH/pull/101/files#diff-b014e93fcab9bae29f453d7a616da5eac2f02947f32d02a1a1bf200eeaab5a39R125 and associated PR https://github.com/cividi/TransparenZRH/pull/101 and https://ckan.org/blog/faster-datastore-in-ckan-2-7

e.g. in `ckan.py`
```python
def __read_ckan_table(self, name):
    params = {"id": self.__dataset}
    endpoint = f"{self.__endpoint}/package_show"
    response = self.__make_ckan_request(endpoint, params=params)
    for resource in response["result"]["resources"]:
        if name == resource.get("name", resource["id"]):
            endpoint = f"{self.__endpoint}/datastore_search"
            params = {"limit": 0, "resource_id": resource["id"], "include_total": False}
            response = self.__make_ckan_request(endpoint, params=params)
            return response["result"]

```

**Comment by roll** [comment]
Hi @n0rdlicht,

I'm releasing `frictionless@4.16.3` with a fix.

Also, thanks for your suggestion, I've added it to the CKAN TODO list - https://github.com/frictionlessdata/frictionless-py/issues/475
