### ISSUE TITLE
Diacritic in one cell breaks validation of whole datapackage

### ISSUE THREAD

**Issue by augusto-herrmann** [frictionlessdata/frictionless-py#905]
# Overview

I came across a behaviour that I think may be a bug. A certain diacritic character "ā", if present in *any* cell of *any* resource will cause the whole data package validation to fail.

## How to reproduce

Install a fresh environment with frictionless.

```bash
cd /tmp
mkdir frictionless-test
cd frictionless test
python3 -m venv pyenv
source pyenv/bin/activate
pip install frictionless==4.16.6
```

Create the following files.

**datapackage.json**
```json
{
    "profile": "data-package",
    "name": "encoding-test",
    "resources": [
        {
            "name": "ok1",
            "path": "ok1.csv"
        },
        {
            "name": "ok2",
            "path": "ok2.csv"
        }
    ]
}
```

**ok1.csv**
```csv
id,name
1,apple
```

**ok1.csv**
```csv
id,name
2,banana
```

Try to validate the data package:

```bash
frictionless validate datapackage.json
# -----
# valid: ok1.csv
# -----
# -----
# valid: ok2.csv
# -----
```

and everything goes ok. But if you add a new file with that character:

**this-breaks-everything.csv**

```csv
id,name
3,Kāwanatanga
```

and update `datapackage.json` accordingly:

```json
{
    "profile": "data-package",
    "name": "encoding-test",
    "resources": [
        {
            "name": "ok1",
            "path": "ok1.csv"
        },
        {
            "name": "ok2",
            "path": "ok2.csv"
        },
        {
            "name": "this-breaks-everything",
            "path": "this-breaks-everything.csv"
        }
    ]
}
```

and then try to validate, you get an error for the whole thing:

```bash
frictionless validate datapackage.json 
# -------
# invalid: datapackage.json
# -------
==============  =======================================================================================================================================
code            message                                                                                                                                
==============  =======================================================================================================================================
encoding-error  The data source could not be successfully decoded: 'charmap' codec can't decode byte 0x81 in position 12: character maps to <undefined>
==============  =======================================================================================================================================
```

i.e., even if wasn't able to parse `this-breaks-everything.csv` (and I think it should), it should at least still show the other resources as valid.

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by augusto-herrmann** [comment]
I just wanted to add that this problem does not occur with accents present in Western European languages, such as Portuguese, Spanish, French, etc. (i.e. á â à ã ä é ê è, etc.). The diacritic that creates the problem is ā present in the Māori language in New Zealand. Even though it is a valid unicode character. You can also use it in a python string without a problem.

**Comment by roll** [comment]
@augusto-herrmann 
There were two problems:
- a problem with validating functions. And thanks to your issue I solved kinda an important performance/edge case issue :+1:
- encoding detection is not correct for this file

I'm releasing `frictionless@4.19.3` that shows correct validation error and doesn't hide other validation tasks but it seems for this file you need to provide a correct encoding to make it valid

**Comment by augusto-herrmann** [comment]
That's awesome, @roll! Спасибо большое. :partying_face:
