### ISSUE TITLE
Consider more flexible field initialization

### ISSUE THREAD

**Issue by itcarroll** [frictionlessdata/frictionless-py#906]
The `frictionless.Schema` class ignores a list of [anything other than `dict`](https://github.com/frictionlessdata/frictionless-py/blob/bffe82989f0fc782cb51b0c83bf2dee521e55ad8/frictionless/schema.py#L287) for the `fields` keyword. Would you consider accepting any instance of `collections.abc.MutableMapping`? This would not be a breaking change because `isinstance(dict(), collections.abc.MutableMapping)` equals `true`.

My use case: I'm constructing the field metadata in a `pandas.DataFrame` and using the `into` keyword of `pandas.DataFrame.to_dict` to customize the mapping produced. My custom output subclasses `collections.abc.MutableMapping`, but is not an instance of `dict`.

**Comment by roll** [comment]
Hi @itcarroll,

We're definitely happy to support them as we did previously for `pathlib.Path`/etc. Are you interesting in PRing it? Or I can try slightly later (currently very busy for a few weeks)

**Comment by itcarroll** [comment]
Yep, I can work on a PR.

**Comment by itcarroll** [comment]
Forgot about this, but PR just submitted.

FYI - Discovered while working on this that `make test` fails with Python 3.10 b/c (ironically) the `savReaderWriter` package required with `frictionless[spss]` imports directly from `collections` rather than `collections.abc` (deprecated since 3.3 and removed in 3.10).
