### ISSUE TITLE
Core functionality missing

### ISSUE THREAD

**Issue by bkarolina** [frictionlessdata/frictionless-py#907]
# Overview

Hi there! 👋🏻 

While using frictionless we found out, we are missing few core functionalities:
* `field-merge`
* `field-pack`
* `field-rename`
Especially first is cumbersome, as we wanted to create `geometry` column by merging teo columns. Workaround is to `field-add` and use formula to do so, however this is not working in declarative way (that's is our desired way how to have it in our infrastructure).
* `Package`  functionality (write package = write all resources that it has, do something to all Resources, ....)

And one question - when we can expect Storage API?
> The Storage concpet is responsible for reading and writing data package from dataset source like CKAN, SQL, or others. Currently, the Storage API is not yet finished so you can try reading the codebase and implement your own storage but you need to be ready for some changes to the API that might come.

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi @bkarolina,

Thanks, we need to add them. I'm marking it as a feature request.

Regarding the Storage API, currently, we're discussing it with @pwalsh and @akariv. I think we might expect some progress on this coming month but to be honest it's months not days or weeks

**Comment by bkarolina** [comment]
Hi @roll, 
thanks, looking forward to have the features and I'll be checking on progress regarding Storage API 👀

**Comment by shashigharti** [comment]
Hi @bkarolina,

Thank you for the feature request! Regarding field-merge, field-pack, field-rename and package few examples of how you want to use it would be nice.

cc @roll @aivuk

**Comment by roll** [comment]
Here is a `spets.field_unpack`:

```python
def test_step_field_unpack():
    source = Resource(path="data/transform.csv")
    target = transform(
        source,
        steps=[
            steps.field_update(name="id", type="array", value=[1, 1]),
            steps.field_unpack(name="id", to_names=["id2", "id3"]),
        ],
    )
    assert target.schema == {
        "fields": [
            {"name": "name", "type": "string"},
            {"name": "population", "type": "integer"},
            {"name": "id2"},
            {"name": "id3"},
        ]
    }
    assert target.read_rows() == [
        {"name": "germany", "population": 83, "id2": 1, "id3": 1},
        {"name": "france", "population": 66, "id2": 1, "id3": 1},
        {"name": "spain", "population": 47, "id2": 1, "id3": 1},
    ]
```

I think `spets.field_pack` should by default revert this transform (creating an array from two fields):

```python
steps.field_pack(name="id", from_names=["id1", "id2"], preserve=False)
```

**Comment by roll** [comment]
Also, we have `steps.field_split`:

```python
def test_step_field_split():
    source = Resource(path="data/transform.csv")
    target = transform(
        source,
        steps=[
            steps.field_split(name="name", to_names=["name1", "name2"], pattern="a"),
        ],
    )
    assert target.schema == {
        "fields": [
            {"name": "id", "type": "integer"},
            {"name": "population", "type": "integer"},
            {"name": "name1", "type": "string"},
            {"name": "name2", "type": "string"},
        ]
    }
    assert target.read_rows() == [
        {"id": 1, "population": 83, "name1": "germ", "name2": "ny"},
        {"id": 2, "population": 66, "name1": "fr", "name2": "nce"},
        {"id": 3, "population": 47, "name1": "sp", "name2": "in"},
    ]
```

In my opinion `steps.field_merge` will revert it as:

```python
steps.field_merge(name="name", from_names=["name1", "name2"], joiner="a")
```

**Comment by roll** [comment]
Regarding `steps.field_rename`:
- is it the same as `steps.field_update(new_name='new')`?

**Comment by roll** [comment]
I add a few new feature requests to handle separately:
- #1062 
- #1063

**Comment by shashigharti** [comment]
> Regarding `steps.field_rename`:
> 
> * is it the same as `steps.field_update(new_name='new')`?

yes this is already there; we can rename the field using steps.field_update

**Comment by roll** [comment]
@shashigharti 
Cool! Let's implement then these two steps to make this issue done:
- `steps.field_merge`
- `steps.field_pack`
