### ISSUE TITLE
Cannot install Frictionless with poetry or pip with setuptools>=58.0

### ISSUE THREAD

**Issue by jaceklqed** [frictionlessdata/frictionless-py#908]
# Overview

Cannot install Frictionless with https://github.com/python-poetry/poetry - 

`docker run --rm python:3.9 bash -c "pip install poetry; poetry init -n; poetry add frictionless; poetry install"`

this produces an error:

```
(...)
  • Installing simpleeval (0.9.10)
  • Installing stringcase (1.2.0)
  • Installing typer (0.4.0)
  • Installing validators (0.18.2)

  EnvCommandError

 (...) 
      error in simpleeval setup command: use_2to3 is invalid.
```

I get a similar error when installing with pip:

`docker run --rm python:3.9 bash -c "pip install \"setuptools>=58.0\"; pip install frictionless"`

It seems to be a result of a bug in simpleeval https://github.com/danthedeckie/simpleeval/issues/90

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by martinjeannot** [comment]
We're currently running into the same issue installing frictionless with poetry. It breaks our CI with the following : 

```
ERROR: Command errored out with exit status 1:
       command: /root/.cache/pypoetry/virtualenvs/my-project-Rllp0j9V-py3.8/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-6ida3v9w/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-6ida3v9w/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-i20ssdkd
           cwd: /tmp/pip-req-build-6ida3v9w/
      Complete output (1 lines):
      error in simpleeval setup command: use_2to3 is invalid.
      ----------------------------------------
  WARNING: Discarding file:///root/.cache/pypoetry/artifacts/50/4e/74/88cd8798beec55242df644b9e03605a8f07b7508b9e23b8ee0a65ba486/simpleeval-0.9.10.tar.gz. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by roll** [comment]
Thanks! I'll investigate

**Comment by roll** [comment]
@jaceklqed 
@mariorodeghiero 
I've asked `simpleeval`'s author to take a look. It seems we need to wait a few days.

I tried one other option in #911 but it didn't work. Maybe other ideas?

PS.
Weirdly, it's not 100% reproducible, e.g. my env and our CI doesn't catch it yet

**Comment by sirex** [comment]
This fix worked for me: https://github.com/python-poetry/poetry/issues/4511

**Comment by roll** [comment]
Ok... #916 is also not good enough

**Comment by istrupin** [comment]
For Pipenv this worked for me as a workaround:

`pipenv install -e "git+https://github.com/graingert/simpleeval@acd8455dec557d551aae1b37b708eb7cd025b03b#egg=simpleeval"  `

That added this to the pipfile:
`simpleeval = {editable = true, ref = "acd8455dec557d551aae1b37b708eb7cd025b03b", git = "https://github.com/graingert/simpleeval"}`

Which, when I run a freeze, adds the below to `requirements.txt`:

`-e git+https://github.com/graingert/simpleeval@acd8455dec557d551aae1b37b708eb7cd025b03b#egg=simpleeval`

Certainly not a long term fix, but it got me unblocked in the meantime at least.

**Comment by loleg** [comment]
With frictionless **4.20.2**, also using poetry I was getting a similar error:

```
from frictionless import Package, Resource
  File "../python3.9/site-packages/frictionless/__init__.py", line 35, in <module>
    from . import checks
  File "../python3.9/site-packages/frictionless/checks/__init__.py", line 3, in <module>
    from .regulation import forbidden_value, sequential_value, row_constraint
  File "../python3.9/site-packages/frictionless/checks/regulation.py", line 1, in <module>
    import simpleeval
ModuleNotFoundError: No module named 'simpleeval'
```

This worked, in a pinch: `poetry add reportbro-simpleeval`

But rebuilding the virtualenv is a better solution:

`poetry env remove python && poetry install`

Just a heads up that some upgrades might not succeed cleanly.
