### ISSUE TITLE
A very bad CSV, that validate can not map

### ISSUE THREAD

**Issue by aborruso** [frictionlessdata/frictionless-py#929]
# Overview

Hi,
I have this [csv](https://github.com/frictionlessdata/frictionless-py/files/7359620/_11012018072326.csv) that has a lot of errors.

But, if I run 

```
frictionless validate --buffer-size 250000 --sample-size 750 _11012018072326.csv 
```

I have only the error below, that blocks the real CSV validation check.

I have no info about the real source encoding, then I apply this solution: I run `iconv -f utf-8 -t utf-8 -c input.csv >output.csv` and then I use `frictionless validate` on the output.

I know, it's not a real solution, but in this way I can map several useful CSV errors.

Is there a validate option, similar to the `iconv` one, to remove the unsupported character, and then to apply the validation to this cleaned input?

Thank you

```
===  =====  ==============  ============================================================================================================================
row  field  code            message
===  =====  ==============  ============================================================================================================================
            encoding-error  The data source could not be successfully decoded: 'utf-8' codec can't decode byte 0x8d in position 1447: invalid start byte
===  =====  ==============  ============================================================================================================================
```

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
@aborruso 
Can you at least guess what is the original encoding? It seems the detector can't infer it correctly.

You can try some others:

```
$ frictionless validate table.csv --encoding <some>
```

**Comment by aborruso** [comment]
> Can you at least guess what is the original encoding? It seems the detector can't infer it correctly.

The problem is this: probably the creator of the data forced a mix of encoding, creating an unreadable file.
Mine is a request to enable - via an option - the ability to check by skipping all unreadable characters.

**Comment by roll** [comment]
Ok. I see. I'll investigate

**Comment by aborruso** [comment]
> Can you at least guess what is the original encoding? It seems the detector can't infer it correctly.

I have made a testing loop, and it's `IBM850`. But to have an option to remove not recognized chars could be a raw way to have something from validate test, even in cases like this.

**Comment by roll** [comment]
Thanks @aborruso,

I've create a feature request for it - https://github.com/frictionlessdata/frictionless-py/issues/932

**Comment by aborruso** [comment]
> I've create a feature request for it - #932

Thank you very much!
