### ISSUE TITLE
validate: wrong stats output applying cli to a bad CSV

### ISSUE THREAD

**Issue by aborruso** [frictionlessdata/frictionless-py#930]
# Overview

Trying to validate [this](https://github.com/frictionlessdata/frictionless-py/files/7360258/_10012018141849.csv) this bad CSV file I have in the stats this:

```
"stats": {
          "hash": "",
          "bytes": 0,
          "fields": 247,
          "rows": 0
        }
```

It's not 0 bytes and it has more than 0 rows and fields.

I have used this command (4.19.5) `frictionless validate --buffer-size 250000 --sample-size 750  _10012018141849.csv --json`.

Thank you

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Thanks! I'll investigate

**Comment by roll** [comment]
Hi @aborruso,

In this case it hits the error limit which is indicated by `report.tasks[0].partial == True`.

It can be solved by extending this limit:

```
$ frictionless validate tmp/issue930.csv --limit-errors 10000 --json
```

**Comment by aborruso** [comment]
> It can be solved by extending this limit:

Thank you @roll 

Wouldn't it be better to warn the user in some way? To put an alert in the output, something like

```
{
  "version": "4.19.5",
  "time": 1.278,
  "errors": [],
  "alert": "the number of errors limit has been exceeded",
  ...
}
```

**Comment by roll** [comment]
@aborruso 
I agree, I have written it down here - https://github.com/frictionlessdata/frictionless-py/issues/933

**Comment by aborruso** [comment]
@roll what about to add in the CLI help the default value for `--limit-errors`.

Something like

```
  --limit-errors INTEGER          Limit errors by this integer [default: 1000]
```

And if there is also a default value for `--limit-memory`, add this to   `--limit-memory` CLI help message.

**Comment by roll** [comment]
Thanks @aborruso -- I've created an issue for it

**Comment by aborruso** [comment]
> Thanks @aborruso -- I've created an issue for it

Thank you!
