### ISSUE TITLE
Notify users about partial validations

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#933]
# Overview

Currently, there is a programmatic flag `report.tasks[n].partial == True` indicating that the validation task stopped before the end of the file hitting one of the limits error/row/memory/etc

It will be better to also notify end-users about it e.g. with a `warning`.

**Comment by fjuniorr** [comment]
I was also surprised by this behaviour. In my case, because of the default error limit of 1000, only the rows were reported as zero

```json
"stats": {
    "hash": "786821ef31ed9c6b56e1c4ef49dbc270",
    "bytes": 8550597,
    "fields": 14,
    "rows": 0
}
```

Another idea, not necessarily instead of the warning/message, might be to return `None` in this case to make the semantics of the value closer to what is happening.

**Comment by roll** [comment]
Hi @aivuk, WDYT?

I think we, at least, need a CLI indication for it

**Comment by shashigharti** [comment]
@roll WDYT of indicating this partial validations as general error?

```
# Errors 

code        message
----------  ------------------------------------------------------------------------------------
task-error  The task has an error: Stopped processing at row 5, maximum error limit "2" exceeded

# Validation Result 

# -------
# invalid: data/countries.csv 
# -------

  row    field  code        message
-----  -------  ----------  --------------------------------------------------
    4        5  extra-cell  Row at position "4" has an extra value in field at
                            position "5"
    7        2  missing-    Row at position "7" has a missing cell in field
                cell        "neighbor_id" at position "2"


```

**Comment by roll** [comment]
Hi @shashigharti,

No, it's not an error as a user you can do something like `frictionless validate table.csv --limit-rows 1000` -- ok, my first 1000 rows are valid

So the issue is about showing a note about partial validation -- somewhere near our new summary section (just a simple note line in cli)
