### ISSUE TITLE
New arguments for Detector `field_true/false_values`

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#941]
# Overview

It's possible to tweak e.g. `missing_values` using Detector but it would be also great to set True/False values without providing a full schema.

**Comment by roll** [comment]
@shashigharti 
Let's discuss this issue one of the next plannings

**Comment by shashigharti** [comment]
@roll Thank you!. Is there any example of how we currently set True/False values using full schema?

**Comment by roll** [comment]
@shashigharti 
Similar to this snippet - https://github.com/frictionlessdata/frictionless-py/blob/main/frictionless/detector.py#L438-L439 - there is `booleanField.true_value/false_value`

**Comment by roll** [comment]
A simple schema:

```yaml
fields:
  - name: a
    type: boolean
    trueValues: ['+']
```

**Comment by roll** [comment]
https://specs.frictionlessdata.io/table-schema/#boolean

**Comment by shashigharti** [comment]
@roll I have added the code and have few questions regarding the functionality. If I have this data
**Data:**
id,neighbor_id,name,population,natural_resources
1,,Britain,67,yes
2,3,France,67,yes
3,2,Germany,83,yes
4,,Italy,60,yes

When I describe above data shouldn't natural_resources be inferred as 'boolean'.
```
detector = Detector(field_missing_values=["", "67"], field_true_values=["yes"])
schema = describe_schema("../data/countries-truefalsevalues.csv", detector=detector)
print(schema.to_yaml("schema.yaml"))
```

**Comment by roll** [comment]
HI @shashigharti,

yes it's a good test case for this feature (although I would simplify the test code)

**Comment by shashigharti** [comment]
@roll Sorry i didnot understand the simplification part could you please explain it? Do you mean only testing using field_true_values=["yes"] ? 

or

detector = Detector(field_true_values=["yes", "1"], field_false_values=["no", "0"])
assert detector.field_true_values == ["yes", "1"]
assert detector.field_false_values == ["no", "0"]

**Comment by roll** [comment]
I mean having something focusd only on True/False values like:

```csv
id,value
1,yes
2,no
```

```python
with Resource('table.csv', detector=Detector(field_true_values=['yes'], field_false_values=['no']):
  assert resource.schema.get_field('value').type == 'boolean'
  assert resource.read_rows() == [{'id': 1, 'value': True}, {'id': 2, 'value': False}]
```

And similar tests
