### ISSUE TITLE
Resources with duplicate property "name" in datapackage.json files

### ISSUE THREAD

**Issue by gabrielbdornas** [frictionlessdata/frictionless-py#942]
# Overview

The `frictionless validate` option doesn't return any error if a datapackage.json contains two resources with the same "name" property.

I believe that it could be validated for two reasons:

Frist: Because as pointed in frictionless [specs](https://specs.frictionlessdata.io/data-resource/#metadata-properties) "if present, the name MUST be unique amongst all resources in this data package".

Second: As I tested, if [package.get_resource function](https://framework.frictionlessdata.io/docs/references/api-reference/#packageget_resource) is needed to extract the resource information, only the first resource listed in my datapackage.json will the returned.

What makes more sense: an error during `frictionless validate` call or return all resources with the same name in package.get_resource function?

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by augusto-herrmann** [comment]
IMHO this situation should definitely raise a validation error, as it violates the specs.

I don't think the specs should be changed in this regard, because if resources are not unique it would create difficulties in identifying and accessing them.

**Comment by roll** [comment]
Thanks! 

It's a bug for sure

**Comment by gabrielbdornas** [comment]
Thanks for your help @roll
