### ISSUE TITLE
302 redirect

### ISSUE THREAD

**Issue by pierredittgen** [frictionlessdata/frictionless-py#950]
# Overview

Using frictionless (4.21.2) CLI to validate a CSV file available from a 302 redirect URL leads to strange behaviour.

The incriminated URL is <https://demo.data.gouv.fr/fr/datasets/r/d4d78089-f218-40b6-a86a-d7cc4e624b0c>. It redirects to <https://static.data.gouv.fr/resources/donnees-essentielles-de-conventions-de-subvention-a-antibes/20200325-153014/antibes-subventions-2017.csv> using `Location` http header.

Validating the primary URL using frictionless:

```bash
> frictionless validate --schema https://git.opendatafrance.net/scdl/subventions/-/raw/v2.0.1/schema.json https://demo.data.gouv.fr/fr/datasets/r/d4d78089-f218-40b6-a86a-d7cc4e624b0c

# -----
# valid: https://demo.data.gouv.fr/fr/datasets/r/d4d78089-f218-40b6-a86a-d7cc4e624b0c
# -----
```

Validating the target url:

```bash
frictionless validate --schema https://git.opendatafrance.net/scdl/subventions/-/raw/v2.0.1/schema.json https://static.data.gouv.fr/resources/donnees-essentielles-de-conventions-de-subvention-a-antibes/20200325-153014/antibes-subventions-2017.csv

# -------
# invalid: https://static.data.gouv.fr/resources/donnees-essentielles-de-conventions-de-subvention-a-antibes/20200325-153014/antibes-subventions-2017.csv
# -------
==========  ======================================
code        message
==========  ======================================
task-error  The task has an error: 'fieldPosition'
==========  ======================================
```

So I got some questions/remarks:
- it seems that frictionless doesn't support 302 redirect. Am I wrong? If not, do you plan to implement it or is there a workaround to deal with this type of URL?
- first frictionless command reports a valid result. It's strange as the URL body is HTML and not tabular data (?)
- second frictionless command reports an invalid result. How should the message be understood?

Thanks in advance for your help.

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Thanks, @pierredittgen!

I'll investigate

**Comment by roll** [comment]
Hi @pierredittgen,

I can't access the link. Are they publicly available?

**Comment by johanricher** [comment]
The dataset was updated, here are new example links:
- URL ([accessible to the user on that page](https://www.data.gouv.fr/fr/datasets/donnees-essentielles-de-conventions-de-subvention-attribuees-par-la-ville-dantibes/)) https://www.data.gouv.fr/fr/datasets/r/9d65d9fd-a65f-43fc-9202-dd8d78b2a596
- which redirects to: https://static.data.gouv.fr/resources/donnees-essentielles-de-conventions-de-subvention-attribuees-par-la-ville-dantibes/20211216-154317/antibes-subventions.csv

**Comment by roll** [comment]
Hi @johanricher @pierredittgen 

The problem was with the internal issue that was hiding actual errors (after releasing #974):

```bash
frictionless validate https://www.data.gouv.fr/fr/datasets/r/9d65d9fd-a65f-43fc-9202-dd8d78b2a596 --format csv --schema https://git.opendatafrance.net/scdl/subventions/-/raw/v2.0.1/schema.json
```

Now it works; just don't forget to specify the format. The CSV fails in many ways because it's not actually comma-separated (not related to the issue)

**Comment by johanricher** [comment]
Thanks @roll! We'll test on our side and let you know if we still have related issues.
