### ISSUE TITLE
Resources path are interpreted as relative to the current directory

### ISSUE THREAD

**Issue by niconoe** [frictionlessdata/frictionless-py#956]
I have a simple script that calls the `validate_package()` function. The package I want to validate is located in a different directory than the validation script. `datapackage.json` references a resource with path `deployments.csv`

The validation fails (cannot access ressource) because frictionless intereprets the resource path such as:

`VALIDATION_SCRIPT/deployments.csv`

while it would seem more logical to understand it as:

`DIRECTORY_THAT_CONTAINS_DATAPACKAGE.JSON/deployments.csv`

The specs seems to agree it's not the intended behaviour:

> POSIX paths (unix-style with / as separator) are supported for referencing local files, with the security restraint that they MUST be relative siblings or children of the descriptor.

To be more precise, it seems frictionless actually interpret this path as relative to the current working directory (which happens in most case to be the same than the directory of the validation script), since I can circumvent the problem by calling `os.chdir(DESCRIPTOR_PATH_DIRECTORY)` before calling validate_package().

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Thank you! I'll investigate

**Comment by roll** [comment]
Hi @niconoe,

I can't reproduce the problem. 

Many of our tests use different package directories - https://github.com/frictionlessdata/frictionless-py/blob/main/tests/test_package.py - and it passes on Linux/Mac/Windows

Can you please provide an example (data/script) that fails?

**Comment by niconoe** [comment]
@roll : no problem!

I just created a repository with a minimal reproducible example: https://github.com/niconoe/show_frictionless_issue (explanations on how to use in README.md).

**Comment by roll** [comment]
Thanks, @niconoe, I got it.

The problem is that Frictionless can only properly handle relative paths in data packages if it's located in some file system (local or remote). When you read the JSON file into memory we lose basepath information for this data package.

The simplest fix is just to provide a package path to the `validate` function:

```python
from frictionless import validate

report = validate('path/to/datapackage.json')
```

If for some reason you want to use a package descriptor from memory the fix will be:

```python
with open(EXAMPLE_DESCRIPTOR_PATH) as json_file:
    descriptor_data = json.load(json_file)
    report = validate(descriptor_data, basepath=os.path.dirname(EXAMPLE_DESCRIPTOR_PATH))
```

Please re-open the issue if you need more help :+1:
