### ISSUE TITLE
SQL plugin fails with foreign key constraint on PostgreSQL when writing a package whose resources are not in dependency order

### ISSUE THREAD

**Issue by davidpeckham** [frictionlessdata/frictionless-py#957]
# Overview

The SQL plugin fails while writing package resources to PostgreSQL when those resources are not in order by foreign key dependencies (ancestors first). It wrote data to a child table before foreign keys were written to the parent table, causing a foreign key constraint violation.

## Test Case

To reproduce this error, I reordered the resources in [data/storage/integrity.json](https://github.com/frictionlessdata/frictionless-py/blob/dde69f276cde3f22e0d8e5dece3ac5d1474cce2c/data/storage/integrity.json) so that the child resource (`integrity_link`) comes before the parent resource (`integrity_main`). After making that change, [test_sql_storage_postgresql_integrity](https://github.com/frictionlessdata/frictionless-py/blob/dde69f276cde3f22e0d8e5dece3ac5d1474cce2c/tests/plugins/test_sql.py#L514) fails with a foreign key violation.

Here is the modified test data:

```
{
  "resources": [
    {
      "name": "integrity_link",
      "schema": {
        "fields": [
          {"name": "main_id", "type": "integer"},
          {"name": "some_id", "type": "integer", "constraints": {"unique": true}},
          {"name": "description", "type": "string", "constraints": {"unique": true}}
        ],
        "primaryKey": ["main_id", "some_id"],
        "foreignKeys": [
          {"fields": ["main_id"], "reference": {"resource": "integrity_main", "fields": ["id"]}}
        ]
      },
      "data": [
        ["main_id", "some_id", "description"],
        ["1", "1", "note1"],
        ["2", "2", "note2"]
      ]
    },
    {
      "name": "integrity_main",
      "schema": {
        "fields": [
          {"name": "id", "type": "integer"},
          {"name": "parent", "type": "integer"},
          {"name": "description", "type": "string"}
        ],
        "primaryKey": ["id"],
        "foreignKeys": [
          {"fields": ["parent"], "reference": {"resource": "", "fields": ["id"]}}
        ]
      },
      "data": [
        ["id", "parent", "description"],
        ["1", "", "english"],
        ["2", "1", "中国人"]
      ]
    }
  ]
}
```

## Problem

[SqlStorage.write_package](https://github.com/frictionlessdata/frictionless-py/blob/dde69f276cde3f22e0d8e5dece3ac5d1474cce2c/frictionless/plugins/sql.py#L355) writes resources in the order they appear in the package, so it's possible for a child table to be written before a parent table:

```
# Write data
for resource in package.resources:
    self.__write_convert_data(resource)
```

## Workaround

I was able to workaround this by changing `write_package` to write resources in dependency order:

```
# Write data
existent_names = list(self)
for name in existent_names:
    if package.has_resource(name):
        self.__write_convert_data(package.get_resource(name))
```

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Thanks for reporting!

**Comment by davidpeckham** [comment]
You're welcome. Thank you for SQL Plugin! I appreciate the attention to detail in creating package metadata and constraints in the PostgreSQL schema.

**Comment by roll** [comment]
Thanks for providing the fix! I'm releasing it
