### ISSUE TITLE
excel plugin error

### ISSUE THREAD

**Issue by sarenaz** [frictionlessdata/frictionless-py#960]
Hello everyone, 

I tried to install frictionless excel plugin and got an error. This is what I typed `pip install frictionless[excel]` and this is the error message that I received `zsh: no matches found: frictionless[excel]`. I'm on a mac, frictionless version 4.22.3 and python version 3.10.0. I also tried this on Jupyter Notebook and got the same error. I asked @lwinfree to check and she got the same error. Let me know if you need more information and thank you 😄  @roll

**Comment by roll** [comment]
Hi @sarenaz,

You need to quote the name as your CLI tries to do some glob matching:

```bash
$ pip install 'frictionless[excel]'
```

We need to update the docs to notify users

**Comment by sarenaz** [comment]
thank you @roll this helps a lot
