### ISSUE TITLE
Is there a way to have in output only the valid rows?

### ISSUE THREAD

**Issue by aborruso** [frictionlessdata/frictionless-py#963]
# Overview

Imagine I have a CSV, in which only few lines have an error.
Is it possible to run a cli command to have in output valid lines only?

If no, this is a feature request.

Thank you

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
MERGED into #1004

**Comment by aborruso** [comment]
@roll when do you think to release it?

Thank you very much for this feature

**Comment by roll** [comment]
Hi @shashigharti can you please release a new version?

**Comment by shashigharti** [comment]
@aborruso @roll New version released!

**Comment by aborruso** [comment]
Thank you very much

**Comment by aborruso** [comment]
Wow, really great, I have tested it: thank you very much @shashigharti and @roll
