### ISSUE TITLE
SQLite resource fails when `basepath` is non-empty

### ISSUE THREAD

**Issue by suvayu** [frictionlessdata/frictionless-py#964]
## Setup
Let us first create a dummy SQLite database in a directory

```bash
$ mkdir testing/
$ sqlite3 testing/dummy.db <<EOF
> CREATE TABLE test_table (id integer, name varchar(255));
> INSERT INTO test_table VALUES (1, 'foo');
> INSERT INTO test_table VALUES (2, 'bar');
> INSERT INTO test_table VALUES (3, 'baz');
> EOF
```

## Use `frictionless` from Python
```python
from frictionless import Resource
from frictionless.plugins.sql import SqlDialect

dialect = SqlDialect(table="test_table")

# works
res1 = Resource(
    "sqlite:///testing/dummy.db", basepath="", dialect=dialect, scheme="sqlite"
)
res1.infer()
print(res1)

# fails
res2 = Resource(
    "sqlite:///dummy.db", basepath="testing", dialect=dialect, scheme="sqlite"
)
res2.infer()
```
The above code leads to the following exception:
```python
Traceback (most recent call last):
  File "/home/user/code/testing/frictionless-sqlite-bug/debug.py", line 16, in <module>
    res2.infer()
  File "/home/user/.virtualenvs/sark/lib/python3.9/site-packages/frictionless/resource.py", line 724, in infer
    with self:
  File "/home/user/.virtualenvs/sark/lib/python3.9/site-packages/frictionless/resource.py", line 288, in __enter__
    self.open()
  File "/home/user/.virtualenvs/sark/lib/python3.9/site-packages/frictionless/resource.py", line 769, in open
    self.__parser.open()
  File "/home/user/.virtualenvs/sark/lib/python3.9/site-packages/frictionless/parser.py", line 76, in open
    self.__list_stream = self.read_list_stream()
  File "/home/user/.virtualenvs/sark/lib/python3.9/site-packages/frictionless/parser.py", line 117, in read_list_stream
    for cells in list_stream:
  File "/home/user/.virtualenvs/sark/lib/python3.9/site-packages/frictionless/parser.py", line 174, in __next__
    return self.list_stream.__next__()
  File "/home/user/.virtualenvs/sark/lib/python3.9/site-packages/frictionless/plugins/sql.py", line 159, in read_list_stream_create
    resource = storage.read_resource(
  File "/home/user/.virtualenvs/sark/lib/python3.9/site-packages/frictionless/plugins/sql.py", line 235, in read_resource
    raise FrictionlessException(errors.StorageError(note=note))
frictionless.exception.FrictionlessException: [storage-error] The storage has an error: Resource "test_table" does not exist
```
You can see it fails because it tries to open a database in the current directory instead of inside `testing`.  There is an empty db file in the current directory:
```bash
$ ls -lhtr
total 8.0K
drwxrwxr-x. 1 user user  16 Jan 10 01:28 testing
-rw-r--r--. 1 user user 415 Jan 10 01:37 debug.py
-rw-r--r--. 1 user user   0 Jan 10 01:37 dummy.db
```

## Analysis
In `SqlParser`, `SqlStorage` is instantiated like this:
https://github.com/frictionlessdata/frictionless-py/blob/fc2070f0e8b9baaad4857524c54ca3e51223ec40/frictionless/plugins/sql.py#L158
This looks correct, I believe the problem lies in `helpers.py`, in `is_remote_path` and `join_path`.
https://github.com/frictionlessdata/frictionless-py/blob/fc2070f0e8b9baaad4857524c54ca3e51223ec40/frictionless/helpers.py#L182-L199

When you create a resource, a File object is created here:
https://github.com/frictionlessdata/frictionless-py/blob/fc2070f0e8b9baaad4857524c54ca3e51223ec40/frictionless/resource.py#L171-L179

`File.__init__` invokes this snippet:
https://github.com/frictionlessdata/frictionless-py/blob/fc2070f0e8b9baaad4857524c54ca3e51223ec40/frictionless/file.py#L134-L135

For `sqlite`, currently it simply returns `path`, when it should return something like `{scheme}:///{basepath}/{path}`

A possible implementation could look like this (it has to be incorporated into `is_remote_path` and `join_path`):
```python
parsed = urlparse(path)
result = "{scheme}:///{basepath}{path}".format(scheme=parsed.scheme, basepath=basepath, path=parsed.path)
```

Thoughts?

**Comment by suvayu** [comment]
I have been looking at the code, some comments.

- all resources with a non-empty `scheme` (basically anything that isn't a `file`) is treated like a URL.  While files are treated like local paths, e.g. has to satisfy checks like "is a sub path of `basepath`".
- however `sqlite` falls in the middle, and currently the code treats it as a URL, as a consequence, leads to few issues.
  - when creating a zip archive, the db file is **not** included in the archive! <sup>1</sup>
  - `resource.fullpath` is incorrect

I see two ways of dealing with this:
1. fix/special case how `sqlite` is treated in `file.py::File`
   - `scheme` is `sqlite`, and `fullpath` is `{basepath}/{path}` (note `scheme` is absent, so existing helpers work unaltered)
   - `SqlStorage` then uses `{scheme}:///{fullpath}`
2. special case `sqlite` where relevant
   - the functions I mentioned in `helpers.py`
   - unit tests
   - `Package.to_zip`

I think (**1**) is a better fix, but possibly more work.

#### Footnote
1. There's an unrelated issue; while creating the archive, there is a security check if the path being included is an absolute path or not, however this is done for `fullpath` not `path`.  This leads to the following discrepancy:
   ```
   Resource("mydata.csv", basepath="a_subdir") # can be included in a zip
   Resource("mydata.csv", basepath="/absolute/path/to/a_subdir") # can't be included in a zip
   ```

**Comment by roll** [comment]
Thanks @suvayu, I'll be on it soon. Thanks for the analysis!

**Comment by roll** [comment]
Hi @suvayu,

I'm releasing `frictionless@4.24` that supports `SqlDialect.basepath`. Here is an example - https://framework.frictionlessdata.io/docs/tutorials/formats/sql-tutorial/#sqlite

I've weighted different options and all of them including `resource.basepath` were against the rule that `basepath` is only applicable to relative paths and SQL plugin encapsulation. So `SqlDialect.basepath` seems to be the most acceptable in my opinion

**Comment by suvayu** [comment]
@roll Thanks a lot for the rapid fix!  I'll have look :)
