### ISSUE TITLE
frictionless validator fails on inline data resource (datapackage validator works)

### ISSUE THREAD

**Issue by wingechr** [frictionlessdata/frictionless-py#965]
# Steps to reproduce

running `frictionless validate --type package datapackage.json`

with `datapackage.json`:
```json
{
    "profile": "data-package",
    "resources": [
        {
            "profile": "data-resource",
            "name": "my_inline_data",            
            "data": "MY_INLINE_DATA"
        }
    ]
}
```

using frictionless 4.22.0:

# Expected behaviour

valid 

# Actual behaviour

results in: `scheme-error  The data source could not be successfully loaded: [Errno 2] No such file or directory: 'MY_INLINE_DATA'`

# Notes

running `datapackage validate datapackage.json` (v1.15.2) works

**Comment by roll** [comment]
Thank you! I'll investigate

**Comment by roll** [comment]
Hi @wingechr,

The data property only accepts an array for data arrays or mappings, for example:

> https://specs.frictionlessdata.io/tabular-data-resource/#json-tabular-data

```
{
    "profile": "data-package",
    "resources": [
        {
            "profile": "data-resource",
            "name": "my_inline_data",
            "data": [["field1", "field2"], ["value1", "value2]]
        }
    ]
}
```
```
frictionless validate tmp/issue965/datapackage.json
# -----
# valid: my_inline_data
# -----
```

Although the error message is confusing. I'll create an issue to improve it.
