### ISSUE TITLE
Provide validation hints for common mistakes?

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#993]
# Overview

For example, one can define `missingValues` on the resource level instead of the schema level. It's a common mistake and according to the standards a resource having `missingValues` is perfectly valid (because props set are customizable and open-ended). In this case (and similar), the framework might emit a warning in the validation report.

---

Missed schema level (`resource -> fields` instead of `resource -> schema -> fields`) - https://github.com/frictionlessdata/frictionless-py/issues/1043

**Comment by roll** [comment]
@shashigharti 
Let's discuss next week on Github/Slack how we're going to handle it

**Comment by shashigharti** [comment]
@roll will we only handle two cases for now: missing values and fields for this issue? 

If yes, I have a question regarding fields, both of this work(with and without schema). 

```
descriptor = {
  "name": "test-tabulator",
  "resources": [
    {
      "name": "number-two",
      "path": "993/table.csv",
      "fields": [
        {
          "name": "id",
          "type": "integer"
        },
        {
          "name": "name",
          "type": "string"
        }
      ]
    }
  ]
}
```
```
descriptor = {
  "name": "test-tabulator",
  "resources": [
    {
      "name": "number-two",
      "path": "993/table.csv",
      "schema": {
        "fields": [
          {
            "name": "id",
            "type": "integer",            
          },
          {
            "name": "name",
            "type": "string"
          }
        ]        
      }
    }
  ]
}
```

**Comment by roll** [comment]
@shashigharti 
Both work but the first one will not have any effect -- that's the problem. So we need to notify the user about it

I would add a `resource-error` in `resource.metadata_validate` saying that the `fields` property should be on schema

The same for the `missingValues`
